// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsManualBackupClusterInfoConfigurationNodeConfigurationResourceConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("amount")]
        public Input<double>? Amount { get; set; }

        [Input("resourceType")]
        public Input<string>? ResourceType { get; set; }

        [Input("resourceUnit")]
        public Input<string>? ResourceUnit { get; set; }

        public AccountsManualBackupClusterInfoConfigurationNodeConfigurationResourceConfigurationArgs()
        {
        }
        public static new AccountsManualBackupClusterInfoConfigurationNodeConfigurationResourceConfigurationArgs Empty => new AccountsManualBackupClusterInfoConfigurationNodeConfigurationResourceConfigurationArgs();
    }
}
