// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsClusterConfigurationDatabaseConfigurationServiceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Secret to use for the main API key.
        /// </summary>
        [Input("apiKey")]
        public Input<Inputs.AccountsClusterConfigurationDatabaseConfigurationServiceApiKeyArgs>? ApiKey { get; set; }

        [Input("enableTls")]
        public Input<bool>? EnableTls { get; set; }

        [Input("forceIncludeJwtRbac")]
        public Input<bool>? ForceIncludeJwtRbac { get; set; }

        [Input("jwtRbac")]
        public Input<bool>? JwtRbac { get; set; }

        /// <summary>
        /// Secret to use for the read-only API key.
        /// </summary>
        [Input("readOnlyApiKey")]
        public Input<Inputs.AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKeyArgs>? ReadOnlyApiKey { get; set; }

        public AccountsClusterConfigurationDatabaseConfigurationServiceArgs()
        {
        }
        public static new AccountsClusterConfigurationDatabaseConfigurationServiceArgs Empty => new AccountsClusterConfigurationDatabaseConfigurationServiceArgs();
    }
}
