// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsManualBackupClusterInfoConfigurationNodeConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("packageId")]
        public Input<string>? PackageId { get; set; }

        [Input("resourceConfigurations")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationNodeConfigurationResourceConfigurationGetArgs>? _resourceConfigurations;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationNodeConfigurationResourceConfigurationGetArgs> ResourceConfigurations
        {
            get => _resourceConfigurations ?? (_resourceConfigurations = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationNodeConfigurationResourceConfigurationGetArgs>());
            set => _resourceConfigurations = value;
        }

        public AccountsManualBackupClusterInfoConfigurationNodeConfigurationGetArgs()
        {
        }
        public static new AccountsManualBackupClusterInfoConfigurationNodeConfigurationGetArgs Empty => new AccountsManualBackupClusterInfoConfigurationNodeConfigurationGetArgs();
    }
}
