// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsClusterConfigurationDatabaseConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Audit logging configuration for the Qdrant database.
        /// </summary>
        [Input("auditLogging")]
        public Input<Inputs.AccountsClusterConfigurationDatabaseConfigurationAuditLoggingArgs>? AuditLogging { get; set; }

        /// <summary>
        /// Default collection parameters.
        /// </summary>
        [Input("collection")]
        public Input<Inputs.AccountsClusterConfigurationDatabaseConfigurationCollectionArgs>? Collection { get; set; }

        /// <summary>
        /// Inference service configuration.
        /// </summary>
        [Input("inference")]
        public Input<Inputs.AccountsClusterConfigurationDatabaseConfigurationInferenceArgs>? Inference { get; set; }

        /// <summary>
        /// Logging level for the database. Must be one of: DATABASE_CONFIGURATION_LOG_LEVEL_DEBUG, DATABASE_CONFIGURATION_LOG_LEVEL_ERROR, DATABASE_CONFIGURATION_LOG_LEVEL_INFO, DATABASE_CONFIGURATION_LOG_LEVEL_OFF, DATABASE_CONFIGURATION_LOG_LEVEL_TRACE, DATABASE_CONFIGURATION_LOG_LEVEL_WARN.
        /// </summary>
        [Input("logLevel")]
        public Input<string>? LogLevel { get; set; }

        /// <summary>
        /// Service-related configuration.
        /// </summary>
        [Input("service")]
        public Input<Inputs.AccountsClusterConfigurationDatabaseConfigurationServiceArgs>? Service { get; set; }

        /// <summary>
        /// Storage-related configuration.
        /// </summary>
        [Input("storage")]
        public Input<Inputs.AccountsClusterConfigurationDatabaseConfigurationStorageArgs>? Storage { get; set; }

        /// <summary>
        /// TLS configuration for the database.
        /// </summary>
        [Input("tls")]
        public Input<Inputs.AccountsClusterConfigurationDatabaseConfigurationTlsArgs>? Tls { get; set; }

        public AccountsClusterConfigurationDatabaseConfigurationArgs()
        {
        }
        public static new AccountsClusterConfigurationDatabaseConfigurationArgs Empty => new AccountsClusterConfigurationDatabaseConfigurationArgs();
    }
}
