// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsRolePermissionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Permission category (e.g., "Cluster", "Account").
        /// </summary>
        [Input("category")]
        public Input<string>? Category { get; set; }

        /// <summary>
        /// Permission value (e.g., "read:backups").
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public AccountsRolePermissionGetArgs()
        {
        }
        public static new AccountsRolePermissionGetArgs Empty => new AccountsRolePermissionGetArgs();
    }
}
