// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("secretKey")]
        public Input<string>? SecretKey { get; set; }

        [Input("secretName")]
        public Input<string>? SecretName { get; set; }

        public AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyGetArgs()
        {
        }
        public static new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyGetArgs Empty => new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyGetArgs();
    }
}
