// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsHybridCloudEnvironmentStatusVolumeSnapshotClassGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("driver")]
        public Input<string>? Driver { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public AccountsHybridCloudEnvironmentStatusVolumeSnapshotClassGetArgs()
        {
        }
        public static new AccountsHybridCloudEnvironmentStatusVolumeSnapshotClassGetArgs Empty => new AccountsHybridCloudEnvironmentStatusVolumeSnapshotClassGetArgs();
    }
}
