// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsManualBackupClusterInfoConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowedIpSourceRanges")]
        private InputList<string>? _allowedIpSourceRanges;
        public InputList<string> AllowedIpSourceRanges
        {
            get => _allowedIpSourceRanges ?? (_allowedIpSourceRanges = new InputList<string>());
            set => _allowedIpSourceRanges = value;
        }

        [Input("annotations")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationAnnotationArgs>? _annotations;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationAnnotationArgs> Annotations
        {
            get => _annotations ?? (_annotations = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationAnnotationArgs>());
            set => _annotations = value;
        }

        [Input("clusterStorageConfigurations")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationClusterStorageConfigurationArgs>? _clusterStorageConfigurations;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationClusterStorageConfigurationArgs> ClusterStorageConfigurations
        {
            get => _clusterStorageConfigurations ?? (_clusterStorageConfigurations = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationClusterStorageConfigurationArgs>());
            set => _clusterStorageConfigurations = value;
        }

        [Input("databaseConfigurations")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationArgs>? _databaseConfigurations;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationArgs> DatabaseConfigurations
        {
            get => _databaseConfigurations ?? (_databaseConfigurations = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationArgs>());
            set => _databaseConfigurations = value;
        }

        [Input("gpuType")]
        public Input<string>? GpuType { get; set; }

        [Input("lastModifiedAt")]
        public Input<string>? LastModifiedAt { get; set; }

        [Input("nodeConfigurations")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationNodeConfigurationArgs>? _nodeConfigurations;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationNodeConfigurationArgs> NodeConfigurations
        {
            get => _nodeConfigurations ?? (_nodeConfigurations = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationNodeConfigurationArgs>());
            set => _nodeConfigurations = value;
        }

        [Input("nodeSelectors")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationNodeSelectorArgs>? _nodeSelectors;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationNodeSelectorArgs> NodeSelectors
        {
            get => _nodeSelectors ?? (_nodeSelectors = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationNodeSelectorArgs>());
            set => _nodeSelectors = value;
        }

        [Input("numberOfNodes")]
        public Input<double>? NumberOfNodes { get; set; }

        [Input("podLabels")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationPodLabelArgs>? _podLabels;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationPodLabelArgs> PodLabels
        {
            get => _podLabels ?? (_podLabels = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationPodLabelArgs>());
            set => _podLabels = value;
        }

        [Input("rebalanceStrategy")]
        public Input<string>? RebalanceStrategy { get; set; }

        [Input("reservedCpuPercentage")]
        public Input<double>? ReservedCpuPercentage { get; set; }

        [Input("reservedMemoryPercentage")]
        public Input<double>? ReservedMemoryPercentage { get; set; }

        [Input("restartPolicy")]
        public Input<string>? RestartPolicy { get; set; }

        [Input("serviceAnnotations")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationServiceAnnotationArgs>? _serviceAnnotations;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationServiceAnnotationArgs> ServiceAnnotations
        {
            get => _serviceAnnotations ?? (_serviceAnnotations = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationServiceAnnotationArgs>());
            set => _serviceAnnotations = value;
        }

        [Input("serviceType")]
        public Input<string>? ServiceType { get; set; }

        [Input("tolerations")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationTolerationArgs>? _tolerations;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationTolerationArgs> Tolerations
        {
            get => _tolerations ?? (_tolerations = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationTolerationArgs>());
            set => _tolerations = value;
        }

        [Input("topologySpreadConstraints")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationTopologySpreadConstraintArgs>? _topologySpreadConstraints;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationTopologySpreadConstraintArgs> TopologySpreadConstraints
        {
            get => _topologySpreadConstraints ?? (_topologySpreadConstraints = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationTopologySpreadConstraintArgs>());
            set => _topologySpreadConstraints = value;
        }

        [Input("version")]
        public Input<string>? Version { get; set; }

        public AccountsManualBackupClusterInfoConfigurationArgs()
        {
        }
        public static new AccountsManualBackupClusterInfoConfigurationArgs Empty => new AccountsManualBackupClusterInfoConfigurationArgs();
    }
}
