// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsClusterStatusScalabilityInfoArgs : global::Pulumi.ResourceArgs
    {
        [Input("reason")]
        public Input<string>? Reason { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        public AccountsClusterStatusScalabilityInfoArgs()
        {
        }
        public static new AccountsClusterStatusScalabilityInfoArgs Empty => new AccountsClusterStatusScalabilityInfoArgs();
    }
}
