// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiKeys")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyGetArgs>? _apiKeys;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyGetArgs> ApiKeys
        {
            get => _apiKeys ?? (_apiKeys = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyGetArgs>());
            set => _apiKeys = value;
        }

        [Input("enableTls")]
        public Input<bool>? EnableTls { get; set; }

        [Input("forceIncludeJwtRbac")]
        public Input<bool>? ForceIncludeJwtRbac { get; set; }

        [Input("jwtRbac")]
        public Input<bool>? JwtRbac { get; set; }

        [Input("readOnlyApiKeys")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyGetArgs>? _readOnlyApiKeys;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyGetArgs> ReadOnlyApiKeys
        {
            get => _readOnlyApiKeys ?? (_readOnlyApiKeys = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyGetArgs>());
            set => _readOnlyApiKeys = value;
        }

        public AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceGetArgs()
        {
        }
        public static new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceGetArgs Empty => new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceGetArgs();
    }
}
