// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsHybridCloudEnvironmentConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Advanced operator settings as a YAML string.
        /// </summary>
        [Input("advancedOperatorSettings")]
        public Input<string>? AdvancedOperatorSettings { get; set; }

        /// <summary>
        /// CA certificates for custom certificate authorities.
        /// </summary>
        [Input("caCertificates")]
        public Input<string>? CaCertificates { get; set; }

        /// <summary>
        /// Chart registry URL.
        /// </summary>
        [Input("chartRepositoryUrl")]
        public Input<string>? ChartRepositoryUrl { get; set; }

        /// <summary>
        /// Container registry URL.
        /// </summary>
        [Input("containerRegistryUrl")]
        public Input<string>? ContainerRegistryUrl { get; set; }

        [Input("controlPlaneLabels")]
        private InputList<Inputs.AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelGetArgs>? _controlPlaneLabels;

        /// <summary>
        /// Additional labels to apply to control plane components.
        /// </summary>
        public InputList<Inputs.AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelGetArgs> ControlPlaneLabels
        {
            get => _controlPlaneLabels ?? (_controlPlaneLabels = new InputList<Inputs.AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelGetArgs>());
            set => _controlPlaneLabels = value;
        }

        /// <summary>
        /// Default database storage class.
        /// </summary>
        [Input("databaseStorageClass")]
        public Input<string>? DatabaseStorageClass { get; set; }

        /// <summary>
        /// Optional HTTP proxy URL.
        /// </summary>
        [Input("httpProxyUrl")]
        public Input<string>? HttpProxyUrl { get; set; }

        /// <summary>
        /// Optional HTTPS proxy URL.
        /// </summary>
        [Input("httpsProxyUrl")]
        public Input<string>? HttpsProxyUrl { get; set; }

        /// <summary>
        /// Last modification timestamp of the configuration.
        /// </summary>
        [Input("lastModifiedAt")]
        public Input<string>? LastModifiedAt { get; set; }

        /// <summary>
        /// Log level for deployed components. Must be one of: HYBRID_CLOUD_ENVIRONMENT_CONFIGURATION_LOG_LEVEL_DEBUG, HYBRID_CLOUD_ENVIRONMENT_CONFIGURATION_LOG_LEVEL_ERROR, HYBRID_CLOUD_ENVIRONMENT_CONFIGURATION_LOG_LEVEL_INFO, HYBRID_CLOUD_ENVIRONMENT_CONFIGURATION_LOG_LEVEL_WARN.
        /// </summary>
        [Input("logLevel")]
        public Input<string>? LogLevel { get; set; }

        /// <summary>
        /// The Kubernetes namespace where the Qdrant hybrid cloud components will be deployed.
        /// </summary>
        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        [Input("noProxyConfigs")]
        private InputList<string>? _noProxyConfigs;

        /// <summary>
        /// List of hosts that should not be proxied.
        /// </summary>
        public InputList<string> NoProxyConfigs
        {
            get => _noProxyConfigs ?? (_noProxyConfigs = new InputList<string>());
            set => _noProxyConfigs = value;
        }

        [Input("nodeSelectors")]
        private InputList<Inputs.AccountsHybridCloudEnvironmentConfigurationNodeSelectorGetArgs>? _nodeSelectors;

        /// <summary>
        /// Node selector labels for scheduling control plane components.
        /// </summary>
        public InputList<Inputs.AccountsHybridCloudEnvironmentConfigurationNodeSelectorGetArgs> NodeSelectors
        {
            get => _nodeSelectors ?? (_nodeSelectors = new InputList<Inputs.AccountsHybridCloudEnvironmentConfigurationNodeSelectorGetArgs>());
            set => _nodeSelectors = value;
        }

        /// <summary>
        /// Kubernetes secret name containing registry credentials.
        /// </summary>
        [Input("registrySecretName")]
        public Input<string>? RegistrySecretName { get; set; }

        /// <summary>
        /// Default snapshot storage class.
        /// </summary>
        [Input("snapshotStorageClass")]
        public Input<string>? SnapshotStorageClass { get; set; }

        [Input("tolerations")]
        private InputList<Inputs.AccountsHybridCloudEnvironmentConfigurationTolerationGetArgs>? _tolerations;

        /// <summary>
        /// Tolerations for scheduling control plane components.
        /// </summary>
        public InputList<Inputs.AccountsHybridCloudEnvironmentConfigurationTolerationGetArgs> Tolerations
        {
            get => _tolerations ?? (_tolerations = new InputList<Inputs.AccountsHybridCloudEnvironmentConfigurationTolerationGetArgs>());
            set => _tolerations = value;
        }

        /// <summary>
        /// Default volume snapshot storage class.
        /// </summary>
        [Input("volumeSnapshotStorageClass")]
        public Input<string>? VolumeSnapshotStorageClass { get; set; }

        public AccountsHybridCloudEnvironmentConfigurationGetArgs()
        {
        }
        public static new AccountsHybridCloudEnvironmentConfigurationGetArgs Empty => new AccountsHybridCloudEnvironmentConfigurationGetArgs();
    }
}
