// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsDatabaseApiKeyV2GlobalAccessRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access type for global access. Must be one of: GLOBAL_ACCESS_RULE_ACCESS_TYPE_MANAGE, GLOBAL_ACCESS_RULE_ACCESS_TYPE_READ_ONLY.
        /// </summary>
        [Input("accessType", required: true)]
        public Input<string> AccessType { get; set; } = null!;

        public AccountsDatabaseApiKeyV2GlobalAccessRuleArgs()
        {
        }
        public static new AccountsDatabaseApiKeyV2GlobalAccessRuleArgs Empty => new AccountsDatabaseApiKeyV2GlobalAccessRuleArgs();
    }
}
