// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiKeys")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyArgs>? _apiKeys;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyArgs> ApiKeys
        {
            get => _apiKeys ?? (_apiKeys = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyArgs>());
            set => _apiKeys = value;
        }

        [Input("enableTls")]
        public Input<bool>? EnableTls { get; set; }

        [Input("forceIncludeJwtRbac")]
        public Input<bool>? ForceIncludeJwtRbac { get; set; }

        [Input("jwtRbac")]
        public Input<bool>? JwtRbac { get; set; }

        [Input("readOnlyApiKeys")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyArgs>? _readOnlyApiKeys;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyArgs> ReadOnlyApiKeys
        {
            get => _readOnlyApiKeys ?? (_readOnlyApiKeys = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyArgs>());
            set => _readOnlyApiKeys = value;
        }

        public AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs()
        {
        }
        public static new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs Empty => new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs();
    }
}
