// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsClusterConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowedIpSourceRanges")]
        private InputList<string>? _allowedIpSourceRanges;

        /// <summary>
        /// List of allowed IP source ranges for this cluster. On Hybrid Cloud, this will configure the loadBalancerSourceRanges of a LoadBalancer Service.
        /// </summary>
        public InputList<string> AllowedIpSourceRanges
        {
            get => _allowedIpSourceRanges ?? (_allowedIpSourceRanges = new InputList<string>());
            set => _allowedIpSourceRanges = value;
        }

        [Input("annotations")]
        private InputList<Inputs.AccountsClusterConfigurationAnnotationArgs>? _annotations;

        /// <summary>
        /// List of annotations for this cluster in a hybrid cloud environment.
        /// </summary>
        public InputList<Inputs.AccountsClusterConfigurationAnnotationArgs> Annotations
        {
            get => _annotations ?? (_annotations = new InputList<Inputs.AccountsClusterConfigurationAnnotationArgs>());
            set => _annotations = value;
        }

        /// <summary>
        /// Configuration for cluster storage settings.
        /// </summary>
        [Input("clusterStorageConfiguration")]
        public Input<Inputs.AccountsClusterConfigurationClusterStorageConfigurationArgs>? ClusterStorageConfiguration { get; set; }

        /// <summary>
        /// Configuration for the Qdrant database engine, primarily for hybrid cloud setups.
        /// </summary>
        [Input("databaseConfiguration")]
        public Input<Inputs.AccountsClusterConfigurationDatabaseConfigurationArgs>? DatabaseConfiguration { get; set; }

        /// <summary>
        /// The GPU type that should be used for the database. Must be one of: CLUSTER_CONFIGURATION_GPU_TYPE_AMD, CLUSTER_CONFIGURATION_GPU_TYPE_NVIDIA.
        /// </summary>
        [Input("gpuType")]
        public Input<string>? GpuType { get; set; }

        /// <summary>
        /// Cluster Schema Timestamp when the cluster configuration was last updated field
        /// </summary>
        [Input("lastModifiedAt")]
        public Input<string>? LastModifiedAt { get; set; }

        /// <summary>
        /// Cluster Schema The node configuration options of a cluster field
        /// </summary>
        [Input("nodeConfiguration", required: true)]
        public Input<Inputs.AccountsClusterConfigurationNodeConfigurationArgs> NodeConfiguration { get; set; } = null!;

        [Input("nodeSelectors")]
        private InputList<Inputs.AccountsClusterConfigurationNodeSelectorArgs>? _nodeSelectors;

        /// <summary>
        /// The node selector for this cluster in a hybrid cloud environment.
        /// </summary>
        public InputList<Inputs.AccountsClusterConfigurationNodeSelectorArgs> NodeSelectors
        {
            get => _nodeSelectors ?? (_nodeSelectors = new InputList<Inputs.AccountsClusterConfigurationNodeSelectorArgs>());
            set => _nodeSelectors = value;
        }

        /// <summary>
        /// Cluster Schema The number of nodes in the cluster field
        /// </summary>
        [Input("numberOfNodes", required: true)]
        public Input<double> NumberOfNodes { get; set; } = null!;

        [Input("podLabels")]
        private InputList<Inputs.AccountsClusterConfigurationPodLabelArgs>? _podLabels;

        /// <summary>
        /// List of labels applied to the pods of this cluster in a hybrid cloud environment.
        /// </summary>
        public InputList<Inputs.AccountsClusterConfigurationPodLabelArgs> PodLabels
        {
            get => _podLabels ?? (_podLabels = new InputList<Inputs.AccountsClusterConfigurationPodLabelArgs>());
            set => _podLabels = value;
        }

        /// <summary>
        /// The automatic shard rebalancing strategy for the database. Must be one of: CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT_AND_SIZE, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_SIZE.
        /// </summary>
        [Input("rebalanceStrategy")]
        public Input<string>? RebalanceStrategy { get; set; }

        /// <summary>
        /// The percentage of CPU resources reserved for system components.
        /// </summary>
        [Input("reservedCpuPercentage")]
        public Input<double>? ReservedCpuPercentage { get; set; }

        /// <summary>
        /// The percentage of RAM resources reserved for system components.
        /// </summary>
        [Input("reservedMemoryPercentage")]
        public Input<double>? ReservedMemoryPercentage { get; set; }

        /// <summary>
        /// The restart policy for the database. Must be one of: CLUSTER_CONFIGURATION_RESTART_POLICY_AUTOMATIC, CLUSTER_CONFIGURATION_RESTART_POLICY_PARALLEL, CLUSTER_CONFIGURATION_RESTART_POLICY_ROLLING.
        /// </summary>
        [Input("restartPolicy")]
        public Input<string>? RestartPolicy { get; set; }

        [Input("serviceAnnotations")]
        private InputList<Inputs.AccountsClusterConfigurationServiceAnnotationArgs>? _serviceAnnotations;

        /// <summary>
        /// List of annotations applied to the service of this cluster in a hybrid cloud environment.
        /// </summary>
        public InputList<Inputs.AccountsClusterConfigurationServiceAnnotationArgs> ServiceAnnotations
        {
            get => _serviceAnnotations ?? (_serviceAnnotations = new InputList<Inputs.AccountsClusterConfigurationServiceAnnotationArgs>());
            set => _serviceAnnotations = value;
        }

        /// <summary>
        /// The type of service to use for this cluster in a hybrid cloud environment. Must be one of: CLUSTER_SERVICE_TYPE_CLUSTER_IP, CLUSTER_SERVICE_TYPE_LOAD_BALANCER, CLUSTER_SERVICE_TYPE_NODE_PORT.
        /// </summary>
        [Input("serviceType")]
        public Input<string>? ServiceType { get; set; }

        [Input("tolerations")]
        private InputList<Inputs.AccountsClusterConfigurationTolerationArgs>? _tolerations;

        /// <summary>
        /// List of tolerations for this cluster in a hybrid cloud environment.
        /// </summary>
        public InputList<Inputs.AccountsClusterConfigurationTolerationArgs> Tolerations
        {
            get => _tolerations ?? (_tolerations = new InputList<Inputs.AccountsClusterConfigurationTolerationArgs>());
            set => _tolerations = value;
        }

        [Input("topologySpreadConstraints")]
        private InputList<Inputs.AccountsClusterConfigurationTopologySpreadConstraintArgs>? _topologySpreadConstraints;

        /// <summary>
        /// List of topology spread constraints for this cluster in a hybrid cloud environment.
        /// </summary>
        public InputList<Inputs.AccountsClusterConfigurationTopologySpreadConstraintArgs> TopologySpreadConstraints
        {
            get => _topologySpreadConstraints ?? (_topologySpreadConstraints = new InputList<Inputs.AccountsClusterConfigurationTopologySpreadConstraintArgs>());
            set => _topologySpreadConstraints = value;
        }

        /// <summary>
        /// Cluster Schema Version of the Qdrant cluster field
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public AccountsClusterConfigurationArgs()
        {
        }
        public static new AccountsClusterConfigurationArgs Empty => new AccountsClusterConfigurationArgs();
    }
}
