// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsManualBackupClusterInfoArgs : global::Pulumi.ResourceArgs
    {
        [Input("cloudProviderId")]
        public Input<string>? CloudProviderId { get; set; }

        [Input("cloudProviderRegionId")]
        public Input<string>? CloudProviderRegionId { get; set; }

        [Input("configurations")]
        private InputList<Inputs.AccountsManualBackupClusterInfoConfigurationArgs>? _configurations;
        public InputList<Inputs.AccountsManualBackupClusterInfoConfigurationArgs> Configurations
        {
            get => _configurations ?? (_configurations = new InputList<Inputs.AccountsManualBackupClusterInfoConfigurationArgs>());
            set => _configurations = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("resourcesSummaries")]
        private InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryArgs>? _resourcesSummaries;
        public InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryArgs> ResourcesSummaries
        {
            get => _resourcesSummaries ?? (_resourcesSummaries = new InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryArgs>());
            set => _resourcesSummaries = value;
        }

        [Input("restorePackageId")]
        public Input<string>? RestorePackageId { get; set; }

        public AccountsManualBackupClusterInfoArgs()
        {
        }
        public static new AccountsManualBackupClusterInfoArgs Empty => new AccountsManualBackupClusterInfoArgs();
    }
}
