// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsHybridCloudEnvironmentStatusStorageClassGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowVolumeExpansion")]
        public Input<bool>? AllowVolumeExpansion { get; set; }

        [Input("default")]
        public Input<bool>? Default { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("parameters")]
        private InputMap<string>? _parameters;
        public InputMap<string> Parameters
        {
            get => _parameters ?? (_parameters = new InputMap<string>());
            set => _parameters = value;
        }

        [Input("provisioner")]
        public Input<string>? Provisioner { get; set; }

        [Input("reclaimPolicy")]
        public Input<string>? ReclaimPolicy { get; set; }

        public AccountsHybridCloudEnvironmentStatusStorageClassGetArgs()
        {
        }
        public static new AccountsHybridCloudEnvironmentStatusStorageClassGetArgs Empty => new AccountsHybridCloudEnvironmentStatusStorageClassGetArgs();
    }
}
