// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsClusterConfigurationDatabaseConfigurationCollectionArgs : global::Pulumi.ResourceArgs
    {
        [Input("replicationFactor")]
        public Input<double>? ReplicationFactor { get; set; }

        [Input("vectors")]
        public Input<Inputs.AccountsClusterConfigurationDatabaseConfigurationCollectionVectorsArgs>? Vectors { get; set; }

        [Input("writeConsistencyFactor")]
        public Input<double>? WriteConsistencyFactor { get; set; }

        public AccountsClusterConfigurationDatabaseConfigurationCollectionArgs()
        {
        }
        public static new AccountsClusterConfigurationDatabaseConfigurationCollectionArgs Empty => new AccountsClusterConfigurationDatabaseConfigurationCollectionArgs();
    }
}
