// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsHybridCloudEnvironmentStatusGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("capabilities")]
        private InputList<Inputs.AccountsHybridCloudEnvironmentStatusCapabilityGetArgs>? _capabilities;
        public InputList<Inputs.AccountsHybridCloudEnvironmentStatusCapabilityGetArgs> Capabilities
        {
            get => _capabilities ?? (_capabilities = new InputList<Inputs.AccountsHybridCloudEnvironmentStatusCapabilityGetArgs>());
            set => _capabilities = value;
        }

        [Input("clusterCreationReadiness")]
        public Input<string>? ClusterCreationReadiness { get; set; }

        [Input("componentStatuses")]
        private InputList<Inputs.AccountsHybridCloudEnvironmentStatusComponentStatusGetArgs>? _componentStatuses;
        public InputList<Inputs.AccountsHybridCloudEnvironmentStatusComponentStatusGetArgs> ComponentStatuses
        {
            get => _componentStatuses ?? (_componentStatuses = new InputList<Inputs.AccountsHybridCloudEnvironmentStatusComponentStatusGetArgs>());
            set => _componentStatuses = value;
        }

        [Input("kubernetesDistribution")]
        public Input<string>? KubernetesDistribution { get; set; }

        [Input("kubernetesVersion")]
        public Input<string>? KubernetesVersion { get; set; }

        [Input("lastModifiedAt")]
        public Input<string>? LastModifiedAt { get; set; }

        [Input("message")]
        public Input<string>? Message { get; set; }

        [Input("numberOfNodes")]
        public Input<double>? NumberOfNodes { get; set; }

        [Input("phase")]
        public Input<string>? Phase { get; set; }

        [Input("storageClasses")]
        private InputList<Inputs.AccountsHybridCloudEnvironmentStatusStorageClassGetArgs>? _storageClasses;
        public InputList<Inputs.AccountsHybridCloudEnvironmentStatusStorageClassGetArgs> StorageClasses
        {
            get => _storageClasses ?? (_storageClasses = new InputList<Inputs.AccountsHybridCloudEnvironmentStatusStorageClassGetArgs>());
            set => _storageClasses = value;
        }

        [Input("volumeSnapshotClasses")]
        private InputList<Inputs.AccountsHybridCloudEnvironmentStatusVolumeSnapshotClassGetArgs>? _volumeSnapshotClasses;
        public InputList<Inputs.AccountsHybridCloudEnvironmentStatusVolumeSnapshotClassGetArgs> VolumeSnapshotClasses
        {
            get => _volumeSnapshotClasses ?? (_volumeSnapshotClasses = new InputList<Inputs.AccountsHybridCloudEnvironmentStatusVolumeSnapshotClassGetArgs>());
            set => _volumeSnapshotClasses = value;
        }

        public AccountsHybridCloudEnvironmentStatusGetArgs()
        {
        }
        public static new AccountsHybridCloudEnvironmentStatusGetArgs Empty => new AccountsHybridCloudEnvironmentStatusGetArgs();
    }
}
