// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsManualBackupClusterInfoResourcesSummaryArgs : global::Pulumi.ResourceArgs
    {
        [Input("cpus")]
        private InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryCpusArgs>? _cpus;
        public InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryCpusArgs> Cpus
        {
            get => _cpus ?? (_cpus = new InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryCpusArgs>());
            set => _cpus = value;
        }

        [Input("disks")]
        private InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryDiskArgs>? _disks;
        public InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryDiskArgs> Disks
        {
            get => _disks ?? (_disks = new InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryDiskArgs>());
            set => _disks = value;
        }

        [Input("rams")]
        private InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryRamArgs>? _rams;
        public InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryRamArgs> Rams
        {
            get => _rams ?? (_rams = new InputList<Inputs.AccountsManualBackupClusterInfoResourcesSummaryRamArgs>());
            set => _rams = value;
        }

        public AccountsManualBackupClusterInfoResourcesSummaryArgs()
        {
        }
        public static new AccountsManualBackupClusterInfoResourcesSummaryArgs Empty => new AccountsManualBackupClusterInfoResourcesSummaryArgs();
    }
}
