// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsClusterConfigurationNodeConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cluster Schema The package identifier (specifying: CPU, Memory, and disk size) field
        /// </summary>
        [Input("packageId", required: true)]
        public Input<string> PackageId { get; set; } = null!;

        [Input("resourceConfigurations")]
        private InputList<Inputs.AccountsClusterConfigurationNodeConfigurationResourceConfigurationGetArgs>? _resourceConfigurations;

        /// <summary>
        /// The resource configuration of the package
        /// </summary>
        public InputList<Inputs.AccountsClusterConfigurationNodeConfigurationResourceConfigurationGetArgs> ResourceConfigurations
        {
            get => _resourceConfigurations ?? (_resourceConfigurations = new InputList<Inputs.AccountsClusterConfigurationNodeConfigurationResourceConfigurationGetArgs>());
            set => _resourceConfigurations = value;
        }

        public AccountsClusterConfigurationNodeConfigurationGetArgs()
        {
        }
        public static new AccountsClusterConfigurationNodeConfigurationGetArgs Empty => new AccountsClusterConfigurationNodeConfigurationGetArgs();
    }
}
