// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKeyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The key within the secret.
        /// </summary>
        [Input("secretKey", required: true)]
        public Input<string> SecretKey { get; set; } = null!;

        /// <summary>
        /// The name of the secret.
        /// </summary>
        [Input("secretName", required: true)]
        public Input<string> SecretName { get; set; } = null!;

        public AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKeyGetArgs()
        {
        }
        public static new AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKeyGetArgs Empty => new AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKeyGetArgs();
    }
}
