// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class ServerlessSpaceApiKeyCollectionAccessRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access type for the collection. Must be one of: COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_ONLY, COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_WRITE.
        /// </summary>
        [Input("accessType", required: true)]
        public Input<string> AccessType { get; set; } = null!;

        /// <summary>
        /// Name of the collection.
        /// </summary>
        [Input("collectionName", required: true)]
        public Input<string> CollectionName { get; set; } = null!;

        public ServerlessSpaceApiKeyCollectionAccessRuleArgs()
        {
        }
        public static new ServerlessSpaceApiKeyCollectionAccessRuleArgs Empty => new ServerlessSpaceApiKeyCollectionAccessRuleArgs();
    }
}
