// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Inputs
{

    public sealed class ServerlessBackupStatArgs : global::Pulumi.ResourceArgs
    {
        [Input("collectionCount")]
        public Input<double>? CollectionCount { get; set; }

        [Input("duration")]
        public Input<string>? Duration { get; set; }

        [Input("sizeBytes")]
        public Input<double>? SizeBytes { get; set; }

        [Input("totalPoints")]
        public Input<double>? TotalPoints { get; set; }

        public ServerlessBackupStatArgs()
        {
        }
        public static new ServerlessBackupStatArgs Empty => new ServerlessBackupStatArgs();
    }
}
