// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.qdrantcloud.inputs.ServerlessBackupTimeoutsArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServerlessBackupArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServerlessBackupArgs Empty = new ServerlessBackupArgs();

    /**
     * Serverless Backup Schema Account ID (defaults to the provider account ID) field
     * 
     */
    @Import(name="accountId")
    private @Nullable Output<String> accountId;

    /**
     * @return Serverless Backup Schema Account ID (defaults to the provider account ID) field
     * 
     */
    public Optional<Output<String>> accountId() {
        return Optional.ofNullable(this.accountId);
    }

    /**
     * Serverless Backup Schema Name of the collection to back up. If unset, the entire space is backed up field
     * 
     */
    @Import(name="collectionName")
    private @Nullable Output<String> collectionName;

    /**
     * @return Serverless Backup Schema Name of the collection to back up. If unset, the entire space is backed up field
     * 
     */
    public Optional<Output<String>> collectionName() {
        return Optional.ofNullable(this.collectionName);
    }

    /**
     * Serverless Backup Schema Retention period of the backup, as a Go duration string between &lt;span pulumi-lang-nodejs=&#34;`24h`&#34; pulumi-lang-dotnet=&#34;`24h`&#34; pulumi-lang-go=&#34;`24h`&#34; pulumi-lang-python=&#34;`24h`&#34; pulumi-lang-yaml=&#34;`24h`&#34; pulumi-lang-java=&#34;`24h`&#34; pulumi-lang-hcl=&#34;`24h`&#34;&gt;`24h`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`8760h`&#34; pulumi-lang-dotnet=&#34;`8760h`&#34; pulumi-lang-go=&#34;`8760h`&#34; pulumi-lang-python=&#34;`8760h`&#34; pulumi-lang-yaml=&#34;`8760h`&#34; pulumi-lang-java=&#34;`8760h`&#34; pulumi-lang-hcl=&#34;`8760h`&#34;&gt;`8760h`&lt;/span&gt;. If unset, the backup is retained indefinitely field
     * 
     */
    @Import(name="retentionPeriod")
    private @Nullable Output<String> retentionPeriod;

    /**
     * @return Serverless Backup Schema Retention period of the backup, as a Go duration string between &lt;span pulumi-lang-nodejs=&#34;`24h`&#34; pulumi-lang-dotnet=&#34;`24h`&#34; pulumi-lang-go=&#34;`24h`&#34; pulumi-lang-python=&#34;`24h`&#34; pulumi-lang-yaml=&#34;`24h`&#34; pulumi-lang-java=&#34;`24h`&#34; pulumi-lang-hcl=&#34;`24h`&#34;&gt;`24h`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`8760h`&#34; pulumi-lang-dotnet=&#34;`8760h`&#34; pulumi-lang-go=&#34;`8760h`&#34; pulumi-lang-python=&#34;`8760h`&#34; pulumi-lang-yaml=&#34;`8760h`&#34; pulumi-lang-java=&#34;`8760h`&#34; pulumi-lang-hcl=&#34;`8760h`&#34;&gt;`8760h`&lt;/span&gt;. If unset, the backup is retained indefinitely field
     * 
     */
    public Optional<Output<String>> retentionPeriod() {
        return Optional.ofNullable(this.retentionPeriod);
    }

    /**
     * Serverless Backup Schema ID of the serverless space to back up field
     * 
     */
    @Import(name="spaceId", required=true)
    private Output<String> spaceId;

    /**
     * @return Serverless Backup Schema ID of the serverless space to back up field
     * 
     */
    public Output<String> spaceId() {
        return this.spaceId;
    }

    @Import(name="timeouts")
    private @Nullable Output<ServerlessBackupTimeoutsArgs> timeouts;

    public Optional<Output<ServerlessBackupTimeoutsArgs>> timeouts() {
        return Optional.ofNullable(this.timeouts);
    }

    private ServerlessBackupArgs() {}

    private ServerlessBackupArgs(ServerlessBackupArgs $) {
        this.accountId = $.accountId;
        this.collectionName = $.collectionName;
        this.retentionPeriod = $.retentionPeriod;
        this.spaceId = $.spaceId;
        this.timeouts = $.timeouts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServerlessBackupArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServerlessBackupArgs $;

        public Builder() {
            $ = new ServerlessBackupArgs();
        }

        public Builder(ServerlessBackupArgs defaults) {
            $ = new ServerlessBackupArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId Serverless Backup Schema Account ID (defaults to the provider account ID) field
         * 
         * @return builder
         * 
         */
        public Builder accountId(@Nullable Output<String> accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param accountId Serverless Backup Schema Account ID (defaults to the provider account ID) field
         * 
         * @return builder
         * 
         */
        public Builder accountId(String accountId) {
            return accountId(Output.of(accountId));
        }

        /**
         * @param collectionName Serverless Backup Schema Name of the collection to back up. If unset, the entire space is backed up field
         * 
         * @return builder
         * 
         */
        public Builder collectionName(@Nullable Output<String> collectionName) {
            $.collectionName = collectionName;
            return this;
        }

        /**
         * @param collectionName Serverless Backup Schema Name of the collection to back up. If unset, the entire space is backed up field
         * 
         * @return builder
         * 
         */
        public Builder collectionName(String collectionName) {
            return collectionName(Output.of(collectionName));
        }

        /**
         * @param retentionPeriod Serverless Backup Schema Retention period of the backup, as a Go duration string between &lt;span pulumi-lang-nodejs=&#34;`24h`&#34; pulumi-lang-dotnet=&#34;`24h`&#34; pulumi-lang-go=&#34;`24h`&#34; pulumi-lang-python=&#34;`24h`&#34; pulumi-lang-yaml=&#34;`24h`&#34; pulumi-lang-java=&#34;`24h`&#34; pulumi-lang-hcl=&#34;`24h`&#34;&gt;`24h`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`8760h`&#34; pulumi-lang-dotnet=&#34;`8760h`&#34; pulumi-lang-go=&#34;`8760h`&#34; pulumi-lang-python=&#34;`8760h`&#34; pulumi-lang-yaml=&#34;`8760h`&#34; pulumi-lang-java=&#34;`8760h`&#34; pulumi-lang-hcl=&#34;`8760h`&#34;&gt;`8760h`&lt;/span&gt;. If unset, the backup is retained indefinitely field
         * 
         * @return builder
         * 
         */
        public Builder retentionPeriod(@Nullable Output<String> retentionPeriod) {
            $.retentionPeriod = retentionPeriod;
            return this;
        }

        /**
         * @param retentionPeriod Serverless Backup Schema Retention period of the backup, as a Go duration string between &lt;span pulumi-lang-nodejs=&#34;`24h`&#34; pulumi-lang-dotnet=&#34;`24h`&#34; pulumi-lang-go=&#34;`24h`&#34; pulumi-lang-python=&#34;`24h`&#34; pulumi-lang-yaml=&#34;`24h`&#34; pulumi-lang-java=&#34;`24h`&#34; pulumi-lang-hcl=&#34;`24h`&#34;&gt;`24h`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`8760h`&#34; pulumi-lang-dotnet=&#34;`8760h`&#34; pulumi-lang-go=&#34;`8760h`&#34; pulumi-lang-python=&#34;`8760h`&#34; pulumi-lang-yaml=&#34;`8760h`&#34; pulumi-lang-java=&#34;`8760h`&#34; pulumi-lang-hcl=&#34;`8760h`&#34;&gt;`8760h`&lt;/span&gt;. If unset, the backup is retained indefinitely field
         * 
         * @return builder
         * 
         */
        public Builder retentionPeriod(String retentionPeriod) {
            return retentionPeriod(Output.of(retentionPeriod));
        }

        /**
         * @param spaceId Serverless Backup Schema ID of the serverless space to back up field
         * 
         * @return builder
         * 
         */
        public Builder spaceId(Output<String> spaceId) {
            $.spaceId = spaceId;
            return this;
        }

        /**
         * @param spaceId Serverless Backup Schema ID of the serverless space to back up field
         * 
         * @return builder
         * 
         */
        public Builder spaceId(String spaceId) {
            return spaceId(Output.of(spaceId));
        }

        public Builder timeouts(@Nullable Output<ServerlessBackupTimeoutsArgs> timeouts) {
            $.timeouts = timeouts;
            return this;
        }

        public Builder timeouts(ServerlessBackupTimeoutsArgs timeouts) {
            return timeouts(Output.of(timeouts));
        }

        public ServerlessBackupArgs build() {
            if ($.spaceId == null) {
                throw new MissingRequiredPropertyException("ServerlessBackupArgs", "spaceId");
            }
            return $;
        }
    }

}
