// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKey {
    /**
     * @return The key within the secret.
     * 
     */
    private String secretKey;
    /**
     * @return The name of the secret.
     * 
     */
    private String secretName;

    private AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKey() {}
    /**
     * @return The key within the secret.
     * 
     */
    public String secretKey() {
        return this.secretKey;
    }
    /**
     * @return The name of the secret.
     * 
     */
    public String secretName() {
        return this.secretName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKey defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String secretKey;
        private String secretName;
        public Builder() {}
        public Builder(AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKey defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.secretKey = defaults.secretKey;
    	      this.secretName = defaults.secretName;
        }

        @CustomType.Setter
        public Builder secretKey(String secretKey) {
            if (secretKey == null) {
              throw new MissingRequiredPropertyException("AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKey", "secretKey");
            }
            this.secretKey = secretKey;
            return this;
        }
        @CustomType.Setter
        public Builder secretName(String secretName) {
            if (secretName == null) {
              throw new MissingRequiredPropertyException("AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKey", "secretName");
            }
            this.secretName = secretName;
            return this;
        }
        public AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKey build() {
            final var _resultValue = new AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKey();
            _resultValue.secretKey = secretKey;
            _resultValue.secretName = secretName;
            return _resultValue;
        }
    }
}
