// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.qdrantcloud.outputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKey;
import com.pulumi.qdrantcloud.outputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKey;
import java.lang.Boolean;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationService {
    private @Nullable List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKey> apiKeys;
    private @Nullable Boolean enableTls;
    private @Nullable Boolean forceIncludeJwtRbac;
    private @Nullable Boolean jwtRbac;
    private @Nullable List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKey> readOnlyApiKeys;

    private AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationService() {}
    public List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKey> apiKeys() {
        return this.apiKeys == null ? List.of() : this.apiKeys;
    }
    public Optional<Boolean> enableTls() {
        return Optional.ofNullable(this.enableTls);
    }
    public Optional<Boolean> forceIncludeJwtRbac() {
        return Optional.ofNullable(this.forceIncludeJwtRbac);
    }
    public Optional<Boolean> jwtRbac() {
        return Optional.ofNullable(this.jwtRbac);
    }
    public List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKey> readOnlyApiKeys() {
        return this.readOnlyApiKeys == null ? List.of() : this.readOnlyApiKeys;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationService defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKey> apiKeys;
        private @Nullable Boolean enableTls;
        private @Nullable Boolean forceIncludeJwtRbac;
        private @Nullable Boolean jwtRbac;
        private @Nullable List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKey> readOnlyApiKeys;
        public Builder() {}
        public Builder(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationService defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.apiKeys = defaults.apiKeys;
    	      this.enableTls = defaults.enableTls;
    	      this.forceIncludeJwtRbac = defaults.forceIncludeJwtRbac;
    	      this.jwtRbac = defaults.jwtRbac;
    	      this.readOnlyApiKeys = defaults.readOnlyApiKeys;
        }

        @CustomType.Setter
        public Builder apiKeys(@Nullable List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKey> apiKeys) {

            this.apiKeys = apiKeys;
            return this;
        }
        public Builder apiKeys(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKey... apiKeys) {
            return apiKeys(List.of(apiKeys));
        }
        @CustomType.Setter
        public Builder enableTls(@Nullable Boolean enableTls) {

            this.enableTls = enableTls;
            return this;
        }
        @CustomType.Setter
        public Builder forceIncludeJwtRbac(@Nullable Boolean forceIncludeJwtRbac) {

            this.forceIncludeJwtRbac = forceIncludeJwtRbac;
            return this;
        }
        @CustomType.Setter
        public Builder jwtRbac(@Nullable Boolean jwtRbac) {

            this.jwtRbac = jwtRbac;
            return this;
        }
        @CustomType.Setter
        public Builder readOnlyApiKeys(@Nullable List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKey> readOnlyApiKeys) {

            this.readOnlyApiKeys = readOnlyApiKeys;
            return this;
        }
        public Builder readOnlyApiKeys(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKey... readOnlyApiKeys) {
            return readOnlyApiKeys(List.of(readOnlyApiKeys));
        }
        public AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationService build() {
            final var _resultValue = new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationService();
            _resultValue.apiKeys = apiKeys;
            _resultValue.enableTls = enableTls;
            _resultValue.forceIncludeJwtRbac = forceIncludeJwtRbac;
            _resultValue.jwtRbac = jwtRbac;
            _resultValue.readOnlyApiKeys = readOnlyApiKeys;
            return _resultValue;
        }
    }
}
