// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class AccountsHybridCloudEnvironmentStatusStorageClass {
    private @Nullable Boolean allowVolumeExpansion;
    private @Nullable Boolean default_;
    private @Nullable String name;
    private @Nullable Map<String,String> parameters;
    private @Nullable String provisioner;
    private @Nullable String reclaimPolicy;

    private AccountsHybridCloudEnvironmentStatusStorageClass() {}
    public Optional<Boolean> allowVolumeExpansion() {
        return Optional.ofNullable(this.allowVolumeExpansion);
    }
    public Optional<Boolean> default_() {
        return Optional.ofNullable(this.default_);
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public Map<String,String> parameters() {
        return this.parameters == null ? Map.of() : this.parameters;
    }
    public Optional<String> provisioner() {
        return Optional.ofNullable(this.provisioner);
    }
    public Optional<String> reclaimPolicy() {
        return Optional.ofNullable(this.reclaimPolicy);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AccountsHybridCloudEnvironmentStatusStorageClass defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean allowVolumeExpansion;
        private @Nullable Boolean default_;
        private @Nullable String name;
        private @Nullable Map<String,String> parameters;
        private @Nullable String provisioner;
        private @Nullable String reclaimPolicy;
        public Builder() {}
        public Builder(AccountsHybridCloudEnvironmentStatusStorageClass defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.allowVolumeExpansion = defaults.allowVolumeExpansion;
    	      this.default_ = defaults.default_;
    	      this.name = defaults.name;
    	      this.parameters = defaults.parameters;
    	      this.provisioner = defaults.provisioner;
    	      this.reclaimPolicy = defaults.reclaimPolicy;
        }

        @CustomType.Setter
        public Builder allowVolumeExpansion(@Nullable Boolean allowVolumeExpansion) {

            this.allowVolumeExpansion = allowVolumeExpansion;
            return this;
        }
        @CustomType.Setter("default")
        public Builder default_(@Nullable Boolean default_) {

            this.default_ = default_;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder parameters(@Nullable Map<String,String> parameters) {

            this.parameters = parameters;
            return this;
        }
        @CustomType.Setter
        public Builder provisioner(@Nullable String provisioner) {

            this.provisioner = provisioner;
            return this;
        }
        @CustomType.Setter
        public Builder reclaimPolicy(@Nullable String reclaimPolicy) {

            this.reclaimPolicy = reclaimPolicy;
            return this;
        }
        public AccountsHybridCloudEnvironmentStatusStorageClass build() {
            final var _resultValue = new AccountsHybridCloudEnvironmentStatusStorageClass();
            _resultValue.allowVolumeExpansion = allowVolumeExpansion;
            _resultValue.default_ = default_;
            _resultValue.name = name;
            _resultValue.parameters = parameters;
            _resultValue.provisioner = provisioner;
            _resultValue.reclaimPolicy = reclaimPolicy;
            return _resultValue;
        }
    }
}
