// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class AccountsClusterConfigurationTopologySpreadConstraint {
    private Double maxSkew;
    private String topologyKey;
    /**
     * @return Action to take when the topology spread constraint cannot be satisfied. Must be one of: TOPOLOGY_SPREAD_CONSTRAINT_WHEN_UNSATISFIABLE_DO_NOT_SCHEDULE, TOPOLOGY_SPREAD_CONSTRAINT_WHEN_UNSATISFIABLE_SCHEDULE_ANYWAY.
     * 
     */
    private String whenUnsatisfiable;

    private AccountsClusterConfigurationTopologySpreadConstraint() {}
    public Double maxSkew() {
        return this.maxSkew;
    }
    public String topologyKey() {
        return this.topologyKey;
    }
    /**
     * @return Action to take when the topology spread constraint cannot be satisfied. Must be one of: TOPOLOGY_SPREAD_CONSTRAINT_WHEN_UNSATISFIABLE_DO_NOT_SCHEDULE, TOPOLOGY_SPREAD_CONSTRAINT_WHEN_UNSATISFIABLE_SCHEDULE_ANYWAY.
     * 
     */
    public String whenUnsatisfiable() {
        return this.whenUnsatisfiable;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AccountsClusterConfigurationTopologySpreadConstraint defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Double maxSkew;
        private String topologyKey;
        private String whenUnsatisfiable;
        public Builder() {}
        public Builder(AccountsClusterConfigurationTopologySpreadConstraint defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.maxSkew = defaults.maxSkew;
    	      this.topologyKey = defaults.topologyKey;
    	      this.whenUnsatisfiable = defaults.whenUnsatisfiable;
        }

        @CustomType.Setter
        public Builder maxSkew(Double maxSkew) {
            if (maxSkew == null) {
              throw new MissingRequiredPropertyException("AccountsClusterConfigurationTopologySpreadConstraint", "maxSkew");
            }
            this.maxSkew = maxSkew;
            return this;
        }
        @CustomType.Setter
        public Builder topologyKey(String topologyKey) {
            if (topologyKey == null) {
              throw new MissingRequiredPropertyException("AccountsClusterConfigurationTopologySpreadConstraint", "topologyKey");
            }
            this.topologyKey = topologyKey;
            return this;
        }
        @CustomType.Setter
        public Builder whenUnsatisfiable(String whenUnsatisfiable) {
            if (whenUnsatisfiable == null) {
              throw new MissingRequiredPropertyException("AccountsClusterConfigurationTopologySpreadConstraint", "whenUnsatisfiable");
            }
            this.whenUnsatisfiable = whenUnsatisfiable;
            return this;
        }
        public AccountsClusterConfigurationTopologySpreadConstraint build() {
            final var _resultValue = new AccountsClusterConfigurationTopologySpreadConstraint();
            _resultValue.maxSkew = maxSkew;
            _resultValue.topologyKey = topologyKey;
            _resultValue.whenUnsatisfiable = whenUnsatisfiable;
            return _resultValue;
        }
    }
}
