// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.qdrantcloud.outputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStorage {
    private @Nullable List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance> performances;

    private AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStorage() {}
    public List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance> performances() {
        return this.performances == null ? List.of() : this.performances;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStorage defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance> performances;
        public Builder() {}
        public Builder(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStorage defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.performances = defaults.performances;
        }

        @CustomType.Setter
        public Builder performances(@Nullable List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance> performances) {

            this.performances = performances;
            return this;
        }
        public Builder performances(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance... performances) {
            return performances(List.of(performances));
        }
        public AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStorage build() {
            final var _resultValue = new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStorage();
            _resultValue.performances = performances;
            return _resultValue;
        }
    }
}
