// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class AccountsHybridCloudEnvironmentStatusComponentStatus {
    private @Nullable String message;
    private @Nullable String name;
    private @Nullable String namespace;
    private @Nullable String phase;
    private @Nullable String version;

    private AccountsHybridCloudEnvironmentStatusComponentStatus() {}
    public Optional<String> message() {
        return Optional.ofNullable(this.message);
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public Optional<String> namespace() {
        return Optional.ofNullable(this.namespace);
    }
    public Optional<String> phase() {
        return Optional.ofNullable(this.phase);
    }
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AccountsHybridCloudEnvironmentStatusComponentStatus defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String message;
        private @Nullable String name;
        private @Nullable String namespace;
        private @Nullable String phase;
        private @Nullable String version;
        public Builder() {}
        public Builder(AccountsHybridCloudEnvironmentStatusComponentStatus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.message = defaults.message;
    	      this.name = defaults.name;
    	      this.namespace = defaults.namespace;
    	      this.phase = defaults.phase;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder message(@Nullable String message) {

            this.message = message;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder namespace(@Nullable String namespace) {

            this.namespace = namespace;
            return this;
        }
        @CustomType.Setter
        public Builder phase(@Nullable String phase) {

            this.phase = phase;
            return this;
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        public AccountsHybridCloudEnvironmentStatusComponentStatus build() {
            final var _resultValue = new AccountsHybridCloudEnvironmentStatusComponentStatus();
            _resultValue.message = message;
            _resultValue.name = name;
            _resultValue.namespace = namespace;
            _resultValue.phase = phase;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
