// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.qdrantcloud.outputs.GetAccountsDatabaseApiKeysV2KeyCollectionAccessRule;
import com.pulumi.qdrantcloud.outputs.GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAccountsDatabaseApiKeysV2Key {
    private @Nullable String accountId;
    private @Nullable String clusterId;
    private @Nullable List<GetAccountsDatabaseApiKeysV2KeyCollectionAccessRule> collectionAccessRules;
    private @Nullable String createdAt;
    private @Nullable String createdByEmail;
    private @Nullable String expiresAt;
    private @Nullable List<GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule> globalAccessRules;
    private @Nullable String id;
    private @Nullable String key;
    private @Nullable String name;
    private @Nullable String postfix;

    private GetAccountsDatabaseApiKeysV2Key() {}
    public Optional<String> accountId() {
        return Optional.ofNullable(this.accountId);
    }
    public Optional<String> clusterId() {
        return Optional.ofNullable(this.clusterId);
    }
    public List<GetAccountsDatabaseApiKeysV2KeyCollectionAccessRule> collectionAccessRules() {
        return this.collectionAccessRules == null ? List.of() : this.collectionAccessRules;
    }
    public Optional<String> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }
    public Optional<String> createdByEmail() {
        return Optional.ofNullable(this.createdByEmail);
    }
    public Optional<String> expiresAt() {
        return Optional.ofNullable(this.expiresAt);
    }
    public List<GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule> globalAccessRules() {
        return this.globalAccessRules == null ? List.of() : this.globalAccessRules;
    }
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    public Optional<String> key() {
        return Optional.ofNullable(this.key);
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public Optional<String> postfix() {
        return Optional.ofNullable(this.postfix);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountsDatabaseApiKeysV2Key defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String accountId;
        private @Nullable String clusterId;
        private @Nullable List<GetAccountsDatabaseApiKeysV2KeyCollectionAccessRule> collectionAccessRules;
        private @Nullable String createdAt;
        private @Nullable String createdByEmail;
        private @Nullable String expiresAt;
        private @Nullable List<GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule> globalAccessRules;
        private @Nullable String id;
        private @Nullable String key;
        private @Nullable String name;
        private @Nullable String postfix;
        public Builder() {}
        public Builder(GetAccountsDatabaseApiKeysV2Key defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.clusterId = defaults.clusterId;
    	      this.collectionAccessRules = defaults.collectionAccessRules;
    	      this.createdAt = defaults.createdAt;
    	      this.createdByEmail = defaults.createdByEmail;
    	      this.expiresAt = defaults.expiresAt;
    	      this.globalAccessRules = defaults.globalAccessRules;
    	      this.id = defaults.id;
    	      this.key = defaults.key;
    	      this.name = defaults.name;
    	      this.postfix = defaults.postfix;
        }

        @CustomType.Setter
        public Builder accountId(@Nullable String accountId) {

            this.accountId = accountId;
            return this;
        }
        @CustomType.Setter
        public Builder clusterId(@Nullable String clusterId) {

            this.clusterId = clusterId;
            return this;
        }
        @CustomType.Setter
        public Builder collectionAccessRules(@Nullable List<GetAccountsDatabaseApiKeysV2KeyCollectionAccessRule> collectionAccessRules) {

            this.collectionAccessRules = collectionAccessRules;
            return this;
        }
        public Builder collectionAccessRules(GetAccountsDatabaseApiKeysV2KeyCollectionAccessRule... collectionAccessRules) {
            return collectionAccessRules(List.of(collectionAccessRules));
        }
        @CustomType.Setter
        public Builder createdAt(@Nullable String createdAt) {

            this.createdAt = createdAt;
            return this;
        }
        @CustomType.Setter
        public Builder createdByEmail(@Nullable String createdByEmail) {

            this.createdByEmail = createdByEmail;
            return this;
        }
        @CustomType.Setter
        public Builder expiresAt(@Nullable String expiresAt) {

            this.expiresAt = expiresAt;
            return this;
        }
        @CustomType.Setter
        public Builder globalAccessRules(@Nullable List<GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule> globalAccessRules) {

            this.globalAccessRules = globalAccessRules;
            return this;
        }
        public Builder globalAccessRules(GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule... globalAccessRules) {
            return globalAccessRules(List.of(globalAccessRules));
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder key(@Nullable String key) {

            this.key = key;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder postfix(@Nullable String postfix) {

            this.postfix = postfix;
            return this;
        }
        public GetAccountsDatabaseApiKeysV2Key build() {
            final var _resultValue = new GetAccountsDatabaseApiKeysV2Key();
            _resultValue.accountId = accountId;
            _resultValue.clusterId = clusterId;
            _resultValue.collectionAccessRules = collectionAccessRules;
            _resultValue.createdAt = createdAt;
            _resultValue.createdByEmail = createdByEmail;
            _resultValue.expiresAt = expiresAt;
            _resultValue.globalAccessRules = globalAccessRules;
            _resultValue.id = id;
            _resultValue.key = key;
            _resultValue.name = name;
            _resultValue.postfix = postfix;
            return _resultValue;
        }
    }
}
