// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAccountsClustersClusterStatusCapabilityBackup {
    private @Nullable String reason;
    private @Nullable String status;

    private GetAccountsClustersClusterStatusCapabilityBackup() {}
    public Optional<String> reason() {
        return Optional.ofNullable(this.reason);
    }
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountsClustersClusterStatusCapabilityBackup defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String reason;
        private @Nullable String status;
        public Builder() {}
        public Builder(GetAccountsClustersClusterStatusCapabilityBackup defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.reason = defaults.reason;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder reason(@Nullable String reason) {

            this.reason = reason;
            return this;
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        public GetAccountsClustersClusterStatusCapabilityBackup build() {
            final var _resultValue = new GetAccountsClustersClusterStatusCapabilityBackup();
            _resultValue.reason = reason;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
