// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.qdrantcloud.outputs.GetAccountsBackupSchedulesSchedule;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetAccountsBackupSchedulesResult {
    private String accountId;
    private String clusterId;
    private String id;
    private List<GetAccountsBackupSchedulesSchedule> schedules;

    private GetAccountsBackupSchedulesResult() {}
    public String accountId() {
        return this.accountId;
    }
    public String clusterId() {
        return this.clusterId;
    }
    public String id() {
        return this.id;
    }
    public List<GetAccountsBackupSchedulesSchedule> schedules() {
        return this.schedules;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountsBackupSchedulesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accountId;
        private String clusterId;
        private String id;
        private List<GetAccountsBackupSchedulesSchedule> schedules;
        public Builder() {}
        public Builder(GetAccountsBackupSchedulesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.clusterId = defaults.clusterId;
    	      this.id = defaults.id;
    	      this.schedules = defaults.schedules;
        }

        @CustomType.Setter
        public Builder accountId(String accountId) {
            if (accountId == null) {
              throw new MissingRequiredPropertyException("GetAccountsBackupSchedulesResult", "accountId");
            }
            this.accountId = accountId;
            return this;
        }
        @CustomType.Setter
        public Builder clusterId(String clusterId) {
            if (clusterId == null) {
              throw new MissingRequiredPropertyException("GetAccountsBackupSchedulesResult", "clusterId");
            }
            this.clusterId = clusterId;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetAccountsBackupSchedulesResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder schedules(List<GetAccountsBackupSchedulesSchedule> schedules) {
            if (schedules == null) {
              throw new MissingRequiredPropertyException("GetAccountsBackupSchedulesResult", "schedules");
            }
            this.schedules = schedules;
            return this;
        }
        public Builder schedules(GetAccountsBackupSchedulesSchedule... schedules) {
            return schedules(List.of(schedules));
        }
        public GetAccountsBackupSchedulesResult build() {
            final var _resultValue = new GetAccountsBackupSchedulesResult();
            _resultValue.accountId = accountId;
            _resultValue.clusterId = clusterId;
            _resultValue.id = id;
            _resultValue.schedules = schedules;
            return _resultValue;
        }
    }
}
