// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAccountsClustersClusterConfigurationDatabaseConfigurationAuditLogging {
    private @Nullable Boolean enabled;
    private @Nullable Double maxLogFiles;
    private @Nullable String rotation;
    private @Nullable Boolean trustForwardedHeaders;

    private GetAccountsClustersClusterConfigurationDatabaseConfigurationAuditLogging() {}
    public Optional<Boolean> enabled() {
        return Optional.ofNullable(this.enabled);
    }
    public Optional<Double> maxLogFiles() {
        return Optional.ofNullable(this.maxLogFiles);
    }
    public Optional<String> rotation() {
        return Optional.ofNullable(this.rotation);
    }
    public Optional<Boolean> trustForwardedHeaders() {
        return Optional.ofNullable(this.trustForwardedHeaders);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountsClustersClusterConfigurationDatabaseConfigurationAuditLogging defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean enabled;
        private @Nullable Double maxLogFiles;
        private @Nullable String rotation;
        private @Nullable Boolean trustForwardedHeaders;
        public Builder() {}
        public Builder(GetAccountsClustersClusterConfigurationDatabaseConfigurationAuditLogging defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.maxLogFiles = defaults.maxLogFiles;
    	      this.rotation = defaults.rotation;
    	      this.trustForwardedHeaders = defaults.trustForwardedHeaders;
        }

        @CustomType.Setter
        public Builder enabled(@Nullable Boolean enabled) {

            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder maxLogFiles(@Nullable Double maxLogFiles) {

            this.maxLogFiles = maxLogFiles;
            return this;
        }
        @CustomType.Setter
        public Builder rotation(@Nullable String rotation) {

            this.rotation = rotation;
            return this;
        }
        @CustomType.Setter
        public Builder trustForwardedHeaders(@Nullable Boolean trustForwardedHeaders) {

            this.trustForwardedHeaders = trustForwardedHeaders;
            return this;
        }
        public GetAccountsClustersClusterConfigurationDatabaseConfigurationAuditLogging build() {
            final var _resultValue = new GetAccountsClustersClusterConfigurationDatabaseConfigurationAuditLogging();
            _resultValue.enabled = enabled;
            _resultValue.maxLogFiles = maxLogFiles;
            _resultValue.rotation = rotation;
            _resultValue.trustForwardedHeaders = trustForwardedHeaders;
            return _resultValue;
        }
    }
}
