// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterStatusCapability;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterStatusResource;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterStatusScalabilityInfo;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAccountsClusterStatus {
    private @Nullable List<GetAccountsClusterStatusCapability> capabilities;
    private @Nullable Double nodesUp;
    private @Nullable String phase;
    private @Nullable String reason;
    private @Nullable List<GetAccountsClusterStatusResource> resources;
    private @Nullable String restartedAt;
    private @Nullable List<GetAccountsClusterStatusScalabilityInfo> scalabilityInfos;
    private @Nullable String version;

    private GetAccountsClusterStatus() {}
    public List<GetAccountsClusterStatusCapability> capabilities() {
        return this.capabilities == null ? List.of() : this.capabilities;
    }
    public Optional<Double> nodesUp() {
        return Optional.ofNullable(this.nodesUp);
    }
    public Optional<String> phase() {
        return Optional.ofNullable(this.phase);
    }
    public Optional<String> reason() {
        return Optional.ofNullable(this.reason);
    }
    public List<GetAccountsClusterStatusResource> resources() {
        return this.resources == null ? List.of() : this.resources;
    }
    public Optional<String> restartedAt() {
        return Optional.ofNullable(this.restartedAt);
    }
    public List<GetAccountsClusterStatusScalabilityInfo> scalabilityInfos() {
        return this.scalabilityInfos == null ? List.of() : this.scalabilityInfos;
    }
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountsClusterStatus defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<GetAccountsClusterStatusCapability> capabilities;
        private @Nullable Double nodesUp;
        private @Nullable String phase;
        private @Nullable String reason;
        private @Nullable List<GetAccountsClusterStatusResource> resources;
        private @Nullable String restartedAt;
        private @Nullable List<GetAccountsClusterStatusScalabilityInfo> scalabilityInfos;
        private @Nullable String version;
        public Builder() {}
        public Builder(GetAccountsClusterStatus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.capabilities = defaults.capabilities;
    	      this.nodesUp = defaults.nodesUp;
    	      this.phase = defaults.phase;
    	      this.reason = defaults.reason;
    	      this.resources = defaults.resources;
    	      this.restartedAt = defaults.restartedAt;
    	      this.scalabilityInfos = defaults.scalabilityInfos;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder capabilities(@Nullable List<GetAccountsClusterStatusCapability> capabilities) {

            this.capabilities = capabilities;
            return this;
        }
        public Builder capabilities(GetAccountsClusterStatusCapability... capabilities) {
            return capabilities(List.of(capabilities));
        }
        @CustomType.Setter
        public Builder nodesUp(@Nullable Double nodesUp) {

            this.nodesUp = nodesUp;
            return this;
        }
        @CustomType.Setter
        public Builder phase(@Nullable String phase) {

            this.phase = phase;
            return this;
        }
        @CustomType.Setter
        public Builder reason(@Nullable String reason) {

            this.reason = reason;
            return this;
        }
        @CustomType.Setter
        public Builder resources(@Nullable List<GetAccountsClusterStatusResource> resources) {

            this.resources = resources;
            return this;
        }
        public Builder resources(GetAccountsClusterStatusResource... resources) {
            return resources(List.of(resources));
        }
        @CustomType.Setter
        public Builder restartedAt(@Nullable String restartedAt) {

            this.restartedAt = restartedAt;
            return this;
        }
        @CustomType.Setter
        public Builder scalabilityInfos(@Nullable List<GetAccountsClusterStatusScalabilityInfo> scalabilityInfos) {

            this.scalabilityInfos = scalabilityInfos;
            return this;
        }
        public Builder scalabilityInfos(GetAccountsClusterStatusScalabilityInfo... scalabilityInfos) {
            return scalabilityInfos(List.of(scalabilityInfos));
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        public GetAccountsClusterStatus build() {
            final var _resultValue = new GetAccountsClusterStatus();
            _resultValue.capabilities = capabilities;
            _resultValue.nodesUp = nodesUp;
            _resultValue.phase = phase;
            _resultValue.reason = reason;
            _resultValue.resources = resources;
            _resultValue.restartedAt = restartedAt;
            _resultValue.scalabilityInfos = scalabilityInfos;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
