// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterConfigurationAnnotation;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterConfigurationClusterStorageConfiguration;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterConfigurationDatabaseConfiguration;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterConfigurationNodeConfiguration;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterConfigurationNodeSelector;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterConfigurationPodLabel;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterConfigurationServiceAnnotation;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterConfigurationToleration;
import com.pulumi.qdrantcloud.outputs.GetAccountsClusterConfigurationTopologySpreadConstraint;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAccountsClusterConfiguration {
    private @Nullable List<String> allowedIpSourceRanges;
    private @Nullable List<GetAccountsClusterConfigurationAnnotation> annotations;
    private @Nullable List<GetAccountsClusterConfigurationClusterStorageConfiguration> clusterStorageConfigurations;
    private @Nullable List<GetAccountsClusterConfigurationDatabaseConfiguration> databaseConfigurations;
    private @Nullable String gpuType;
    private @Nullable String lastModifiedAt;
    private @Nullable List<GetAccountsClusterConfigurationNodeConfiguration> nodeConfigurations;
    private @Nullable List<GetAccountsClusterConfigurationNodeSelector> nodeSelectors;
    private @Nullable Double numberOfNodes;
    private @Nullable List<GetAccountsClusterConfigurationPodLabel> podLabels;
    private @Nullable String rebalanceStrategy;
    private @Nullable Double reservedCpuPercentage;
    private @Nullable Double reservedMemoryPercentage;
    private @Nullable String restartPolicy;
    private @Nullable List<GetAccountsClusterConfigurationServiceAnnotation> serviceAnnotations;
    private @Nullable String serviceType;
    private @Nullable List<GetAccountsClusterConfigurationToleration> tolerations;
    private @Nullable List<GetAccountsClusterConfigurationTopologySpreadConstraint> topologySpreadConstraints;
    private @Nullable String version;

    private GetAccountsClusterConfiguration() {}
    public List<String> allowedIpSourceRanges() {
        return this.allowedIpSourceRanges == null ? List.of() : this.allowedIpSourceRanges;
    }
    public List<GetAccountsClusterConfigurationAnnotation> annotations() {
        return this.annotations == null ? List.of() : this.annotations;
    }
    public List<GetAccountsClusterConfigurationClusterStorageConfiguration> clusterStorageConfigurations() {
        return this.clusterStorageConfigurations == null ? List.of() : this.clusterStorageConfigurations;
    }
    public List<GetAccountsClusterConfigurationDatabaseConfiguration> databaseConfigurations() {
        return this.databaseConfigurations == null ? List.of() : this.databaseConfigurations;
    }
    public Optional<String> gpuType() {
        return Optional.ofNullable(this.gpuType);
    }
    public Optional<String> lastModifiedAt() {
        return Optional.ofNullable(this.lastModifiedAt);
    }
    public List<GetAccountsClusterConfigurationNodeConfiguration> nodeConfigurations() {
        return this.nodeConfigurations == null ? List.of() : this.nodeConfigurations;
    }
    public List<GetAccountsClusterConfigurationNodeSelector> nodeSelectors() {
        return this.nodeSelectors == null ? List.of() : this.nodeSelectors;
    }
    public Optional<Double> numberOfNodes() {
        return Optional.ofNullable(this.numberOfNodes);
    }
    public List<GetAccountsClusterConfigurationPodLabel> podLabels() {
        return this.podLabels == null ? List.of() : this.podLabels;
    }
    public Optional<String> rebalanceStrategy() {
        return Optional.ofNullable(this.rebalanceStrategy);
    }
    public Optional<Double> reservedCpuPercentage() {
        return Optional.ofNullable(this.reservedCpuPercentage);
    }
    public Optional<Double> reservedMemoryPercentage() {
        return Optional.ofNullable(this.reservedMemoryPercentage);
    }
    public Optional<String> restartPolicy() {
        return Optional.ofNullable(this.restartPolicy);
    }
    public List<GetAccountsClusterConfigurationServiceAnnotation> serviceAnnotations() {
        return this.serviceAnnotations == null ? List.of() : this.serviceAnnotations;
    }
    public Optional<String> serviceType() {
        return Optional.ofNullable(this.serviceType);
    }
    public List<GetAccountsClusterConfigurationToleration> tolerations() {
        return this.tolerations == null ? List.of() : this.tolerations;
    }
    public List<GetAccountsClusterConfigurationTopologySpreadConstraint> topologySpreadConstraints() {
        return this.topologySpreadConstraints == null ? List.of() : this.topologySpreadConstraints;
    }
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountsClusterConfiguration defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> allowedIpSourceRanges;
        private @Nullable List<GetAccountsClusterConfigurationAnnotation> annotations;
        private @Nullable List<GetAccountsClusterConfigurationClusterStorageConfiguration> clusterStorageConfigurations;
        private @Nullable List<GetAccountsClusterConfigurationDatabaseConfiguration> databaseConfigurations;
        private @Nullable String gpuType;
        private @Nullable String lastModifiedAt;
        private @Nullable List<GetAccountsClusterConfigurationNodeConfiguration> nodeConfigurations;
        private @Nullable List<GetAccountsClusterConfigurationNodeSelector> nodeSelectors;
        private @Nullable Double numberOfNodes;
        private @Nullable List<GetAccountsClusterConfigurationPodLabel> podLabels;
        private @Nullable String rebalanceStrategy;
        private @Nullable Double reservedCpuPercentage;
        private @Nullable Double reservedMemoryPercentage;
        private @Nullable String restartPolicy;
        private @Nullable List<GetAccountsClusterConfigurationServiceAnnotation> serviceAnnotations;
        private @Nullable String serviceType;
        private @Nullable List<GetAccountsClusterConfigurationToleration> tolerations;
        private @Nullable List<GetAccountsClusterConfigurationTopologySpreadConstraint> topologySpreadConstraints;
        private @Nullable String version;
        public Builder() {}
        public Builder(GetAccountsClusterConfiguration defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.allowedIpSourceRanges = defaults.allowedIpSourceRanges;
    	      this.annotations = defaults.annotations;
    	      this.clusterStorageConfigurations = defaults.clusterStorageConfigurations;
    	      this.databaseConfigurations = defaults.databaseConfigurations;
    	      this.gpuType = defaults.gpuType;
    	      this.lastModifiedAt = defaults.lastModifiedAt;
    	      this.nodeConfigurations = defaults.nodeConfigurations;
    	      this.nodeSelectors = defaults.nodeSelectors;
    	      this.numberOfNodes = defaults.numberOfNodes;
    	      this.podLabels = defaults.podLabels;
    	      this.rebalanceStrategy = defaults.rebalanceStrategy;
    	      this.reservedCpuPercentage = defaults.reservedCpuPercentage;
    	      this.reservedMemoryPercentage = defaults.reservedMemoryPercentage;
    	      this.restartPolicy = defaults.restartPolicy;
    	      this.serviceAnnotations = defaults.serviceAnnotations;
    	      this.serviceType = defaults.serviceType;
    	      this.tolerations = defaults.tolerations;
    	      this.topologySpreadConstraints = defaults.topologySpreadConstraints;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder allowedIpSourceRanges(@Nullable List<String> allowedIpSourceRanges) {

            this.allowedIpSourceRanges = allowedIpSourceRanges;
            return this;
        }
        public Builder allowedIpSourceRanges(String... allowedIpSourceRanges) {
            return allowedIpSourceRanges(List.of(allowedIpSourceRanges));
        }
        @CustomType.Setter
        public Builder annotations(@Nullable List<GetAccountsClusterConfigurationAnnotation> annotations) {

            this.annotations = annotations;
            return this;
        }
        public Builder annotations(GetAccountsClusterConfigurationAnnotation... annotations) {
            return annotations(List.of(annotations));
        }
        @CustomType.Setter
        public Builder clusterStorageConfigurations(@Nullable List<GetAccountsClusterConfigurationClusterStorageConfiguration> clusterStorageConfigurations) {

            this.clusterStorageConfigurations = clusterStorageConfigurations;
            return this;
        }
        public Builder clusterStorageConfigurations(GetAccountsClusterConfigurationClusterStorageConfiguration... clusterStorageConfigurations) {
            return clusterStorageConfigurations(List.of(clusterStorageConfigurations));
        }
        @CustomType.Setter
        public Builder databaseConfigurations(@Nullable List<GetAccountsClusterConfigurationDatabaseConfiguration> databaseConfigurations) {

            this.databaseConfigurations = databaseConfigurations;
            return this;
        }
        public Builder databaseConfigurations(GetAccountsClusterConfigurationDatabaseConfiguration... databaseConfigurations) {
            return databaseConfigurations(List.of(databaseConfigurations));
        }
        @CustomType.Setter
        public Builder gpuType(@Nullable String gpuType) {

            this.gpuType = gpuType;
            return this;
        }
        @CustomType.Setter
        public Builder lastModifiedAt(@Nullable String lastModifiedAt) {

            this.lastModifiedAt = lastModifiedAt;
            return this;
        }
        @CustomType.Setter
        public Builder nodeConfigurations(@Nullable List<GetAccountsClusterConfigurationNodeConfiguration> nodeConfigurations) {

            this.nodeConfigurations = nodeConfigurations;
            return this;
        }
        public Builder nodeConfigurations(GetAccountsClusterConfigurationNodeConfiguration... nodeConfigurations) {
            return nodeConfigurations(List.of(nodeConfigurations));
        }
        @CustomType.Setter
        public Builder nodeSelectors(@Nullable List<GetAccountsClusterConfigurationNodeSelector> nodeSelectors) {

            this.nodeSelectors = nodeSelectors;
            return this;
        }
        public Builder nodeSelectors(GetAccountsClusterConfigurationNodeSelector... nodeSelectors) {
            return nodeSelectors(List.of(nodeSelectors));
        }
        @CustomType.Setter
        public Builder numberOfNodes(@Nullable Double numberOfNodes) {

            this.numberOfNodes = numberOfNodes;
            return this;
        }
        @CustomType.Setter
        public Builder podLabels(@Nullable List<GetAccountsClusterConfigurationPodLabel> podLabels) {

            this.podLabels = podLabels;
            return this;
        }
        public Builder podLabels(GetAccountsClusterConfigurationPodLabel... podLabels) {
            return podLabels(List.of(podLabels));
        }
        @CustomType.Setter
        public Builder rebalanceStrategy(@Nullable String rebalanceStrategy) {

            this.rebalanceStrategy = rebalanceStrategy;
            return this;
        }
        @CustomType.Setter
        public Builder reservedCpuPercentage(@Nullable Double reservedCpuPercentage) {

            this.reservedCpuPercentage = reservedCpuPercentage;
            return this;
        }
        @CustomType.Setter
        public Builder reservedMemoryPercentage(@Nullable Double reservedMemoryPercentage) {

            this.reservedMemoryPercentage = reservedMemoryPercentage;
            return this;
        }
        @CustomType.Setter
        public Builder restartPolicy(@Nullable String restartPolicy) {

            this.restartPolicy = restartPolicy;
            return this;
        }
        @CustomType.Setter
        public Builder serviceAnnotations(@Nullable List<GetAccountsClusterConfigurationServiceAnnotation> serviceAnnotations) {

            this.serviceAnnotations = serviceAnnotations;
            return this;
        }
        public Builder serviceAnnotations(GetAccountsClusterConfigurationServiceAnnotation... serviceAnnotations) {
            return serviceAnnotations(List.of(serviceAnnotations));
        }
        @CustomType.Setter
        public Builder serviceType(@Nullable String serviceType) {

            this.serviceType = serviceType;
            return this;
        }
        @CustomType.Setter
        public Builder tolerations(@Nullable List<GetAccountsClusterConfigurationToleration> tolerations) {

            this.tolerations = tolerations;
            return this;
        }
        public Builder tolerations(GetAccountsClusterConfigurationToleration... tolerations) {
            return tolerations(List.of(tolerations));
        }
        @CustomType.Setter
        public Builder topologySpreadConstraints(@Nullable List<GetAccountsClusterConfigurationTopologySpreadConstraint> topologySpreadConstraints) {

            this.topologySpreadConstraints = topologySpreadConstraints;
            return this;
        }
        public Builder topologySpreadConstraints(GetAccountsClusterConfigurationTopologySpreadConstraint... topologySpreadConstraints) {
            return topologySpreadConstraints(List.of(topologySpreadConstraints));
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        public GetAccountsClusterConfiguration build() {
            final var _resultValue = new GetAccountsClusterConfiguration();
            _resultValue.allowedIpSourceRanges = allowedIpSourceRanges;
            _resultValue.annotations = annotations;
            _resultValue.clusterStorageConfigurations = clusterStorageConfigurations;
            _resultValue.databaseConfigurations = databaseConfigurations;
            _resultValue.gpuType = gpuType;
            _resultValue.lastModifiedAt = lastModifiedAt;
            _resultValue.nodeConfigurations = nodeConfigurations;
            _resultValue.nodeSelectors = nodeSelectors;
            _resultValue.numberOfNodes = numberOfNodes;
            _resultValue.podLabels = podLabels;
            _resultValue.rebalanceStrategy = rebalanceStrategy;
            _resultValue.reservedCpuPercentage = reservedCpuPercentage;
            _resultValue.reservedMemoryPercentage = reservedMemoryPercentage;
            _resultValue.restartPolicy = restartPolicy;
            _resultValue.serviceAnnotations = serviceAnnotations;
            _resultValue.serviceType = serviceType;
            _resultValue.tolerations = tolerations;
            _resultValue.topologySpreadConstraints = topologySpreadConstraints;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
