// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.qdrantcloud.outputs.GetAccountsClustersClusterConfiguration;
import com.pulumi.qdrantcloud.outputs.GetAccountsClustersClusterLabel;
import com.pulumi.qdrantcloud.outputs.GetAccountsClustersClusterStatus;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAccountsClustersCluster {
    private @Nullable String accountId;
    private @Nullable String cloudProvider;
    private @Nullable String cloudRegion;
    private @Nullable List<GetAccountsClustersClusterConfiguration> configurations;
    private @Nullable String createdAt;
    private @Nullable Boolean deleteBackupsOnDestroy;
    private @Nullable String id;
    private @Nullable List<GetAccountsClustersClusterLabel> labels;
    private @Nullable String markedForDeletionAt;
    private @Nullable String name;
    private @Nullable String privateRegionId;
    private @Nullable List<GetAccountsClustersClusterStatus> statuses;
    private @Nullable String url;

    private GetAccountsClustersCluster() {}
    public Optional<String> accountId() {
        return Optional.ofNullable(this.accountId);
    }
    public Optional<String> cloudProvider() {
        return Optional.ofNullable(this.cloudProvider);
    }
    public Optional<String> cloudRegion() {
        return Optional.ofNullable(this.cloudRegion);
    }
    public List<GetAccountsClustersClusterConfiguration> configurations() {
        return this.configurations == null ? List.of() : this.configurations;
    }
    public Optional<String> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }
    public Optional<Boolean> deleteBackupsOnDestroy() {
        return Optional.ofNullable(this.deleteBackupsOnDestroy);
    }
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    public List<GetAccountsClustersClusterLabel> labels() {
        return this.labels == null ? List.of() : this.labels;
    }
    public Optional<String> markedForDeletionAt() {
        return Optional.ofNullable(this.markedForDeletionAt);
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public Optional<String> privateRegionId() {
        return Optional.ofNullable(this.privateRegionId);
    }
    public List<GetAccountsClustersClusterStatus> statuses() {
        return this.statuses == null ? List.of() : this.statuses;
    }
    public Optional<String> url() {
        return Optional.ofNullable(this.url);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountsClustersCluster defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String accountId;
        private @Nullable String cloudProvider;
        private @Nullable String cloudRegion;
        private @Nullable List<GetAccountsClustersClusterConfiguration> configurations;
        private @Nullable String createdAt;
        private @Nullable Boolean deleteBackupsOnDestroy;
        private @Nullable String id;
        private @Nullable List<GetAccountsClustersClusterLabel> labels;
        private @Nullable String markedForDeletionAt;
        private @Nullable String name;
        private @Nullable String privateRegionId;
        private @Nullable List<GetAccountsClustersClusterStatus> statuses;
        private @Nullable String url;
        public Builder() {}
        public Builder(GetAccountsClustersCluster defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.cloudProvider = defaults.cloudProvider;
    	      this.cloudRegion = defaults.cloudRegion;
    	      this.configurations = defaults.configurations;
    	      this.createdAt = defaults.createdAt;
    	      this.deleteBackupsOnDestroy = defaults.deleteBackupsOnDestroy;
    	      this.id = defaults.id;
    	      this.labels = defaults.labels;
    	      this.markedForDeletionAt = defaults.markedForDeletionAt;
    	      this.name = defaults.name;
    	      this.privateRegionId = defaults.privateRegionId;
    	      this.statuses = defaults.statuses;
    	      this.url = defaults.url;
        }

        @CustomType.Setter
        public Builder accountId(@Nullable String accountId) {

            this.accountId = accountId;
            return this;
        }
        @CustomType.Setter
        public Builder cloudProvider(@Nullable String cloudProvider) {

            this.cloudProvider = cloudProvider;
            return this;
        }
        @CustomType.Setter
        public Builder cloudRegion(@Nullable String cloudRegion) {

            this.cloudRegion = cloudRegion;
            return this;
        }
        @CustomType.Setter
        public Builder configurations(@Nullable List<GetAccountsClustersClusterConfiguration> configurations) {

            this.configurations = configurations;
            return this;
        }
        public Builder configurations(GetAccountsClustersClusterConfiguration... configurations) {
            return configurations(List.of(configurations));
        }
        @CustomType.Setter
        public Builder createdAt(@Nullable String createdAt) {

            this.createdAt = createdAt;
            return this;
        }
        @CustomType.Setter
        public Builder deleteBackupsOnDestroy(@Nullable Boolean deleteBackupsOnDestroy) {

            this.deleteBackupsOnDestroy = deleteBackupsOnDestroy;
            return this;
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder labels(@Nullable List<GetAccountsClustersClusterLabel> labels) {

            this.labels = labels;
            return this;
        }
        public Builder labels(GetAccountsClustersClusterLabel... labels) {
            return labels(List.of(labels));
        }
        @CustomType.Setter
        public Builder markedForDeletionAt(@Nullable String markedForDeletionAt) {

            this.markedForDeletionAt = markedForDeletionAt;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder privateRegionId(@Nullable String privateRegionId) {

            this.privateRegionId = privateRegionId;
            return this;
        }
        @CustomType.Setter
        public Builder statuses(@Nullable List<GetAccountsClustersClusterStatus> statuses) {

            this.statuses = statuses;
            return this;
        }
        public Builder statuses(GetAccountsClustersClusterStatus... statuses) {
            return statuses(List.of(statuses));
        }
        @CustomType.Setter
        public Builder url(@Nullable String url) {

            this.url = url;
            return this;
        }
        public GetAccountsClustersCluster build() {
            final var _resultValue = new GetAccountsClustersCluster();
            _resultValue.accountId = accountId;
            _resultValue.cloudProvider = cloudProvider;
            _resultValue.cloudRegion = cloudRegion;
            _resultValue.configurations = configurations;
            _resultValue.createdAt = createdAt;
            _resultValue.deleteBackupsOnDestroy = deleteBackupsOnDestroy;
            _resultValue.id = id;
            _resultValue.labels = labels;
            _resultValue.markedForDeletionAt = markedForDeletionAt;
            _resultValue.name = name;
            _resultValue.privateRegionId = privateRegionId;
            _resultValue.statuses = statuses;
            _resultValue.url = url;
            return _resultValue;
        }
    }
}
