// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.qdrantcloud.outputs.GetAccountsAuthKeysKey;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetAccountsAuthKeysResult {
    private String accountId;
    private String id;
    private List<GetAccountsAuthKeysKey> keys;

    private GetAccountsAuthKeysResult() {}
    public String accountId() {
        return this.accountId;
    }
    public String id() {
        return this.id;
    }
    public List<GetAccountsAuthKeysKey> keys() {
        return this.keys;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountsAuthKeysResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accountId;
        private String id;
        private List<GetAccountsAuthKeysKey> keys;
        public Builder() {}
        public Builder(GetAccountsAuthKeysResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.id = defaults.id;
    	      this.keys = defaults.keys;
        }

        @CustomType.Setter
        public Builder accountId(String accountId) {
            if (accountId == null) {
              throw new MissingRequiredPropertyException("GetAccountsAuthKeysResult", "accountId");
            }
            this.accountId = accountId;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetAccountsAuthKeysResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder keys(List<GetAccountsAuthKeysKey> keys) {
            if (keys == null) {
              throw new MissingRequiredPropertyException("GetAccountsAuthKeysResult", "keys");
            }
            this.keys = keys;
            return this;
        }
        public Builder keys(GetAccountsAuthKeysKey... keys) {
            return keys(List.of(keys));
        }
        public GetAccountsAuthKeysResult build() {
            final var _resultValue = new GetAccountsAuthKeysResult();
            _resultValue.accountId = accountId;
            _resultValue.id = id;
            _resultValue.keys = keys;
            return _resultValue;
        }
    }
}
