// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.qdrantcloud.outputs.GetAccountsClustersCluster;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetAccountsClustersResult {
    private String accountId;
    private List<GetAccountsClustersCluster> clusters;
    private String id;

    private GetAccountsClustersResult() {}
    public String accountId() {
        return this.accountId;
    }
    public List<GetAccountsClustersCluster> clusters() {
        return this.clusters;
    }
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountsClustersResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accountId;
        private List<GetAccountsClustersCluster> clusters;
        private String id;
        public Builder() {}
        public Builder(GetAccountsClustersResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.clusters = defaults.clusters;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder accountId(String accountId) {
            if (accountId == null) {
              throw new MissingRequiredPropertyException("GetAccountsClustersResult", "accountId");
            }
            this.accountId = accountId;
            return this;
        }
        @CustomType.Setter
        public Builder clusters(List<GetAccountsClustersCluster> clusters) {
            if (clusters == null) {
              throw new MissingRequiredPropertyException("GetAccountsClustersResult", "clusters");
            }
            this.clusters = clusters;
            return this;
        }
        public Builder clusters(GetAccountsClustersCluster... clusters) {
            return clusters(List.of(clusters));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetAccountsClustersResult", "id");
            }
            this.id = id;
            return this;
        }
        public GetAccountsClustersResult build() {
            final var _resultValue = new GetAccountsClustersResult();
            _resultValue.accountId = accountId;
            _resultValue.clusters = clusters;
            _resultValue.id = id;
            return _resultValue;
        }
    }
}
