// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule {
    private @Nullable String accessType;

    private GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule() {}
    public Optional<String> accessType() {
        return Optional.ofNullable(this.accessType);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String accessType;
        public Builder() {}
        public Builder(GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessType = defaults.accessType;
        }

        @CustomType.Setter
        public Builder accessType(@Nullable String accessType) {

            this.accessType = accessType;
            return this;
        }
        public GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule build() {
            final var _resultValue = new GetAccountsDatabaseApiKeysV2KeyGlobalAccessRule();
            _resultValue.accessType = accessType;
            return _resultValue;
        }
    }
}
