// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.qdrantcloud.outputs.GetBookingPackagesPackage;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetBookingPackagesResult {
    private String cloudProvider;
    private String cloudRegion;
    private String id;
    private List<GetBookingPackagesPackage> packages;

    private GetBookingPackagesResult() {}
    public String cloudProvider() {
        return this.cloudProvider;
    }
    public String cloudRegion() {
        return this.cloudRegion;
    }
    public String id() {
        return this.id;
    }
    public List<GetBookingPackagesPackage> packages() {
        return this.packages;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetBookingPackagesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String cloudProvider;
        private String cloudRegion;
        private String id;
        private List<GetBookingPackagesPackage> packages;
        public Builder() {}
        public Builder(GetBookingPackagesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cloudProvider = defaults.cloudProvider;
    	      this.cloudRegion = defaults.cloudRegion;
    	      this.id = defaults.id;
    	      this.packages = defaults.packages;
        }

        @CustomType.Setter
        public Builder cloudProvider(String cloudProvider) {
            if (cloudProvider == null) {
              throw new MissingRequiredPropertyException("GetBookingPackagesResult", "cloudProvider");
            }
            this.cloudProvider = cloudProvider;
            return this;
        }
        @CustomType.Setter
        public Builder cloudRegion(String cloudRegion) {
            if (cloudRegion == null) {
              throw new MissingRequiredPropertyException("GetBookingPackagesResult", "cloudRegion");
            }
            this.cloudRegion = cloudRegion;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetBookingPackagesResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder packages(List<GetBookingPackagesPackage> packages) {
            if (packages == null) {
              throw new MissingRequiredPropertyException("GetBookingPackagesResult", "packages");
            }
            this.packages = packages;
            return this;
        }
        public Builder packages(GetBookingPackagesPackage... packages) {
            return packages(List.of(packages));
        }
        public GetBookingPackagesResult build() {
            final var _resultValue = new GetBookingPackagesResult();
            _resultValue.cloudProvider = cloudProvider;
            _resultValue.cloudRegion = cloudRegion;
            _resultValue.id = id;
            _resultValue.packages = packages;
            return _resultValue;
        }
    }
}
