// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.qdrantcloud.outputs.GetServerlessBackupsBackup;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetServerlessBackupsResult {
    private String accountId;
    private @Nullable String backupScheduleId;
    private List<GetServerlessBackupsBackup> backups;
    private @Nullable String collectionName;
    private String id;
    private @Nullable String spaceId;

    private GetServerlessBackupsResult() {}
    public String accountId() {
        return this.accountId;
    }
    public Optional<String> backupScheduleId() {
        return Optional.ofNullable(this.backupScheduleId);
    }
    public List<GetServerlessBackupsBackup> backups() {
        return this.backups;
    }
    public Optional<String> collectionName() {
        return Optional.ofNullable(this.collectionName);
    }
    public String id() {
        return this.id;
    }
    public Optional<String> spaceId() {
        return Optional.ofNullable(this.spaceId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetServerlessBackupsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accountId;
        private @Nullable String backupScheduleId;
        private List<GetServerlessBackupsBackup> backups;
        private @Nullable String collectionName;
        private String id;
        private @Nullable String spaceId;
        public Builder() {}
        public Builder(GetServerlessBackupsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.backupScheduleId = defaults.backupScheduleId;
    	      this.backups = defaults.backups;
    	      this.collectionName = defaults.collectionName;
    	      this.id = defaults.id;
    	      this.spaceId = defaults.spaceId;
        }

        @CustomType.Setter
        public Builder accountId(String accountId) {
            if (accountId == null) {
              throw new MissingRequiredPropertyException("GetServerlessBackupsResult", "accountId");
            }
            this.accountId = accountId;
            return this;
        }
        @CustomType.Setter
        public Builder backupScheduleId(@Nullable String backupScheduleId) {

            this.backupScheduleId = backupScheduleId;
            return this;
        }
        @CustomType.Setter
        public Builder backups(List<GetServerlessBackupsBackup> backups) {
            if (backups == null) {
              throw new MissingRequiredPropertyException("GetServerlessBackupsResult", "backups");
            }
            this.backups = backups;
            return this;
        }
        public Builder backups(GetServerlessBackupsBackup... backups) {
            return backups(List.of(backups));
        }
        @CustomType.Setter
        public Builder collectionName(@Nullable String collectionName) {

            this.collectionName = collectionName;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetServerlessBackupsResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder spaceId(@Nullable String spaceId) {

            this.spaceId = spaceId;
            return this;
        }
        public GetServerlessBackupsResult build() {
            final var _resultValue = new GetServerlessBackupsResult();
            _resultValue.accountId = accountId;
            _resultValue.backupScheduleId = backupScheduleId;
            _resultValue.backups = backups;
            _resultValue.collectionName = collectionName;
            _resultValue.id = id;
            _resultValue.spaceId = spaceId;
            return _resultValue;
        }
    }
}
