// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ServerlessSpaceApiKeyGlobalAccessRule {
    /**
     * @return Access type for the entire space. Must be one of: GLOBAL_ACCESS_RULE_ACCESS_TYPE_MANAGE, GLOBAL_ACCESS_RULE_ACCESS_TYPE_METRICS_READ_ONLY, GLOBAL_ACCESS_RULE_ACCESS_TYPE_READ_ONLY.
     * 
     */
    private String accessType;

    private ServerlessSpaceApiKeyGlobalAccessRule() {}
    /**
     * @return Access type for the entire space. Must be one of: GLOBAL_ACCESS_RULE_ACCESS_TYPE_MANAGE, GLOBAL_ACCESS_RULE_ACCESS_TYPE_METRICS_READ_ONLY, GLOBAL_ACCESS_RULE_ACCESS_TYPE_READ_ONLY.
     * 
     */
    public String accessType() {
        return this.accessType;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ServerlessSpaceApiKeyGlobalAccessRule defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accessType;
        public Builder() {}
        public Builder(ServerlessSpaceApiKeyGlobalAccessRule defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessType = defaults.accessType;
        }

        @CustomType.Setter
        public Builder accessType(String accessType) {
            if (accessType == null) {
              throw new MissingRequiredPropertyException("ServerlessSpaceApiKeyGlobalAccessRule", "accessType");
            }
            this.accessType = accessType;
            return this;
        }
        public ServerlessSpaceApiKeyGlobalAccessRule build() {
            final var _resultValue = new ServerlessSpaceApiKeyGlobalAccessRule();
            _resultValue.accessType = accessType;
            return _resultValue;
        }
    }
}
