// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ServerlessSpaceConfigurationSearcherSettings {
    /**
     * @return Idle timeout after which idle search workers may be scaled down, as a Go duration string (between &#34;1m&#34; and &#34;15m&#34;, defaults to &#34;5m&#34;).
     * 
     */
    private @Nullable String idleTimeout;
    /**
     * @return Maximum number of search workers per collection in this space (defaults to 2).
     * 
     */
    private @Nullable Double maxWorkers;
    /**
     * @return Platform-enforced maximum number of search workers per collection (0 means unlimited).
     * 
     */
    private @Nullable Double platformMaxWorkers;

    private ServerlessSpaceConfigurationSearcherSettings() {}
    /**
     * @return Idle timeout after which idle search workers may be scaled down, as a Go duration string (between &#34;1m&#34; and &#34;15m&#34;, defaults to &#34;5m&#34;).
     * 
     */
    public Optional<String> idleTimeout() {
        return Optional.ofNullable(this.idleTimeout);
    }
    /**
     * @return Maximum number of search workers per collection in this space (defaults to 2).
     * 
     */
    public Optional<Double> maxWorkers() {
        return Optional.ofNullable(this.maxWorkers);
    }
    /**
     * @return Platform-enforced maximum number of search workers per collection (0 means unlimited).
     * 
     */
    public Optional<Double> platformMaxWorkers() {
        return Optional.ofNullable(this.platformMaxWorkers);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ServerlessSpaceConfigurationSearcherSettings defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String idleTimeout;
        private @Nullable Double maxWorkers;
        private @Nullable Double platformMaxWorkers;
        public Builder() {}
        public Builder(ServerlessSpaceConfigurationSearcherSettings defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.idleTimeout = defaults.idleTimeout;
    	      this.maxWorkers = defaults.maxWorkers;
    	      this.platformMaxWorkers = defaults.platformMaxWorkers;
        }

        @CustomType.Setter
        public Builder idleTimeout(@Nullable String idleTimeout) {

            this.idleTimeout = idleTimeout;
            return this;
        }
        @CustomType.Setter
        public Builder maxWorkers(@Nullable Double maxWorkers) {

            this.maxWorkers = maxWorkers;
            return this;
        }
        @CustomType.Setter
        public Builder platformMaxWorkers(@Nullable Double platformMaxWorkers) {

            this.platformMaxWorkers = platformMaxWorkers;
            return this;
        }
        public ServerlessSpaceConfigurationSearcherSettings build() {
            final var _resultValue = new ServerlessSpaceConfigurationSearcherSettings();
            _resultValue.idleTimeout = idleTimeout;
            _resultValue.maxWorkers = maxWorkers;
            _resultValue.platformMaxWorkers = platformMaxWorkers;
            return _resultValue;
        }
    }
}
