// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AccountsManualBackupClusterInfoResourcesSummaryDiskArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountsManualBackupClusterInfoResourcesSummaryDiskArgs Empty = new AccountsManualBackupClusterInfoResourcesSummaryDiskArgs();

    @Import(name="amount")
    private @Nullable Output<Double> amount;

    public Optional<Output<Double>> amount() {
        return Optional.ofNullable(this.amount);
    }

    @Import(name="unit")
    private @Nullable Output<String> unit;

    public Optional<Output<String>> unit() {
        return Optional.ofNullable(this.unit);
    }

    private AccountsManualBackupClusterInfoResourcesSummaryDiskArgs() {}

    private AccountsManualBackupClusterInfoResourcesSummaryDiskArgs(AccountsManualBackupClusterInfoResourcesSummaryDiskArgs $) {
        this.amount = $.amount;
        this.unit = $.unit;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountsManualBackupClusterInfoResourcesSummaryDiskArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountsManualBackupClusterInfoResourcesSummaryDiskArgs $;

        public Builder() {
            $ = new AccountsManualBackupClusterInfoResourcesSummaryDiskArgs();
        }

        public Builder(AccountsManualBackupClusterInfoResourcesSummaryDiskArgs defaults) {
            $ = new AccountsManualBackupClusterInfoResourcesSummaryDiskArgs(Objects.requireNonNull(defaults));
        }

        public Builder amount(@Nullable Output<Double> amount) {
            $.amount = amount;
            return this;
        }

        public Builder amount(Double amount) {
            return amount(Output.of(amount));
        }

        public Builder unit(@Nullable Output<String> unit) {
            $.unit = unit;
            return this;
        }

        public Builder unit(String unit) {
            return unit(Output.of(unit));
        }

        public AccountsManualBackupClusterInfoResourcesSummaryDiskArgs build() {
            return $;
        }
    }

}
