// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Double;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs Empty = new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs();

    @Import(name="asyncScorer")
    private @Nullable Output<Boolean> asyncScorer;

    public Optional<Output<Boolean>> asyncScorer() {
        return Optional.ofNullable(this.asyncScorer);
    }

    @Import(name="optimizerCpuBudget")
    private @Nullable Output<Double> optimizerCpuBudget;

    public Optional<Output<Double>> optimizerCpuBudget() {
        return Optional.ofNullable(this.optimizerCpuBudget);
    }

    private AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs() {}

    private AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs $) {
        this.asyncScorer = $.asyncScorer;
        this.optimizerCpuBudget = $.optimizerCpuBudget;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs $;

        public Builder() {
            $ = new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs();
        }

        public Builder(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs defaults) {
            $ = new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs(Objects.requireNonNull(defaults));
        }

        public Builder asyncScorer(@Nullable Output<Boolean> asyncScorer) {
            $.asyncScorer = asyncScorer;
            return this;
        }

        public Builder asyncScorer(Boolean asyncScorer) {
            return asyncScorer(Output.of(asyncScorer));
        }

        public Builder optimizerCpuBudget(@Nullable Output<Double> optimizerCpuBudget) {
            $.optimizerCpuBudget = optimizerCpuBudget;
            return this;
        }

        public Builder optimizerCpuBudget(Double optimizerCpuBudget) {
            return optimizerCpuBudget(Output.of(optimizerCpuBudget));
        }

        public AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformanceArgs build() {
            return $;
        }
    }

}
