// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.qdrantcloud.inputs.AccountsClusterConfigurationAnnotationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsClusterConfigurationClusterStorageConfigurationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsClusterConfigurationDatabaseConfigurationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsClusterConfigurationNodeConfigurationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsClusterConfigurationNodeSelectorArgs;
import com.pulumi.qdrantcloud.inputs.AccountsClusterConfigurationPodLabelArgs;
import com.pulumi.qdrantcloud.inputs.AccountsClusterConfigurationServiceAnnotationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsClusterConfigurationTolerationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsClusterConfigurationTopologySpreadConstraintArgs;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AccountsClusterConfigurationArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountsClusterConfigurationArgs Empty = new AccountsClusterConfigurationArgs();

    /**
     * List of allowed IP source ranges for this cluster. On Hybrid Cloud, this will configure the loadBalancerSourceRanges of a LoadBalancer Service.
     * 
     */
    @Import(name="allowedIpSourceRanges")
    private @Nullable Output<List<String>> allowedIpSourceRanges;

    /**
     * @return List of allowed IP source ranges for this cluster. On Hybrid Cloud, this will configure the loadBalancerSourceRanges of a LoadBalancer Service.
     * 
     */
    public Optional<Output<List<String>>> allowedIpSourceRanges() {
        return Optional.ofNullable(this.allowedIpSourceRanges);
    }

    /**
     * List of annotations for this cluster in a hybrid cloud environment.
     * 
     */
    @Import(name="annotations")
    private @Nullable Output<List<AccountsClusterConfigurationAnnotationArgs>> annotations;

    /**
     * @return List of annotations for this cluster in a hybrid cloud environment.
     * 
     */
    public Optional<Output<List<AccountsClusterConfigurationAnnotationArgs>>> annotations() {
        return Optional.ofNullable(this.annotations);
    }

    /**
     * Configuration for cluster storage settings.
     * 
     */
    @Import(name="clusterStorageConfiguration")
    private @Nullable Output<AccountsClusterConfigurationClusterStorageConfigurationArgs> clusterStorageConfiguration;

    /**
     * @return Configuration for cluster storage settings.
     * 
     */
    public Optional<Output<AccountsClusterConfigurationClusterStorageConfigurationArgs>> clusterStorageConfiguration() {
        return Optional.ofNullable(this.clusterStorageConfiguration);
    }

    /**
     * Configuration for the Qdrant database engine, primarily for hybrid cloud setups.
     * 
     */
    @Import(name="databaseConfiguration")
    private @Nullable Output<AccountsClusterConfigurationDatabaseConfigurationArgs> databaseConfiguration;

    /**
     * @return Configuration for the Qdrant database engine, primarily for hybrid cloud setups.
     * 
     */
    public Optional<Output<AccountsClusterConfigurationDatabaseConfigurationArgs>> databaseConfiguration() {
        return Optional.ofNullable(this.databaseConfiguration);
    }

    /**
     * The GPU type that should be used for the database. Must be one of: CLUSTER_CONFIGURATION_GPU_TYPE_AMD, CLUSTER_CONFIGURATION_GPU_TYPE_NVIDIA.
     * 
     */
    @Import(name="gpuType")
    private @Nullable Output<String> gpuType;

    /**
     * @return The GPU type that should be used for the database. Must be one of: CLUSTER_CONFIGURATION_GPU_TYPE_AMD, CLUSTER_CONFIGURATION_GPU_TYPE_NVIDIA.
     * 
     */
    public Optional<Output<String>> gpuType() {
        return Optional.ofNullable(this.gpuType);
    }

    /**
     * Cluster Schema Timestamp when the cluster configuration was last updated field
     * 
     */
    @Import(name="lastModifiedAt")
    private @Nullable Output<String> lastModifiedAt;

    /**
     * @return Cluster Schema Timestamp when the cluster configuration was last updated field
     * 
     */
    public Optional<Output<String>> lastModifiedAt() {
        return Optional.ofNullable(this.lastModifiedAt);
    }

    /**
     * Cluster Schema The node configuration options of a cluster field
     * 
     */
    @Import(name="nodeConfiguration", required=true)
    private Output<AccountsClusterConfigurationNodeConfigurationArgs> nodeConfiguration;

    /**
     * @return Cluster Schema The node configuration options of a cluster field
     * 
     */
    public Output<AccountsClusterConfigurationNodeConfigurationArgs> nodeConfiguration() {
        return this.nodeConfiguration;
    }

    /**
     * The node selector for this cluster in a hybrid cloud environment.
     * 
     */
    @Import(name="nodeSelectors")
    private @Nullable Output<List<AccountsClusterConfigurationNodeSelectorArgs>> nodeSelectors;

    /**
     * @return The node selector for this cluster in a hybrid cloud environment.
     * 
     */
    public Optional<Output<List<AccountsClusterConfigurationNodeSelectorArgs>>> nodeSelectors() {
        return Optional.ofNullable(this.nodeSelectors);
    }

    /**
     * Cluster Schema The number of nodes in the cluster field
     * 
     */
    @Import(name="numberOfNodes", required=true)
    private Output<Double> numberOfNodes;

    /**
     * @return Cluster Schema The number of nodes in the cluster field
     * 
     */
    public Output<Double> numberOfNodes() {
        return this.numberOfNodes;
    }

    /**
     * List of labels applied to the pods of this cluster in a hybrid cloud environment.
     * 
     */
    @Import(name="podLabels")
    private @Nullable Output<List<AccountsClusterConfigurationPodLabelArgs>> podLabels;

    /**
     * @return List of labels applied to the pods of this cluster in a hybrid cloud environment.
     * 
     */
    public Optional<Output<List<AccountsClusterConfigurationPodLabelArgs>>> podLabels() {
        return Optional.ofNullable(this.podLabels);
    }

    /**
     * The automatic shard rebalancing strategy for the database. Must be one of: CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT_AND_SIZE, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_SIZE.
     * 
     */
    @Import(name="rebalanceStrategy")
    private @Nullable Output<String> rebalanceStrategy;

    /**
     * @return The automatic shard rebalancing strategy for the database. Must be one of: CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT_AND_SIZE, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_SIZE.
     * 
     */
    public Optional<Output<String>> rebalanceStrategy() {
        return Optional.ofNullable(this.rebalanceStrategy);
    }

    /**
     * The percentage of CPU resources reserved for system components.
     * 
     */
    @Import(name="reservedCpuPercentage")
    private @Nullable Output<Double> reservedCpuPercentage;

    /**
     * @return The percentage of CPU resources reserved for system components.
     * 
     */
    public Optional<Output<Double>> reservedCpuPercentage() {
        return Optional.ofNullable(this.reservedCpuPercentage);
    }

    /**
     * The percentage of RAM resources reserved for system components.
     * 
     */
    @Import(name="reservedMemoryPercentage")
    private @Nullable Output<Double> reservedMemoryPercentage;

    /**
     * @return The percentage of RAM resources reserved for system components.
     * 
     */
    public Optional<Output<Double>> reservedMemoryPercentage() {
        return Optional.ofNullable(this.reservedMemoryPercentage);
    }

    /**
     * The restart policy for the database. Must be one of: CLUSTER_CONFIGURATION_RESTART_POLICY_AUTOMATIC, CLUSTER_CONFIGURATION_RESTART_POLICY_PARALLEL, CLUSTER_CONFIGURATION_RESTART_POLICY_ROLLING.
     * 
     */
    @Import(name="restartPolicy")
    private @Nullable Output<String> restartPolicy;

    /**
     * @return The restart policy for the database. Must be one of: CLUSTER_CONFIGURATION_RESTART_POLICY_AUTOMATIC, CLUSTER_CONFIGURATION_RESTART_POLICY_PARALLEL, CLUSTER_CONFIGURATION_RESTART_POLICY_ROLLING.
     * 
     */
    public Optional<Output<String>> restartPolicy() {
        return Optional.ofNullable(this.restartPolicy);
    }

    /**
     * List of annotations applied to the service of this cluster in a hybrid cloud environment.
     * 
     */
    @Import(name="serviceAnnotations")
    private @Nullable Output<List<AccountsClusterConfigurationServiceAnnotationArgs>> serviceAnnotations;

    /**
     * @return List of annotations applied to the service of this cluster in a hybrid cloud environment.
     * 
     */
    public Optional<Output<List<AccountsClusterConfigurationServiceAnnotationArgs>>> serviceAnnotations() {
        return Optional.ofNullable(this.serviceAnnotations);
    }

    /**
     * The type of service to use for this cluster in a hybrid cloud environment. Must be one of: CLUSTER_SERVICE_TYPE_CLUSTER_IP, CLUSTER_SERVICE_TYPE_LOAD_BALANCER, CLUSTER_SERVICE_TYPE_NODE_PORT.
     * 
     */
    @Import(name="serviceType")
    private @Nullable Output<String> serviceType;

    /**
     * @return The type of service to use for this cluster in a hybrid cloud environment. Must be one of: CLUSTER_SERVICE_TYPE_CLUSTER_IP, CLUSTER_SERVICE_TYPE_LOAD_BALANCER, CLUSTER_SERVICE_TYPE_NODE_PORT.
     * 
     */
    public Optional<Output<String>> serviceType() {
        return Optional.ofNullable(this.serviceType);
    }

    /**
     * List of tolerations for this cluster in a hybrid cloud environment.
     * 
     */
    @Import(name="tolerations")
    private @Nullable Output<List<AccountsClusterConfigurationTolerationArgs>> tolerations;

    /**
     * @return List of tolerations for this cluster in a hybrid cloud environment.
     * 
     */
    public Optional<Output<List<AccountsClusterConfigurationTolerationArgs>>> tolerations() {
        return Optional.ofNullable(this.tolerations);
    }

    /**
     * List of topology spread constraints for this cluster in a hybrid cloud environment.
     * 
     */
    @Import(name="topologySpreadConstraints")
    private @Nullable Output<List<AccountsClusterConfigurationTopologySpreadConstraintArgs>> topologySpreadConstraints;

    /**
     * @return List of topology spread constraints for this cluster in a hybrid cloud environment.
     * 
     */
    public Optional<Output<List<AccountsClusterConfigurationTopologySpreadConstraintArgs>>> topologySpreadConstraints() {
        return Optional.ofNullable(this.topologySpreadConstraints);
    }

    /**
     * Cluster Schema Version of the Qdrant cluster field
     * 
     */
    @Import(name="version")
    private @Nullable Output<String> version;

    /**
     * @return Cluster Schema Version of the Qdrant cluster field
     * 
     */
    public Optional<Output<String>> version() {
        return Optional.ofNullable(this.version);
    }

    private AccountsClusterConfigurationArgs() {}

    private AccountsClusterConfigurationArgs(AccountsClusterConfigurationArgs $) {
        this.allowedIpSourceRanges = $.allowedIpSourceRanges;
        this.annotations = $.annotations;
        this.clusterStorageConfiguration = $.clusterStorageConfiguration;
        this.databaseConfiguration = $.databaseConfiguration;
        this.gpuType = $.gpuType;
        this.lastModifiedAt = $.lastModifiedAt;
        this.nodeConfiguration = $.nodeConfiguration;
        this.nodeSelectors = $.nodeSelectors;
        this.numberOfNodes = $.numberOfNodes;
        this.podLabels = $.podLabels;
        this.rebalanceStrategy = $.rebalanceStrategy;
        this.reservedCpuPercentage = $.reservedCpuPercentage;
        this.reservedMemoryPercentage = $.reservedMemoryPercentage;
        this.restartPolicy = $.restartPolicy;
        this.serviceAnnotations = $.serviceAnnotations;
        this.serviceType = $.serviceType;
        this.tolerations = $.tolerations;
        this.topologySpreadConstraints = $.topologySpreadConstraints;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountsClusterConfigurationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountsClusterConfigurationArgs $;

        public Builder() {
            $ = new AccountsClusterConfigurationArgs();
        }

        public Builder(AccountsClusterConfigurationArgs defaults) {
            $ = new AccountsClusterConfigurationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param allowedIpSourceRanges List of allowed IP source ranges for this cluster. On Hybrid Cloud, this will configure the loadBalancerSourceRanges of a LoadBalancer Service.
         * 
         * @return builder
         * 
         */
        public Builder allowedIpSourceRanges(@Nullable Output<List<String>> allowedIpSourceRanges) {
            $.allowedIpSourceRanges = allowedIpSourceRanges;
            return this;
        }

        /**
         * @param allowedIpSourceRanges List of allowed IP source ranges for this cluster. On Hybrid Cloud, this will configure the loadBalancerSourceRanges of a LoadBalancer Service.
         * 
         * @return builder
         * 
         */
        public Builder allowedIpSourceRanges(List<String> allowedIpSourceRanges) {
            return allowedIpSourceRanges(Output.of(allowedIpSourceRanges));
        }

        /**
         * @param allowedIpSourceRanges List of allowed IP source ranges for this cluster. On Hybrid Cloud, this will configure the loadBalancerSourceRanges of a LoadBalancer Service.
         * 
         * @return builder
         * 
         */
        public Builder allowedIpSourceRanges(String... allowedIpSourceRanges) {
            return allowedIpSourceRanges(List.of(allowedIpSourceRanges));
        }

        /**
         * @param annotations List of annotations for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder annotations(@Nullable Output<List<AccountsClusterConfigurationAnnotationArgs>> annotations) {
            $.annotations = annotations;
            return this;
        }

        /**
         * @param annotations List of annotations for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder annotations(List<AccountsClusterConfigurationAnnotationArgs> annotations) {
            return annotations(Output.of(annotations));
        }

        /**
         * @param annotations List of annotations for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder annotations(AccountsClusterConfigurationAnnotationArgs... annotations) {
            return annotations(List.of(annotations));
        }

        /**
         * @param clusterStorageConfiguration Configuration for cluster storage settings.
         * 
         * @return builder
         * 
         */
        public Builder clusterStorageConfiguration(@Nullable Output<AccountsClusterConfigurationClusterStorageConfigurationArgs> clusterStorageConfiguration) {
            $.clusterStorageConfiguration = clusterStorageConfiguration;
            return this;
        }

        /**
         * @param clusterStorageConfiguration Configuration for cluster storage settings.
         * 
         * @return builder
         * 
         */
        public Builder clusterStorageConfiguration(AccountsClusterConfigurationClusterStorageConfigurationArgs clusterStorageConfiguration) {
            return clusterStorageConfiguration(Output.of(clusterStorageConfiguration));
        }

        /**
         * @param databaseConfiguration Configuration for the Qdrant database engine, primarily for hybrid cloud setups.
         * 
         * @return builder
         * 
         */
        public Builder databaseConfiguration(@Nullable Output<AccountsClusterConfigurationDatabaseConfigurationArgs> databaseConfiguration) {
            $.databaseConfiguration = databaseConfiguration;
            return this;
        }

        /**
         * @param databaseConfiguration Configuration for the Qdrant database engine, primarily for hybrid cloud setups.
         * 
         * @return builder
         * 
         */
        public Builder databaseConfiguration(AccountsClusterConfigurationDatabaseConfigurationArgs databaseConfiguration) {
            return databaseConfiguration(Output.of(databaseConfiguration));
        }

        /**
         * @param gpuType The GPU type that should be used for the database. Must be one of: CLUSTER_CONFIGURATION_GPU_TYPE_AMD, CLUSTER_CONFIGURATION_GPU_TYPE_NVIDIA.
         * 
         * @return builder
         * 
         */
        public Builder gpuType(@Nullable Output<String> gpuType) {
            $.gpuType = gpuType;
            return this;
        }

        /**
         * @param gpuType The GPU type that should be used for the database. Must be one of: CLUSTER_CONFIGURATION_GPU_TYPE_AMD, CLUSTER_CONFIGURATION_GPU_TYPE_NVIDIA.
         * 
         * @return builder
         * 
         */
        public Builder gpuType(String gpuType) {
            return gpuType(Output.of(gpuType));
        }

        /**
         * @param lastModifiedAt Cluster Schema Timestamp when the cluster configuration was last updated field
         * 
         * @return builder
         * 
         */
        public Builder lastModifiedAt(@Nullable Output<String> lastModifiedAt) {
            $.lastModifiedAt = lastModifiedAt;
            return this;
        }

        /**
         * @param lastModifiedAt Cluster Schema Timestamp when the cluster configuration was last updated field
         * 
         * @return builder
         * 
         */
        public Builder lastModifiedAt(String lastModifiedAt) {
            return lastModifiedAt(Output.of(lastModifiedAt));
        }

        /**
         * @param nodeConfiguration Cluster Schema The node configuration options of a cluster field
         * 
         * @return builder
         * 
         */
        public Builder nodeConfiguration(Output<AccountsClusterConfigurationNodeConfigurationArgs> nodeConfiguration) {
            $.nodeConfiguration = nodeConfiguration;
            return this;
        }

        /**
         * @param nodeConfiguration Cluster Schema The node configuration options of a cluster field
         * 
         * @return builder
         * 
         */
        public Builder nodeConfiguration(AccountsClusterConfigurationNodeConfigurationArgs nodeConfiguration) {
            return nodeConfiguration(Output.of(nodeConfiguration));
        }

        /**
         * @param nodeSelectors The node selector for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder nodeSelectors(@Nullable Output<List<AccountsClusterConfigurationNodeSelectorArgs>> nodeSelectors) {
            $.nodeSelectors = nodeSelectors;
            return this;
        }

        /**
         * @param nodeSelectors The node selector for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder nodeSelectors(List<AccountsClusterConfigurationNodeSelectorArgs> nodeSelectors) {
            return nodeSelectors(Output.of(nodeSelectors));
        }

        /**
         * @param nodeSelectors The node selector for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder nodeSelectors(AccountsClusterConfigurationNodeSelectorArgs... nodeSelectors) {
            return nodeSelectors(List.of(nodeSelectors));
        }

        /**
         * @param numberOfNodes Cluster Schema The number of nodes in the cluster field
         * 
         * @return builder
         * 
         */
        public Builder numberOfNodes(Output<Double> numberOfNodes) {
            $.numberOfNodes = numberOfNodes;
            return this;
        }

        /**
         * @param numberOfNodes Cluster Schema The number of nodes in the cluster field
         * 
         * @return builder
         * 
         */
        public Builder numberOfNodes(Double numberOfNodes) {
            return numberOfNodes(Output.of(numberOfNodes));
        }

        /**
         * @param podLabels List of labels applied to the pods of this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder podLabels(@Nullable Output<List<AccountsClusterConfigurationPodLabelArgs>> podLabels) {
            $.podLabels = podLabels;
            return this;
        }

        /**
         * @param podLabels List of labels applied to the pods of this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder podLabels(List<AccountsClusterConfigurationPodLabelArgs> podLabels) {
            return podLabels(Output.of(podLabels));
        }

        /**
         * @param podLabels List of labels applied to the pods of this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder podLabels(AccountsClusterConfigurationPodLabelArgs... podLabels) {
            return podLabels(List.of(podLabels));
        }

        /**
         * @param rebalanceStrategy The automatic shard rebalancing strategy for the database. Must be one of: CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT_AND_SIZE, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_SIZE.
         * 
         * @return builder
         * 
         */
        public Builder rebalanceStrategy(@Nullable Output<String> rebalanceStrategy) {
            $.rebalanceStrategy = rebalanceStrategy;
            return this;
        }

        /**
         * @param rebalanceStrategy The automatic shard rebalancing strategy for the database. Must be one of: CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT_AND_SIZE, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_SIZE.
         * 
         * @return builder
         * 
         */
        public Builder rebalanceStrategy(String rebalanceStrategy) {
            return rebalanceStrategy(Output.of(rebalanceStrategy));
        }

        /**
         * @param reservedCpuPercentage The percentage of CPU resources reserved for system components.
         * 
         * @return builder
         * 
         */
        public Builder reservedCpuPercentage(@Nullable Output<Double> reservedCpuPercentage) {
            $.reservedCpuPercentage = reservedCpuPercentage;
            return this;
        }

        /**
         * @param reservedCpuPercentage The percentage of CPU resources reserved for system components.
         * 
         * @return builder
         * 
         */
        public Builder reservedCpuPercentage(Double reservedCpuPercentage) {
            return reservedCpuPercentage(Output.of(reservedCpuPercentage));
        }

        /**
         * @param reservedMemoryPercentage The percentage of RAM resources reserved for system components.
         * 
         * @return builder
         * 
         */
        public Builder reservedMemoryPercentage(@Nullable Output<Double> reservedMemoryPercentage) {
            $.reservedMemoryPercentage = reservedMemoryPercentage;
            return this;
        }

        /**
         * @param reservedMemoryPercentage The percentage of RAM resources reserved for system components.
         * 
         * @return builder
         * 
         */
        public Builder reservedMemoryPercentage(Double reservedMemoryPercentage) {
            return reservedMemoryPercentage(Output.of(reservedMemoryPercentage));
        }

        /**
         * @param restartPolicy The restart policy for the database. Must be one of: CLUSTER_CONFIGURATION_RESTART_POLICY_AUTOMATIC, CLUSTER_CONFIGURATION_RESTART_POLICY_PARALLEL, CLUSTER_CONFIGURATION_RESTART_POLICY_ROLLING.
         * 
         * @return builder
         * 
         */
        public Builder restartPolicy(@Nullable Output<String> restartPolicy) {
            $.restartPolicy = restartPolicy;
            return this;
        }

        /**
         * @param restartPolicy The restart policy for the database. Must be one of: CLUSTER_CONFIGURATION_RESTART_POLICY_AUTOMATIC, CLUSTER_CONFIGURATION_RESTART_POLICY_PARALLEL, CLUSTER_CONFIGURATION_RESTART_POLICY_ROLLING.
         * 
         * @return builder
         * 
         */
        public Builder restartPolicy(String restartPolicy) {
            return restartPolicy(Output.of(restartPolicy));
        }

        /**
         * @param serviceAnnotations List of annotations applied to the service of this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder serviceAnnotations(@Nullable Output<List<AccountsClusterConfigurationServiceAnnotationArgs>> serviceAnnotations) {
            $.serviceAnnotations = serviceAnnotations;
            return this;
        }

        /**
         * @param serviceAnnotations List of annotations applied to the service of this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder serviceAnnotations(List<AccountsClusterConfigurationServiceAnnotationArgs> serviceAnnotations) {
            return serviceAnnotations(Output.of(serviceAnnotations));
        }

        /**
         * @param serviceAnnotations List of annotations applied to the service of this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder serviceAnnotations(AccountsClusterConfigurationServiceAnnotationArgs... serviceAnnotations) {
            return serviceAnnotations(List.of(serviceAnnotations));
        }

        /**
         * @param serviceType The type of service to use for this cluster in a hybrid cloud environment. Must be one of: CLUSTER_SERVICE_TYPE_CLUSTER_IP, CLUSTER_SERVICE_TYPE_LOAD_BALANCER, CLUSTER_SERVICE_TYPE_NODE_PORT.
         * 
         * @return builder
         * 
         */
        public Builder serviceType(@Nullable Output<String> serviceType) {
            $.serviceType = serviceType;
            return this;
        }

        /**
         * @param serviceType The type of service to use for this cluster in a hybrid cloud environment. Must be one of: CLUSTER_SERVICE_TYPE_CLUSTER_IP, CLUSTER_SERVICE_TYPE_LOAD_BALANCER, CLUSTER_SERVICE_TYPE_NODE_PORT.
         * 
         * @return builder
         * 
         */
        public Builder serviceType(String serviceType) {
            return serviceType(Output.of(serviceType));
        }

        /**
         * @param tolerations List of tolerations for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder tolerations(@Nullable Output<List<AccountsClusterConfigurationTolerationArgs>> tolerations) {
            $.tolerations = tolerations;
            return this;
        }

        /**
         * @param tolerations List of tolerations for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder tolerations(List<AccountsClusterConfigurationTolerationArgs> tolerations) {
            return tolerations(Output.of(tolerations));
        }

        /**
         * @param tolerations List of tolerations for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder tolerations(AccountsClusterConfigurationTolerationArgs... tolerations) {
            return tolerations(List.of(tolerations));
        }

        /**
         * @param topologySpreadConstraints List of topology spread constraints for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder topologySpreadConstraints(@Nullable Output<List<AccountsClusterConfigurationTopologySpreadConstraintArgs>> topologySpreadConstraints) {
            $.topologySpreadConstraints = topologySpreadConstraints;
            return this;
        }

        /**
         * @param topologySpreadConstraints List of topology spread constraints for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder topologySpreadConstraints(List<AccountsClusterConfigurationTopologySpreadConstraintArgs> topologySpreadConstraints) {
            return topologySpreadConstraints(Output.of(topologySpreadConstraints));
        }

        /**
         * @param topologySpreadConstraints List of topology spread constraints for this cluster in a hybrid cloud environment.
         * 
         * @return builder
         * 
         */
        public Builder topologySpreadConstraints(AccountsClusterConfigurationTopologySpreadConstraintArgs... topologySpreadConstraints) {
            return topologySpreadConstraints(List.of(topologySpreadConstraints));
        }

        /**
         * @param version Cluster Schema Version of the Qdrant cluster field
         * 
         * @return builder
         * 
         */
        public Builder version(@Nullable Output<String> version) {
            $.version = version;
            return this;
        }

        /**
         * @param version Cluster Schema Version of the Qdrant cluster field
         * 
         * @return builder
         * 
         */
        public Builder version(String version) {
            return version(Output.of(version));
        }

        public AccountsClusterConfigurationArgs build() {
            if ($.nodeConfiguration == null) {
                throw new MissingRequiredPropertyException("AccountsClusterConfigurationArgs", "nodeConfiguration");
            }
            if ($.numberOfNodes == null) {
                throw new MissingRequiredPropertyException("AccountsClusterConfigurationArgs", "numberOfNodes");
            }
            return $;
        }
    }

}
