// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.qdrantcloud.inputs.AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs;
import com.pulumi.qdrantcloud.inputs.AccountsClusterConfigurationDatabaseConfigurationTlsKeyArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AccountsClusterConfigurationDatabaseConfigurationTlsArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountsClusterConfigurationDatabaseConfigurationTlsArgs Empty = new AccountsClusterConfigurationDatabaseConfigurationTlsArgs();

    /**
     * Secret to use for the certificate.
     * 
     */
    @Import(name="cert")
    private @Nullable Output<AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs> cert;

    /**
     * @return Secret to use for the certificate.
     * 
     */
    public Optional<Output<AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs>> cert() {
        return Optional.ofNullable(this.cert);
    }

    /**
     * Secret to use for the private key.
     * 
     */
    @Import(name="key")
    private @Nullable Output<AccountsClusterConfigurationDatabaseConfigurationTlsKeyArgs> key;

    /**
     * @return Secret to use for the private key.
     * 
     */
    public Optional<Output<AccountsClusterConfigurationDatabaseConfigurationTlsKeyArgs>> key() {
        return Optional.ofNullable(this.key);
    }

    private AccountsClusterConfigurationDatabaseConfigurationTlsArgs() {}

    private AccountsClusterConfigurationDatabaseConfigurationTlsArgs(AccountsClusterConfigurationDatabaseConfigurationTlsArgs $) {
        this.cert = $.cert;
        this.key = $.key;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountsClusterConfigurationDatabaseConfigurationTlsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountsClusterConfigurationDatabaseConfigurationTlsArgs $;

        public Builder() {
            $ = new AccountsClusterConfigurationDatabaseConfigurationTlsArgs();
        }

        public Builder(AccountsClusterConfigurationDatabaseConfigurationTlsArgs defaults) {
            $ = new AccountsClusterConfigurationDatabaseConfigurationTlsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cert Secret to use for the certificate.
         * 
         * @return builder
         * 
         */
        public Builder cert(@Nullable Output<AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs> cert) {
            $.cert = cert;
            return this;
        }

        /**
         * @param cert Secret to use for the certificate.
         * 
         * @return builder
         * 
         */
        public Builder cert(AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs cert) {
            return cert(Output.of(cert));
        }

        /**
         * @param key Secret to use for the private key.
         * 
         * @return builder
         * 
         */
        public Builder key(@Nullable Output<AccountsClusterConfigurationDatabaseConfigurationTlsKeyArgs> key) {
            $.key = key;
            return this;
        }

        /**
         * @param key Secret to use for the private key.
         * 
         * @return builder
         * 
         */
        public Builder key(AccountsClusterConfigurationDatabaseConfigurationTlsKeyArgs key) {
            return key(Output.of(key));
        }

        public AccountsClusterConfigurationDatabaseConfigurationTlsArgs build() {
            return $;
        }
    }

}
