// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.qdrantcloud.inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyArgs;
import com.pulumi.qdrantcloud.inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyArgs;
import java.lang.Boolean;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs Empty = new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs();

    @Import(name="apiKeys")
    private @Nullable Output<List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyArgs>> apiKeys;

    public Optional<Output<List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyArgs>>> apiKeys() {
        return Optional.ofNullable(this.apiKeys);
    }

    @Import(name="enableTls")
    private @Nullable Output<Boolean> enableTls;

    public Optional<Output<Boolean>> enableTls() {
        return Optional.ofNullable(this.enableTls);
    }

    @Import(name="forceIncludeJwtRbac")
    private @Nullable Output<Boolean> forceIncludeJwtRbac;

    public Optional<Output<Boolean>> forceIncludeJwtRbac() {
        return Optional.ofNullable(this.forceIncludeJwtRbac);
    }

    @Import(name="jwtRbac")
    private @Nullable Output<Boolean> jwtRbac;

    public Optional<Output<Boolean>> jwtRbac() {
        return Optional.ofNullable(this.jwtRbac);
    }

    @Import(name="readOnlyApiKeys")
    private @Nullable Output<List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyArgs>> readOnlyApiKeys;

    public Optional<Output<List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyArgs>>> readOnlyApiKeys() {
        return Optional.ofNullable(this.readOnlyApiKeys);
    }

    private AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs() {}

    private AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs $) {
        this.apiKeys = $.apiKeys;
        this.enableTls = $.enableTls;
        this.forceIncludeJwtRbac = $.forceIncludeJwtRbac;
        this.jwtRbac = $.jwtRbac;
        this.readOnlyApiKeys = $.readOnlyApiKeys;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs $;

        public Builder() {
            $ = new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs();
        }

        public Builder(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs defaults) {
            $ = new AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs(Objects.requireNonNull(defaults));
        }

        public Builder apiKeys(@Nullable Output<List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyArgs>> apiKeys) {
            $.apiKeys = apiKeys;
            return this;
        }

        public Builder apiKeys(List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyArgs> apiKeys) {
            return apiKeys(Output.of(apiKeys));
        }

        public Builder apiKeys(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKeyArgs... apiKeys) {
            return apiKeys(List.of(apiKeys));
        }

        public Builder enableTls(@Nullable Output<Boolean> enableTls) {
            $.enableTls = enableTls;
            return this;
        }

        public Builder enableTls(Boolean enableTls) {
            return enableTls(Output.of(enableTls));
        }

        public Builder forceIncludeJwtRbac(@Nullable Output<Boolean> forceIncludeJwtRbac) {
            $.forceIncludeJwtRbac = forceIncludeJwtRbac;
            return this;
        }

        public Builder forceIncludeJwtRbac(Boolean forceIncludeJwtRbac) {
            return forceIncludeJwtRbac(Output.of(forceIncludeJwtRbac));
        }

        public Builder jwtRbac(@Nullable Output<Boolean> jwtRbac) {
            $.jwtRbac = jwtRbac;
            return this;
        }

        public Builder jwtRbac(Boolean jwtRbac) {
            return jwtRbac(Output.of(jwtRbac));
        }

        public Builder readOnlyApiKeys(@Nullable Output<List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyArgs>> readOnlyApiKeys) {
            $.readOnlyApiKeys = readOnlyApiKeys;
            return this;
        }

        public Builder readOnlyApiKeys(List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyArgs> readOnlyApiKeys) {
            return readOnlyApiKeys(Output.of(readOnlyApiKeys));
        }

        public Builder readOnlyApiKeys(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKeyArgs... readOnlyApiKeys) {
            return readOnlyApiKeys(List.of(readOnlyApiKeys));
        }

        public AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceArgs build() {
            return $;
        }
    }

}
