// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.qdrantcloud.inputs.AccountsManualBackupClusterInfoConfigurationAnnotationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsManualBackupClusterInfoConfigurationClusterStorageConfigurationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsManualBackupClusterInfoConfigurationNodeConfigurationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsManualBackupClusterInfoConfigurationNodeSelectorArgs;
import com.pulumi.qdrantcloud.inputs.AccountsManualBackupClusterInfoConfigurationPodLabelArgs;
import com.pulumi.qdrantcloud.inputs.AccountsManualBackupClusterInfoConfigurationServiceAnnotationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsManualBackupClusterInfoConfigurationTolerationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsManualBackupClusterInfoConfigurationTopologySpreadConstraintArgs;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AccountsManualBackupClusterInfoConfigurationArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountsManualBackupClusterInfoConfigurationArgs Empty = new AccountsManualBackupClusterInfoConfigurationArgs();

    @Import(name="allowedIpSourceRanges")
    private @Nullable Output<List<String>> allowedIpSourceRanges;

    public Optional<Output<List<String>>> allowedIpSourceRanges() {
        return Optional.ofNullable(this.allowedIpSourceRanges);
    }

    @Import(name="annotations")
    private @Nullable Output<List<AccountsManualBackupClusterInfoConfigurationAnnotationArgs>> annotations;

    public Optional<Output<List<AccountsManualBackupClusterInfoConfigurationAnnotationArgs>>> annotations() {
        return Optional.ofNullable(this.annotations);
    }

    @Import(name="clusterStorageConfigurations")
    private @Nullable Output<List<AccountsManualBackupClusterInfoConfigurationClusterStorageConfigurationArgs>> clusterStorageConfigurations;

    public Optional<Output<List<AccountsManualBackupClusterInfoConfigurationClusterStorageConfigurationArgs>>> clusterStorageConfigurations() {
        return Optional.ofNullable(this.clusterStorageConfigurations);
    }

    @Import(name="databaseConfigurations")
    private @Nullable Output<List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationArgs>> databaseConfigurations;

    public Optional<Output<List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationArgs>>> databaseConfigurations() {
        return Optional.ofNullable(this.databaseConfigurations);
    }

    @Import(name="gpuType")
    private @Nullable Output<String> gpuType;

    public Optional<Output<String>> gpuType() {
        return Optional.ofNullable(this.gpuType);
    }

    @Import(name="lastModifiedAt")
    private @Nullable Output<String> lastModifiedAt;

    public Optional<Output<String>> lastModifiedAt() {
        return Optional.ofNullable(this.lastModifiedAt);
    }

    @Import(name="nodeConfigurations")
    private @Nullable Output<List<AccountsManualBackupClusterInfoConfigurationNodeConfigurationArgs>> nodeConfigurations;

    public Optional<Output<List<AccountsManualBackupClusterInfoConfigurationNodeConfigurationArgs>>> nodeConfigurations() {
        return Optional.ofNullable(this.nodeConfigurations);
    }

    @Import(name="nodeSelectors")
    private @Nullable Output<List<AccountsManualBackupClusterInfoConfigurationNodeSelectorArgs>> nodeSelectors;

    public Optional<Output<List<AccountsManualBackupClusterInfoConfigurationNodeSelectorArgs>>> nodeSelectors() {
        return Optional.ofNullable(this.nodeSelectors);
    }

    @Import(name="numberOfNodes")
    private @Nullable Output<Double> numberOfNodes;

    public Optional<Output<Double>> numberOfNodes() {
        return Optional.ofNullable(this.numberOfNodes);
    }

    @Import(name="podLabels")
    private @Nullable Output<List<AccountsManualBackupClusterInfoConfigurationPodLabelArgs>> podLabels;

    public Optional<Output<List<AccountsManualBackupClusterInfoConfigurationPodLabelArgs>>> podLabels() {
        return Optional.ofNullable(this.podLabels);
    }

    @Import(name="rebalanceStrategy")
    private @Nullable Output<String> rebalanceStrategy;

    public Optional<Output<String>> rebalanceStrategy() {
        return Optional.ofNullable(this.rebalanceStrategy);
    }

    @Import(name="reservedCpuPercentage")
    private @Nullable Output<Double> reservedCpuPercentage;

    public Optional<Output<Double>> reservedCpuPercentage() {
        return Optional.ofNullable(this.reservedCpuPercentage);
    }

    @Import(name="reservedMemoryPercentage")
    private @Nullable Output<Double> reservedMemoryPercentage;

    public Optional<Output<Double>> reservedMemoryPercentage() {
        return Optional.ofNullable(this.reservedMemoryPercentage);
    }

    @Import(name="restartPolicy")
    private @Nullable Output<String> restartPolicy;

    public Optional<Output<String>> restartPolicy() {
        return Optional.ofNullable(this.restartPolicy);
    }

    @Import(name="serviceAnnotations")
    private @Nullable Output<List<AccountsManualBackupClusterInfoConfigurationServiceAnnotationArgs>> serviceAnnotations;

    public Optional<Output<List<AccountsManualBackupClusterInfoConfigurationServiceAnnotationArgs>>> serviceAnnotations() {
        return Optional.ofNullable(this.serviceAnnotations);
    }

    @Import(name="serviceType")
    private @Nullable Output<String> serviceType;

    public Optional<Output<String>> serviceType() {
        return Optional.ofNullable(this.serviceType);
    }

    @Import(name="tolerations")
    private @Nullable Output<List<AccountsManualBackupClusterInfoConfigurationTolerationArgs>> tolerations;

    public Optional<Output<List<AccountsManualBackupClusterInfoConfigurationTolerationArgs>>> tolerations() {
        return Optional.ofNullable(this.tolerations);
    }

    @Import(name="topologySpreadConstraints")
    private @Nullable Output<List<AccountsManualBackupClusterInfoConfigurationTopologySpreadConstraintArgs>> topologySpreadConstraints;

    public Optional<Output<List<AccountsManualBackupClusterInfoConfigurationTopologySpreadConstraintArgs>>> topologySpreadConstraints() {
        return Optional.ofNullable(this.topologySpreadConstraints);
    }

    @Import(name="version")
    private @Nullable Output<String> version;

    public Optional<Output<String>> version() {
        return Optional.ofNullable(this.version);
    }

    private AccountsManualBackupClusterInfoConfigurationArgs() {}

    private AccountsManualBackupClusterInfoConfigurationArgs(AccountsManualBackupClusterInfoConfigurationArgs $) {
        this.allowedIpSourceRanges = $.allowedIpSourceRanges;
        this.annotations = $.annotations;
        this.clusterStorageConfigurations = $.clusterStorageConfigurations;
        this.databaseConfigurations = $.databaseConfigurations;
        this.gpuType = $.gpuType;
        this.lastModifiedAt = $.lastModifiedAt;
        this.nodeConfigurations = $.nodeConfigurations;
        this.nodeSelectors = $.nodeSelectors;
        this.numberOfNodes = $.numberOfNodes;
        this.podLabels = $.podLabels;
        this.rebalanceStrategy = $.rebalanceStrategy;
        this.reservedCpuPercentage = $.reservedCpuPercentage;
        this.reservedMemoryPercentage = $.reservedMemoryPercentage;
        this.restartPolicy = $.restartPolicy;
        this.serviceAnnotations = $.serviceAnnotations;
        this.serviceType = $.serviceType;
        this.tolerations = $.tolerations;
        this.topologySpreadConstraints = $.topologySpreadConstraints;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountsManualBackupClusterInfoConfigurationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountsManualBackupClusterInfoConfigurationArgs $;

        public Builder() {
            $ = new AccountsManualBackupClusterInfoConfigurationArgs();
        }

        public Builder(AccountsManualBackupClusterInfoConfigurationArgs defaults) {
            $ = new AccountsManualBackupClusterInfoConfigurationArgs(Objects.requireNonNull(defaults));
        }

        public Builder allowedIpSourceRanges(@Nullable Output<List<String>> allowedIpSourceRanges) {
            $.allowedIpSourceRanges = allowedIpSourceRanges;
            return this;
        }

        public Builder allowedIpSourceRanges(List<String> allowedIpSourceRanges) {
            return allowedIpSourceRanges(Output.of(allowedIpSourceRanges));
        }

        public Builder allowedIpSourceRanges(String... allowedIpSourceRanges) {
            return allowedIpSourceRanges(List.of(allowedIpSourceRanges));
        }

        public Builder annotations(@Nullable Output<List<AccountsManualBackupClusterInfoConfigurationAnnotationArgs>> annotations) {
            $.annotations = annotations;
            return this;
        }

        public Builder annotations(List<AccountsManualBackupClusterInfoConfigurationAnnotationArgs> annotations) {
            return annotations(Output.of(annotations));
        }

        public Builder annotations(AccountsManualBackupClusterInfoConfigurationAnnotationArgs... annotations) {
            return annotations(List.of(annotations));
        }

        public Builder clusterStorageConfigurations(@Nullable Output<List<AccountsManualBackupClusterInfoConfigurationClusterStorageConfigurationArgs>> clusterStorageConfigurations) {
            $.clusterStorageConfigurations = clusterStorageConfigurations;
            return this;
        }

        public Builder clusterStorageConfigurations(List<AccountsManualBackupClusterInfoConfigurationClusterStorageConfigurationArgs> clusterStorageConfigurations) {
            return clusterStorageConfigurations(Output.of(clusterStorageConfigurations));
        }

        public Builder clusterStorageConfigurations(AccountsManualBackupClusterInfoConfigurationClusterStorageConfigurationArgs... clusterStorageConfigurations) {
            return clusterStorageConfigurations(List.of(clusterStorageConfigurations));
        }

        public Builder databaseConfigurations(@Nullable Output<List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationArgs>> databaseConfigurations) {
            $.databaseConfigurations = databaseConfigurations;
            return this;
        }

        public Builder databaseConfigurations(List<AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationArgs> databaseConfigurations) {
            return databaseConfigurations(Output.of(databaseConfigurations));
        }

        public Builder databaseConfigurations(AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationArgs... databaseConfigurations) {
            return databaseConfigurations(List.of(databaseConfigurations));
        }

        public Builder gpuType(@Nullable Output<String> gpuType) {
            $.gpuType = gpuType;
            return this;
        }

        public Builder gpuType(String gpuType) {
            return gpuType(Output.of(gpuType));
        }

        public Builder lastModifiedAt(@Nullable Output<String> lastModifiedAt) {
            $.lastModifiedAt = lastModifiedAt;
            return this;
        }

        public Builder lastModifiedAt(String lastModifiedAt) {
            return lastModifiedAt(Output.of(lastModifiedAt));
        }

        public Builder nodeConfigurations(@Nullable Output<List<AccountsManualBackupClusterInfoConfigurationNodeConfigurationArgs>> nodeConfigurations) {
            $.nodeConfigurations = nodeConfigurations;
            return this;
        }

        public Builder nodeConfigurations(List<AccountsManualBackupClusterInfoConfigurationNodeConfigurationArgs> nodeConfigurations) {
            return nodeConfigurations(Output.of(nodeConfigurations));
        }

        public Builder nodeConfigurations(AccountsManualBackupClusterInfoConfigurationNodeConfigurationArgs... nodeConfigurations) {
            return nodeConfigurations(List.of(nodeConfigurations));
        }

        public Builder nodeSelectors(@Nullable Output<List<AccountsManualBackupClusterInfoConfigurationNodeSelectorArgs>> nodeSelectors) {
            $.nodeSelectors = nodeSelectors;
            return this;
        }

        public Builder nodeSelectors(List<AccountsManualBackupClusterInfoConfigurationNodeSelectorArgs> nodeSelectors) {
            return nodeSelectors(Output.of(nodeSelectors));
        }

        public Builder nodeSelectors(AccountsManualBackupClusterInfoConfigurationNodeSelectorArgs... nodeSelectors) {
            return nodeSelectors(List.of(nodeSelectors));
        }

        public Builder numberOfNodes(@Nullable Output<Double> numberOfNodes) {
            $.numberOfNodes = numberOfNodes;
            return this;
        }

        public Builder numberOfNodes(Double numberOfNodes) {
            return numberOfNodes(Output.of(numberOfNodes));
        }

        public Builder podLabels(@Nullable Output<List<AccountsManualBackupClusterInfoConfigurationPodLabelArgs>> podLabels) {
            $.podLabels = podLabels;
            return this;
        }

        public Builder podLabels(List<AccountsManualBackupClusterInfoConfigurationPodLabelArgs> podLabels) {
            return podLabels(Output.of(podLabels));
        }

        public Builder podLabels(AccountsManualBackupClusterInfoConfigurationPodLabelArgs... podLabels) {
            return podLabels(List.of(podLabels));
        }

        public Builder rebalanceStrategy(@Nullable Output<String> rebalanceStrategy) {
            $.rebalanceStrategy = rebalanceStrategy;
            return this;
        }

        public Builder rebalanceStrategy(String rebalanceStrategy) {
            return rebalanceStrategy(Output.of(rebalanceStrategy));
        }

        public Builder reservedCpuPercentage(@Nullable Output<Double> reservedCpuPercentage) {
            $.reservedCpuPercentage = reservedCpuPercentage;
            return this;
        }

        public Builder reservedCpuPercentage(Double reservedCpuPercentage) {
            return reservedCpuPercentage(Output.of(reservedCpuPercentage));
        }

        public Builder reservedMemoryPercentage(@Nullable Output<Double> reservedMemoryPercentage) {
            $.reservedMemoryPercentage = reservedMemoryPercentage;
            return this;
        }

        public Builder reservedMemoryPercentage(Double reservedMemoryPercentage) {
            return reservedMemoryPercentage(Output.of(reservedMemoryPercentage));
        }

        public Builder restartPolicy(@Nullable Output<String> restartPolicy) {
            $.restartPolicy = restartPolicy;
            return this;
        }

        public Builder restartPolicy(String restartPolicy) {
            return restartPolicy(Output.of(restartPolicy));
        }

        public Builder serviceAnnotations(@Nullable Output<List<AccountsManualBackupClusterInfoConfigurationServiceAnnotationArgs>> serviceAnnotations) {
            $.serviceAnnotations = serviceAnnotations;
            return this;
        }

        public Builder serviceAnnotations(List<AccountsManualBackupClusterInfoConfigurationServiceAnnotationArgs> serviceAnnotations) {
            return serviceAnnotations(Output.of(serviceAnnotations));
        }

        public Builder serviceAnnotations(AccountsManualBackupClusterInfoConfigurationServiceAnnotationArgs... serviceAnnotations) {
            return serviceAnnotations(List.of(serviceAnnotations));
        }

        public Builder serviceType(@Nullable Output<String> serviceType) {
            $.serviceType = serviceType;
            return this;
        }

        public Builder serviceType(String serviceType) {
            return serviceType(Output.of(serviceType));
        }

        public Builder tolerations(@Nullable Output<List<AccountsManualBackupClusterInfoConfigurationTolerationArgs>> tolerations) {
            $.tolerations = tolerations;
            return this;
        }

        public Builder tolerations(List<AccountsManualBackupClusterInfoConfigurationTolerationArgs> tolerations) {
            return tolerations(Output.of(tolerations));
        }

        public Builder tolerations(AccountsManualBackupClusterInfoConfigurationTolerationArgs... tolerations) {
            return tolerations(List.of(tolerations));
        }

        public Builder topologySpreadConstraints(@Nullable Output<List<AccountsManualBackupClusterInfoConfigurationTopologySpreadConstraintArgs>> topologySpreadConstraints) {
            $.topologySpreadConstraints = topologySpreadConstraints;
            return this;
        }

        public Builder topologySpreadConstraints(List<AccountsManualBackupClusterInfoConfigurationTopologySpreadConstraintArgs> topologySpreadConstraints) {
            return topologySpreadConstraints(Output.of(topologySpreadConstraints));
        }

        public Builder topologySpreadConstraints(AccountsManualBackupClusterInfoConfigurationTopologySpreadConstraintArgs... topologySpreadConstraints) {
            return topologySpreadConstraints(List.of(topologySpreadConstraints));
        }

        public Builder version(@Nullable Output<String> version) {
            $.version = version;
            return this;
        }

        public Builder version(String version) {
            return version(Output.of(version));
        }

        public AccountsManualBackupClusterInfoConfigurationArgs build() {
            return $;
        }
    }

}
