// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs Empty = new AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs();

    /**
     * The key within the secret.
     * 
     */
    @Import(name="secretKey", required=true)
    private Output<String> secretKey;

    /**
     * @return The key within the secret.
     * 
     */
    public Output<String> secretKey() {
        return this.secretKey;
    }

    /**
     * The name of the secret.
     * 
     */
    @Import(name="secretName", required=true)
    private Output<String> secretName;

    /**
     * @return The name of the secret.
     * 
     */
    public Output<String> secretName() {
        return this.secretName;
    }

    private AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs() {}

    private AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs(AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs $) {
        this.secretKey = $.secretKey;
        this.secretName = $.secretName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs $;

        public Builder() {
            $ = new AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs();
        }

        public Builder(AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs defaults) {
            $ = new AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param secretKey The key within the secret.
         * 
         * @return builder
         * 
         */
        public Builder secretKey(Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        /**
         * @param secretKey The key within the secret.
         * 
         * @return builder
         * 
         */
        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        /**
         * @param secretName The name of the secret.
         * 
         * @return builder
         * 
         */
        public Builder secretName(Output<String> secretName) {
            $.secretName = secretName;
            return this;
        }

        /**
         * @param secretName The name of the secret.
         * 
         * @return builder
         * 
         */
        public Builder secretName(String secretName) {
            return secretName(Output.of(secretName));
        }

        public AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs build() {
            if ($.secretKey == null) {
                throw new MissingRequiredPropertyException("AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs", "secretKey");
            }
            if ($.secretName == null) {
                throw new MissingRequiredPropertyException("AccountsClusterConfigurationDatabaseConfigurationTlsCertArgs", "secretName");
            }
            return $;
        }
    }

}
