// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.qdrantcloud.inputs.AccountsHybridCloudEnvironmentConfigurationArgs;
import com.pulumi.qdrantcloud.inputs.AccountsHybridCloudEnvironmentStatusArgs;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AccountsHybridCloudEnvironmentState extends com.pulumi.resources.ResourceArgs {

    public static final AccountsHybridCloudEnvironmentState Empty = new AccountsHybridCloudEnvironmentState();

    /**
     * Hybrid cloud environment Schema Account ID field
     * 
     */
    @Import(name="accountId")
    private @Nullable Output<String> accountId;

    /**
     * @return Hybrid cloud environment Schema Account ID field
     * 
     */
    public Optional<Output<String>> accountId() {
        return Optional.ofNullable(this.accountId);
    }

    /**
     * Hybrid cloud environment Schema Commands to bootstrap a Kubernetes cluster into this environment field
     * 
     */
    @Import(name="bootstrapCommands")
    private @Nullable Output<List<String>> bootstrapCommands;

    /**
     * @return Hybrid cloud environment Schema Commands to bootstrap a Kubernetes cluster into this environment field
     * 
     */
    public Optional<Output<List<String>>> bootstrapCommands() {
        return Optional.ofNullable(this.bootstrapCommands);
    }

    /**
     * Hybrid cloud environment Schema Set if the generate bootstrap commands has been called at least once field
     * 
     */
    @Import(name="bootstrapCommandsGenerated")
    private @Nullable Output<Boolean> bootstrapCommandsGenerated;

    /**
     * @return Hybrid cloud environment Schema Set if the generate bootstrap commands has been called at least once field
     * 
     */
    public Optional<Output<Boolean>> bootstrapCommandsGenerated() {
        return Optional.ofNullable(this.bootstrapCommandsGenerated);
    }

    /**
     * Version knob to (re)generate bootstrap commands. -1 = never generate, 0 = idle/do not (re)generate, &gt;0 = generate/rotate.
     * 
     */
    @Import(name="bootstrapCommandsVersion")
    private @Nullable Output<Double> bootstrapCommandsVersion;

    /**
     * @return Version knob to (re)generate bootstrap commands. -1 = never generate, 0 = idle/do not (re)generate, &gt;0 = generate/rotate.
     * 
     */
    public Optional<Output<Double>> bootstrapCommandsVersion() {
        return Optional.ofNullable(this.bootstrapCommandsVersion);
    }

    /**
     * Hybrid cloud environment Schema Configuration field
     * 
     */
    @Import(name="configuration")
    private @Nullable Output<AccountsHybridCloudEnvironmentConfigurationArgs> configuration;

    /**
     * @return Hybrid cloud environment Schema Configuration field
     * 
     */
    public Optional<Output<AccountsHybridCloudEnvironmentConfigurationArgs>> configuration() {
        return Optional.ofNullable(this.configuration);
    }

    /**
     * Hybrid cloud environment Schema Creation timestamp field
     * 
     */
    @Import(name="createdAt")
    private @Nullable Output<String> createdAt;

    /**
     * @return Hybrid cloud environment Schema Creation timestamp field
     * 
     */
    public Optional<Output<String>> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    /**
     * Hybrid cloud environment Schema The email of the user who created the hybrid cloud environment field
     * 
     */
    @Import(name="createdByEmail")
    private @Nullable Output<String> createdByEmail;

    /**
     * @return Hybrid cloud environment Schema The email of the user who created the hybrid cloud environment field
     * 
     */
    public Optional<Output<String>> createdByEmail() {
        return Optional.ofNullable(this.createdByEmail);
    }

    /**
     * Hybrid cloud environment Schema Last modification timestamp field
     * 
     */
    @Import(name="lastModifiedAt")
    private @Nullable Output<String> lastModifiedAt;

    /**
     * @return Hybrid cloud environment Schema Last modification timestamp field
     * 
     */
    public Optional<Output<String>> lastModifiedAt() {
        return Optional.ofNullable(this.lastModifiedAt);
    }

    /**
     * Hybrid cloud environment Schema Name field
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Hybrid cloud environment Schema Name field
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Current status of the hybrid cloud environment (read-only).
     * 
     */
    @Import(name="statuses")
    private @Nullable Output<List<AccountsHybridCloudEnvironmentStatusArgs>> statuses;

    /**
     * @return Current status of the hybrid cloud environment (read-only).
     * 
     */
    public Optional<Output<List<AccountsHybridCloudEnvironmentStatusArgs>>> statuses() {
        return Optional.ofNullable(this.statuses);
    }

    private AccountsHybridCloudEnvironmentState() {}

    private AccountsHybridCloudEnvironmentState(AccountsHybridCloudEnvironmentState $) {
        this.accountId = $.accountId;
        this.bootstrapCommands = $.bootstrapCommands;
        this.bootstrapCommandsGenerated = $.bootstrapCommandsGenerated;
        this.bootstrapCommandsVersion = $.bootstrapCommandsVersion;
        this.configuration = $.configuration;
        this.createdAt = $.createdAt;
        this.createdByEmail = $.createdByEmail;
        this.lastModifiedAt = $.lastModifiedAt;
        this.name = $.name;
        this.statuses = $.statuses;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountsHybridCloudEnvironmentState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountsHybridCloudEnvironmentState $;

        public Builder() {
            $ = new AccountsHybridCloudEnvironmentState();
        }

        public Builder(AccountsHybridCloudEnvironmentState defaults) {
            $ = new AccountsHybridCloudEnvironmentState(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId Hybrid cloud environment Schema Account ID field
         * 
         * @return builder
         * 
         */
        public Builder accountId(@Nullable Output<String> accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param accountId Hybrid cloud environment Schema Account ID field
         * 
         * @return builder
         * 
         */
        public Builder accountId(String accountId) {
            return accountId(Output.of(accountId));
        }

        /**
         * @param bootstrapCommands Hybrid cloud environment Schema Commands to bootstrap a Kubernetes cluster into this environment field
         * 
         * @return builder
         * 
         */
        public Builder bootstrapCommands(@Nullable Output<List<String>> bootstrapCommands) {
            $.bootstrapCommands = bootstrapCommands;
            return this;
        }

        /**
         * @param bootstrapCommands Hybrid cloud environment Schema Commands to bootstrap a Kubernetes cluster into this environment field
         * 
         * @return builder
         * 
         */
        public Builder bootstrapCommands(List<String> bootstrapCommands) {
            return bootstrapCommands(Output.of(bootstrapCommands));
        }

        /**
         * @param bootstrapCommands Hybrid cloud environment Schema Commands to bootstrap a Kubernetes cluster into this environment field
         * 
         * @return builder
         * 
         */
        public Builder bootstrapCommands(String... bootstrapCommands) {
            return bootstrapCommands(List.of(bootstrapCommands));
        }

        /**
         * @param bootstrapCommandsGenerated Hybrid cloud environment Schema Set if the generate bootstrap commands has been called at least once field
         * 
         * @return builder
         * 
         */
        public Builder bootstrapCommandsGenerated(@Nullable Output<Boolean> bootstrapCommandsGenerated) {
            $.bootstrapCommandsGenerated = bootstrapCommandsGenerated;
            return this;
        }

        /**
         * @param bootstrapCommandsGenerated Hybrid cloud environment Schema Set if the generate bootstrap commands has been called at least once field
         * 
         * @return builder
         * 
         */
        public Builder bootstrapCommandsGenerated(Boolean bootstrapCommandsGenerated) {
            return bootstrapCommandsGenerated(Output.of(bootstrapCommandsGenerated));
        }

        /**
         * @param bootstrapCommandsVersion Version knob to (re)generate bootstrap commands. -1 = never generate, 0 = idle/do not (re)generate, &gt;0 = generate/rotate.
         * 
         * @return builder
         * 
         */
        public Builder bootstrapCommandsVersion(@Nullable Output<Double> bootstrapCommandsVersion) {
            $.bootstrapCommandsVersion = bootstrapCommandsVersion;
            return this;
        }

        /**
         * @param bootstrapCommandsVersion Version knob to (re)generate bootstrap commands. -1 = never generate, 0 = idle/do not (re)generate, &gt;0 = generate/rotate.
         * 
         * @return builder
         * 
         */
        public Builder bootstrapCommandsVersion(Double bootstrapCommandsVersion) {
            return bootstrapCommandsVersion(Output.of(bootstrapCommandsVersion));
        }

        /**
         * @param configuration Hybrid cloud environment Schema Configuration field
         * 
         * @return builder
         * 
         */
        public Builder configuration(@Nullable Output<AccountsHybridCloudEnvironmentConfigurationArgs> configuration) {
            $.configuration = configuration;
            return this;
        }

        /**
         * @param configuration Hybrid cloud environment Schema Configuration field
         * 
         * @return builder
         * 
         */
        public Builder configuration(AccountsHybridCloudEnvironmentConfigurationArgs configuration) {
            return configuration(Output.of(configuration));
        }

        /**
         * @param createdAt Hybrid cloud environment Schema Creation timestamp field
         * 
         * @return builder
         * 
         */
        public Builder createdAt(@Nullable Output<String> createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        /**
         * @param createdAt Hybrid cloud environment Schema Creation timestamp field
         * 
         * @return builder
         * 
         */
        public Builder createdAt(String createdAt) {
            return createdAt(Output.of(createdAt));
        }

        /**
         * @param createdByEmail Hybrid cloud environment Schema The email of the user who created the hybrid cloud environment field
         * 
         * @return builder
         * 
         */
        public Builder createdByEmail(@Nullable Output<String> createdByEmail) {
            $.createdByEmail = createdByEmail;
            return this;
        }

        /**
         * @param createdByEmail Hybrid cloud environment Schema The email of the user who created the hybrid cloud environment field
         * 
         * @return builder
         * 
         */
        public Builder createdByEmail(String createdByEmail) {
            return createdByEmail(Output.of(createdByEmail));
        }

        /**
         * @param lastModifiedAt Hybrid cloud environment Schema Last modification timestamp field
         * 
         * @return builder
         * 
         */
        public Builder lastModifiedAt(@Nullable Output<String> lastModifiedAt) {
            $.lastModifiedAt = lastModifiedAt;
            return this;
        }

        /**
         * @param lastModifiedAt Hybrid cloud environment Schema Last modification timestamp field
         * 
         * @return builder
         * 
         */
        public Builder lastModifiedAt(String lastModifiedAt) {
            return lastModifiedAt(Output.of(lastModifiedAt));
        }

        /**
         * @param name Hybrid cloud environment Schema Name field
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Hybrid cloud environment Schema Name field
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param statuses Current status of the hybrid cloud environment (read-only).
         * 
         * @return builder
         * 
         */
        public Builder statuses(@Nullable Output<List<AccountsHybridCloudEnvironmentStatusArgs>> statuses) {
            $.statuses = statuses;
            return this;
        }

        /**
         * @param statuses Current status of the hybrid cloud environment (read-only).
         * 
         * @return builder
         * 
         */
        public Builder statuses(List<AccountsHybridCloudEnvironmentStatusArgs> statuses) {
            return statuses(Output.of(statuses));
        }

        /**
         * @param statuses Current status of the hybrid cloud environment (read-only).
         * 
         * @return builder
         * 
         */
        public Builder statuses(AccountsHybridCloudEnvironmentStatusArgs... statuses) {
            return statuses(List.of(statuses));
        }

        public AccountsHybridCloudEnvironmentState build() {
            return $;
        }
    }

}
