// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs Empty = new AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs();

    @Import(name="key", required=true)
    private Output<String> key;

    public Output<String> key() {
        return this.key;
    }

    @Import(name="value", required=true)
    private Output<String> value;

    public Output<String> value() {
        return this.value;
    }

    private AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs() {}

    private AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs(AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs $) {
        this.key = $.key;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs $;

        public Builder() {
            $ = new AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs();
        }

        public Builder(AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs defaults) {
            $ = new AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs(Objects.requireNonNull(defaults));
        }

        public Builder key(Output<String> key) {
            $.key = key;
            return this;
        }

        public Builder key(String key) {
            return key(Output.of(key));
        }

        public Builder value(Output<String> value) {
            $.value = value;
            return this;
        }

        public Builder value(String value) {
            return value(Output.of(value));
        }

        public AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs build() {
            if ($.key == null) {
                throw new MissingRequiredPropertyException("AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs", "key");
            }
            if ($.value == null) {
                throw new MissingRequiredPropertyException("AccountsHybridCloudEnvironmentConfigurationControlPlaneLabelArgs", "value");
            }
            return $;
        }
    }

}
