// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AccountsRolePermissionArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountsRolePermissionArgs Empty = new AccountsRolePermissionArgs();

    /**
     * Permission category (e.g., &#34;Cluster&#34;, &#34;Account&#34;).
     * 
     */
    @Import(name="category")
    private @Nullable Output<String> category;

    /**
     * @return Permission category (e.g., &#34;Cluster&#34;, &#34;Account&#34;).
     * 
     */
    public Optional<Output<String>> category() {
        return Optional.ofNullable(this.category);
    }

    /**
     * Permission value (e.g., &#34;read:backups&#34;).
     * 
     */
    @Import(name="value", required=true)
    private Output<String> value;

    /**
     * @return Permission value (e.g., &#34;read:backups&#34;).
     * 
     */
    public Output<String> value() {
        return this.value;
    }

    private AccountsRolePermissionArgs() {}

    private AccountsRolePermissionArgs(AccountsRolePermissionArgs $) {
        this.category = $.category;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountsRolePermissionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountsRolePermissionArgs $;

        public Builder() {
            $ = new AccountsRolePermissionArgs();
        }

        public Builder(AccountsRolePermissionArgs defaults) {
            $ = new AccountsRolePermissionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param category Permission category (e.g., &#34;Cluster&#34;, &#34;Account&#34;).
         * 
         * @return builder
         * 
         */
        public Builder category(@Nullable Output<String> category) {
            $.category = category;
            return this;
        }

        /**
         * @param category Permission category (e.g., &#34;Cluster&#34;, &#34;Account&#34;).
         * 
         * @return builder
         * 
         */
        public Builder category(String category) {
            return category(Output.of(category));
        }

        /**
         * @param value Permission value (e.g., &#34;read:backups&#34;).
         * 
         * @return builder
         * 
         */
        public Builder value(Output<String> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value Permission value (e.g., &#34;read:backups&#34;).
         * 
         * @return builder
         * 
         */
        public Builder value(String value) {
            return value(Output.of(value));
        }

        public AccountsRolePermissionArgs build() {
            if ($.value == null) {
                throw new MissingRequiredPropertyException("AccountsRolePermissionArgs", "value");
            }
            return $;
        }
    }

}
