// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAccountsRolesArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAccountsRolesArgs Empty = new GetAccountsRolesArgs();

    @Import(name="accountId")
    private @Nullable Output<String> accountId;

    public Optional<Output<String>> accountId() {
        return Optional.ofNullable(this.accountId);
    }

    @Import(name="id")
    private @Nullable Output<String> id;

    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    private GetAccountsRolesArgs() {}

    private GetAccountsRolesArgs(GetAccountsRolesArgs $) {
        this.accountId = $.accountId;
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAccountsRolesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAccountsRolesArgs $;

        public Builder() {
            $ = new GetAccountsRolesArgs();
        }

        public Builder(GetAccountsRolesArgs defaults) {
            $ = new GetAccountsRolesArgs(Objects.requireNonNull(defaults));
        }

        public Builder accountId(@Nullable Output<String> accountId) {
            $.accountId = accountId;
            return this;
        }

        public Builder accountId(String accountId) {
            return accountId(Output.of(accountId));
        }

        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        public Builder id(String id) {
            return id(Output.of(id));
        }

        public GetAccountsRolesArgs build() {
            return $;
        }
    }

}
