// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAccountsDatabaseApiKeysV2Args extends com.pulumi.resources.InvokeArgs {

    public static final GetAccountsDatabaseApiKeysV2Args Empty = new GetAccountsDatabaseApiKeysV2Args();

    @Import(name="accountId")
    private @Nullable Output<String> accountId;

    public Optional<Output<String>> accountId() {
        return Optional.ofNullable(this.accountId);
    }

    @Import(name="clusterId", required=true)
    private Output<String> clusterId;

    public Output<String> clusterId() {
        return this.clusterId;
    }

    @Import(name="id")
    private @Nullable Output<String> id;

    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    private GetAccountsDatabaseApiKeysV2Args() {}

    private GetAccountsDatabaseApiKeysV2Args(GetAccountsDatabaseApiKeysV2Args $) {
        this.accountId = $.accountId;
        this.clusterId = $.clusterId;
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAccountsDatabaseApiKeysV2Args defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAccountsDatabaseApiKeysV2Args $;

        public Builder() {
            $ = new GetAccountsDatabaseApiKeysV2Args();
        }

        public Builder(GetAccountsDatabaseApiKeysV2Args defaults) {
            $ = new GetAccountsDatabaseApiKeysV2Args(Objects.requireNonNull(defaults));
        }

        public Builder accountId(@Nullable Output<String> accountId) {
            $.accountId = accountId;
            return this;
        }

        public Builder accountId(String accountId) {
            return accountId(Output.of(accountId));
        }

        public Builder clusterId(Output<String> clusterId) {
            $.clusterId = clusterId;
            return this;
        }

        public Builder clusterId(String clusterId) {
            return clusterId(Output.of(clusterId));
        }

        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        public Builder id(String id) {
            return id(Output.of(id));
        }

        public GetAccountsDatabaseApiKeysV2Args build() {
            if ($.clusterId == null) {
                throw new MissingRequiredPropertyException("GetAccountsDatabaseApiKeysV2Args", "clusterId");
            }
            return $;
        }
    }

}
