// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAccountsBackupSchedulePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAccountsBackupSchedulePlainArgs Empty = new GetAccountsBackupSchedulePlainArgs();

    @Import(name="clusterId", required=true)
    private String clusterId;

    public String clusterId() {
        return this.clusterId;
    }

    @Import(name="deleteBackupsOnDestroy")
    private @Nullable Boolean deleteBackupsOnDestroy;

    public Optional<Boolean> deleteBackupsOnDestroy() {
        return Optional.ofNullable(this.deleteBackupsOnDestroy);
    }

    @Import(name="id", required=true)
    private String id;

    public String id() {
        return this.id;
    }

    private GetAccountsBackupSchedulePlainArgs() {}

    private GetAccountsBackupSchedulePlainArgs(GetAccountsBackupSchedulePlainArgs $) {
        this.clusterId = $.clusterId;
        this.deleteBackupsOnDestroy = $.deleteBackupsOnDestroy;
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAccountsBackupSchedulePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAccountsBackupSchedulePlainArgs $;

        public Builder() {
            $ = new GetAccountsBackupSchedulePlainArgs();
        }

        public Builder(GetAccountsBackupSchedulePlainArgs defaults) {
            $ = new GetAccountsBackupSchedulePlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder clusterId(String clusterId) {
            $.clusterId = clusterId;
            return this;
        }

        public Builder deleteBackupsOnDestroy(@Nullable Boolean deleteBackupsOnDestroy) {
            $.deleteBackupsOnDestroy = deleteBackupsOnDestroy;
            return this;
        }

        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetAccountsBackupSchedulePlainArgs build() {
            if ($.clusterId == null) {
                throw new MissingRequiredPropertyException("GetAccountsBackupSchedulePlainArgs", "clusterId");
            }
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetAccountsBackupSchedulePlainArgs", "id");
            }
            return $;
        }
    }

}
