// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetBookingPackagesArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetBookingPackagesArgs Empty = new GetBookingPackagesArgs();

    @Import(name="cloudProvider", required=true)
    private Output<String> cloudProvider;

    public Output<String> cloudProvider() {
        return this.cloudProvider;
    }

    @Import(name="cloudRegion", required=true)
    private Output<String> cloudRegion;

    public Output<String> cloudRegion() {
        return this.cloudRegion;
    }

    @Import(name="id")
    private @Nullable Output<String> id;

    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    private GetBookingPackagesArgs() {}

    private GetBookingPackagesArgs(GetBookingPackagesArgs $) {
        this.cloudProvider = $.cloudProvider;
        this.cloudRegion = $.cloudRegion;
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetBookingPackagesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetBookingPackagesArgs $;

        public Builder() {
            $ = new GetBookingPackagesArgs();
        }

        public Builder(GetBookingPackagesArgs defaults) {
            $ = new GetBookingPackagesArgs(Objects.requireNonNull(defaults));
        }

        public Builder cloudProvider(Output<String> cloudProvider) {
            $.cloudProvider = cloudProvider;
            return this;
        }

        public Builder cloudProvider(String cloudProvider) {
            return cloudProvider(Output.of(cloudProvider));
        }

        public Builder cloudRegion(Output<String> cloudRegion) {
            $.cloudRegion = cloudRegion;
            return this;
        }

        public Builder cloudRegion(String cloudRegion) {
            return cloudRegion(Output.of(cloudRegion));
        }

        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        public Builder id(String id) {
            return id(Output.of(id));
        }

        public GetBookingPackagesArgs build() {
            if ($.cloudProvider == null) {
                throw new MissingRequiredPropertyException("GetBookingPackagesArgs", "cloudProvider");
            }
            if ($.cloudRegion == null) {
                throw new MissingRequiredPropertyException("GetBookingPackagesArgs", "cloudRegion");
            }
            return $;
        }
    }

}
