// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ServerlessSpaceApiKeyCollectionAccessRuleArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServerlessSpaceApiKeyCollectionAccessRuleArgs Empty = new ServerlessSpaceApiKeyCollectionAccessRuleArgs();

    /**
     * Access type for the collection. Must be one of: COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_ONLY, COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_WRITE.
     * 
     */
    @Import(name="accessType", required=true)
    private Output<String> accessType;

    /**
     * @return Access type for the collection. Must be one of: COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_ONLY, COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_WRITE.
     * 
     */
    public Output<String> accessType() {
        return this.accessType;
    }

    /**
     * Name of the collection.
     * 
     */
    @Import(name="collectionName", required=true)
    private Output<String> collectionName;

    /**
     * @return Name of the collection.
     * 
     */
    public Output<String> collectionName() {
        return this.collectionName;
    }

    private ServerlessSpaceApiKeyCollectionAccessRuleArgs() {}

    private ServerlessSpaceApiKeyCollectionAccessRuleArgs(ServerlessSpaceApiKeyCollectionAccessRuleArgs $) {
        this.accessType = $.accessType;
        this.collectionName = $.collectionName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServerlessSpaceApiKeyCollectionAccessRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServerlessSpaceApiKeyCollectionAccessRuleArgs $;

        public Builder() {
            $ = new ServerlessSpaceApiKeyCollectionAccessRuleArgs();
        }

        public Builder(ServerlessSpaceApiKeyCollectionAccessRuleArgs defaults) {
            $ = new ServerlessSpaceApiKeyCollectionAccessRuleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessType Access type for the collection. Must be one of: COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_ONLY, COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_WRITE.
         * 
         * @return builder
         * 
         */
        public Builder accessType(Output<String> accessType) {
            $.accessType = accessType;
            return this;
        }

        /**
         * @param accessType Access type for the collection. Must be one of: COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_ONLY, COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_WRITE.
         * 
         * @return builder
         * 
         */
        public Builder accessType(String accessType) {
            return accessType(Output.of(accessType));
        }

        /**
         * @param collectionName Name of the collection.
         * 
         * @return builder
         * 
         */
        public Builder collectionName(Output<String> collectionName) {
            $.collectionName = collectionName;
            return this;
        }

        /**
         * @param collectionName Name of the collection.
         * 
         * @return builder
         * 
         */
        public Builder collectionName(String collectionName) {
            return collectionName(Output.of(collectionName));
        }

        public ServerlessSpaceApiKeyCollectionAccessRuleArgs build() {
            if ($.accessType == null) {
                throw new MissingRequiredPropertyException("ServerlessSpaceApiKeyCollectionAccessRuleArgs", "accessType");
            }
            if ($.collectionName == null) {
                throw new MissingRequiredPropertyException("ServerlessSpaceApiKeyCollectionAccessRuleArgs", "collectionName");
            }
            return $;
        }
    }

}
