// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Double;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServerlessSpaceConfigurationCollectionSettingsArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServerlessSpaceConfigurationCollectionSettingsArgs Empty = new ServerlessSpaceConfigurationCollectionSettingsArgs();

    /**
     * Customer-defined maximum size in bytes per collection, used for cost control. Must not exceed &lt;span pulumi-lang-nodejs=&#34;`platformMaxSize`&#34; pulumi-lang-dotnet=&#34;`PlatformMaxSize`&#34; pulumi-lang-go=&#34;`platformMaxSize`&#34; pulumi-lang-python=&#34;`platform_max_size`&#34; pulumi-lang-yaml=&#34;`platformMaxSize`&#34; pulumi-lang-java=&#34;`platformMaxSize`&#34; pulumi-lang-hcl=&#34;`platform_max_size`&#34;&gt;`platformMaxSize`&lt;/span&gt;.
     * 
     */
    @Import(name="maxSize")
    private @Nullable Output<Double> maxSize;

    /**
     * @return Customer-defined maximum size in bytes per collection, used for cost control. Must not exceed &lt;span pulumi-lang-nodejs=&#34;`platformMaxSize`&#34; pulumi-lang-dotnet=&#34;`PlatformMaxSize`&#34; pulumi-lang-go=&#34;`platformMaxSize`&#34; pulumi-lang-python=&#34;`platform_max_size`&#34; pulumi-lang-yaml=&#34;`platformMaxSize`&#34; pulumi-lang-java=&#34;`platformMaxSize`&#34; pulumi-lang-hcl=&#34;`platform_max_size`&#34;&gt;`platformMaxSize`&lt;/span&gt;.
     * 
     */
    public Optional<Output<Double>> maxSize() {
        return Optional.ofNullable(this.maxSize);
    }

    /**
     * Platform-enforced maximum size in bytes per collection (0 means unlimited).
     * 
     */
    @Import(name="platformMaxSize")
    private @Nullable Output<Double> platformMaxSize;

    /**
     * @return Platform-enforced maximum size in bytes per collection (0 means unlimited).
     * 
     */
    public Optional<Output<Double>> platformMaxSize() {
        return Optional.ofNullable(this.platformMaxSize);
    }

    private ServerlessSpaceConfigurationCollectionSettingsArgs() {}

    private ServerlessSpaceConfigurationCollectionSettingsArgs(ServerlessSpaceConfigurationCollectionSettingsArgs $) {
        this.maxSize = $.maxSize;
        this.platformMaxSize = $.platformMaxSize;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServerlessSpaceConfigurationCollectionSettingsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServerlessSpaceConfigurationCollectionSettingsArgs $;

        public Builder() {
            $ = new ServerlessSpaceConfigurationCollectionSettingsArgs();
        }

        public Builder(ServerlessSpaceConfigurationCollectionSettingsArgs defaults) {
            $ = new ServerlessSpaceConfigurationCollectionSettingsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param maxSize Customer-defined maximum size in bytes per collection, used for cost control. Must not exceed &lt;span pulumi-lang-nodejs=&#34;`platformMaxSize`&#34; pulumi-lang-dotnet=&#34;`PlatformMaxSize`&#34; pulumi-lang-go=&#34;`platformMaxSize`&#34; pulumi-lang-python=&#34;`platform_max_size`&#34; pulumi-lang-yaml=&#34;`platformMaxSize`&#34; pulumi-lang-java=&#34;`platformMaxSize`&#34; pulumi-lang-hcl=&#34;`platform_max_size`&#34;&gt;`platformMaxSize`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder maxSize(@Nullable Output<Double> maxSize) {
            $.maxSize = maxSize;
            return this;
        }

        /**
         * @param maxSize Customer-defined maximum size in bytes per collection, used for cost control. Must not exceed &lt;span pulumi-lang-nodejs=&#34;`platformMaxSize`&#34; pulumi-lang-dotnet=&#34;`PlatformMaxSize`&#34; pulumi-lang-go=&#34;`platformMaxSize`&#34; pulumi-lang-python=&#34;`platform_max_size`&#34; pulumi-lang-yaml=&#34;`platformMaxSize`&#34; pulumi-lang-java=&#34;`platformMaxSize`&#34; pulumi-lang-hcl=&#34;`platform_max_size`&#34;&gt;`platformMaxSize`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder maxSize(Double maxSize) {
            return maxSize(Output.of(maxSize));
        }

        /**
         * @param platformMaxSize Platform-enforced maximum size in bytes per collection (0 means unlimited).
         * 
         * @return builder
         * 
         */
        public Builder platformMaxSize(@Nullable Output<Double> platformMaxSize) {
            $.platformMaxSize = platformMaxSize;
            return this;
        }

        /**
         * @param platformMaxSize Platform-enforced maximum size in bytes per collection (0 means unlimited).
         * 
         * @return builder
         * 
         */
        public Builder platformMaxSize(Double platformMaxSize) {
            return platformMaxSize(Output.of(platformMaxSize));
        }

        public ServerlessSpaceConfigurationCollectionSettingsArgs build() {
            return $;
        }
    }

}
