// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qdrantcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.qdrantcloud.inputs.ServerlessBackupStatArgs;
import com.pulumi.qdrantcloud.inputs.ServerlessBackupTimeoutsArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServerlessBackupState extends com.pulumi.resources.ResourceArgs {

    public static final ServerlessBackupState Empty = new ServerlessBackupState();

    /**
     * Serverless Backup Schema Account ID (defaults to the provider account ID) field
     * 
     */
    @Import(name="accountId")
    private @Nullable Output<String> accountId;

    /**
     * @return Serverless Backup Schema Account ID (defaults to the provider account ID) field
     * 
     */
    public Optional<Output<String>> accountId() {
        return Optional.ofNullable(this.accountId);
    }

    /**
     * Serverless Backup Schema ID of the backup schedule that created the backup (empty for manual backups) field
     * 
     */
    @Import(name="backupScheduleId")
    private @Nullable Output<String> backupScheduleId;

    /**
     * @return Serverless Backup Schema ID of the backup schedule that created the backup (empty for manual backups) field
     * 
     */
    public Optional<Output<String>> backupScheduleId() {
        return Optional.ofNullable(this.backupScheduleId);
    }

    /**
     * Serverless Backup Schema Name of the collection to back up. If unset, the entire space is backed up field
     * 
     */
    @Import(name="collectionName")
    private @Nullable Output<String> collectionName;

    /**
     * @return Serverless Backup Schema Name of the collection to back up. If unset, the entire space is backed up field
     * 
     */
    public Optional<Output<String>> collectionName() {
        return Optional.ofNullable(this.collectionName);
    }

    /**
     * Serverless Backup Schema Creation time field
     * 
     */
    @Import(name="createdAt")
    private @Nullable Output<String> createdAt;

    /**
     * @return Serverless Backup Schema Creation time field
     * 
     */
    public Optional<Output<String>> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    /**
     * Serverless Backup Schema Name of the backup (generated) field
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Serverless Backup Schema Name of the backup (generated) field
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Serverless Backup Schema Retention period of the backup, as a Go duration string between &lt;span pulumi-lang-nodejs=&#34;`24h`&#34; pulumi-lang-dotnet=&#34;`24h`&#34; pulumi-lang-go=&#34;`24h`&#34; pulumi-lang-python=&#34;`24h`&#34; pulumi-lang-yaml=&#34;`24h`&#34; pulumi-lang-java=&#34;`24h`&#34; pulumi-lang-hcl=&#34;`24h`&#34;&gt;`24h`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`8760h`&#34; pulumi-lang-dotnet=&#34;`8760h`&#34; pulumi-lang-go=&#34;`8760h`&#34; pulumi-lang-python=&#34;`8760h`&#34; pulumi-lang-yaml=&#34;`8760h`&#34; pulumi-lang-java=&#34;`8760h`&#34; pulumi-lang-hcl=&#34;`8760h`&#34;&gt;`8760h`&lt;/span&gt;. If unset, the backup is retained indefinitely field
     * 
     */
    @Import(name="retentionPeriod")
    private @Nullable Output<String> retentionPeriod;

    /**
     * @return Serverless Backup Schema Retention period of the backup, as a Go duration string between &lt;span pulumi-lang-nodejs=&#34;`24h`&#34; pulumi-lang-dotnet=&#34;`24h`&#34; pulumi-lang-go=&#34;`24h`&#34; pulumi-lang-python=&#34;`24h`&#34; pulumi-lang-yaml=&#34;`24h`&#34; pulumi-lang-java=&#34;`24h`&#34; pulumi-lang-hcl=&#34;`24h`&#34;&gt;`24h`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`8760h`&#34; pulumi-lang-dotnet=&#34;`8760h`&#34; pulumi-lang-go=&#34;`8760h`&#34; pulumi-lang-python=&#34;`8760h`&#34; pulumi-lang-yaml=&#34;`8760h`&#34; pulumi-lang-java=&#34;`8760h`&#34; pulumi-lang-hcl=&#34;`8760h`&#34;&gt;`8760h`&lt;/span&gt;. If unset, the backup is retained indefinitely field
     * 
     */
    public Optional<Output<String>> retentionPeriod() {
        return Optional.ofNullable(this.retentionPeriod);
    }

    /**
     * Serverless Backup Schema ID of the serverless space to back up field
     * 
     */
    @Import(name="spaceId")
    private @Nullable Output<String> spaceId;

    /**
     * @return Serverless Backup Schema ID of the serverless space to back up field
     * 
     */
    public Optional<Output<String>> spaceId() {
        return Optional.ofNullable(this.spaceId);
    }

    /**
     * Serverless Backup Schema Statistics of the backup field
     * 
     */
    @Import(name="stats")
    private @Nullable Output<List<ServerlessBackupStatArgs>> stats;

    /**
     * @return Serverless Backup Schema Statistics of the backup field
     * 
     */
    public Optional<Output<List<ServerlessBackupStatArgs>>> stats() {
        return Optional.ofNullable(this.stats);
    }

    /**
     * Serverless Backup Schema Current status of the backup field
     * 
     */
    @Import(name="status")
    private @Nullable Output<String> status;

    /**
     * @return Serverless Backup Schema Current status of the backup field
     * 
     */
    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    @Import(name="timeouts")
    private @Nullable Output<ServerlessBackupTimeoutsArgs> timeouts;

    public Optional<Output<ServerlessBackupTimeoutsArgs>> timeouts() {
        return Optional.ofNullable(this.timeouts);
    }

    private ServerlessBackupState() {}

    private ServerlessBackupState(ServerlessBackupState $) {
        this.accountId = $.accountId;
        this.backupScheduleId = $.backupScheduleId;
        this.collectionName = $.collectionName;
        this.createdAt = $.createdAt;
        this.name = $.name;
        this.retentionPeriod = $.retentionPeriod;
        this.spaceId = $.spaceId;
        this.stats = $.stats;
        this.status = $.status;
        this.timeouts = $.timeouts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServerlessBackupState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServerlessBackupState $;

        public Builder() {
            $ = new ServerlessBackupState();
        }

        public Builder(ServerlessBackupState defaults) {
            $ = new ServerlessBackupState(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountId Serverless Backup Schema Account ID (defaults to the provider account ID) field
         * 
         * @return builder
         * 
         */
        public Builder accountId(@Nullable Output<String> accountId) {
            $.accountId = accountId;
            return this;
        }

        /**
         * @param accountId Serverless Backup Schema Account ID (defaults to the provider account ID) field
         * 
         * @return builder
         * 
         */
        public Builder accountId(String accountId) {
            return accountId(Output.of(accountId));
        }

        /**
         * @param backupScheduleId Serverless Backup Schema ID of the backup schedule that created the backup (empty for manual backups) field
         * 
         * @return builder
         * 
         */
        public Builder backupScheduleId(@Nullable Output<String> backupScheduleId) {
            $.backupScheduleId = backupScheduleId;
            return this;
        }

        /**
         * @param backupScheduleId Serverless Backup Schema ID of the backup schedule that created the backup (empty for manual backups) field
         * 
         * @return builder
         * 
         */
        public Builder backupScheduleId(String backupScheduleId) {
            return backupScheduleId(Output.of(backupScheduleId));
        }

        /**
         * @param collectionName Serverless Backup Schema Name of the collection to back up. If unset, the entire space is backed up field
         * 
         * @return builder
         * 
         */
        public Builder collectionName(@Nullable Output<String> collectionName) {
            $.collectionName = collectionName;
            return this;
        }

        /**
         * @param collectionName Serverless Backup Schema Name of the collection to back up. If unset, the entire space is backed up field
         * 
         * @return builder
         * 
         */
        public Builder collectionName(String collectionName) {
            return collectionName(Output.of(collectionName));
        }

        /**
         * @param createdAt Serverless Backup Schema Creation time field
         * 
         * @return builder
         * 
         */
        public Builder createdAt(@Nullable Output<String> createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        /**
         * @param createdAt Serverless Backup Schema Creation time field
         * 
         * @return builder
         * 
         */
        public Builder createdAt(String createdAt) {
            return createdAt(Output.of(createdAt));
        }

        /**
         * @param name Serverless Backup Schema Name of the backup (generated) field
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Serverless Backup Schema Name of the backup (generated) field
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param retentionPeriod Serverless Backup Schema Retention period of the backup, as a Go duration string between &lt;span pulumi-lang-nodejs=&#34;`24h`&#34; pulumi-lang-dotnet=&#34;`24h`&#34; pulumi-lang-go=&#34;`24h`&#34; pulumi-lang-python=&#34;`24h`&#34; pulumi-lang-yaml=&#34;`24h`&#34; pulumi-lang-java=&#34;`24h`&#34; pulumi-lang-hcl=&#34;`24h`&#34;&gt;`24h`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`8760h`&#34; pulumi-lang-dotnet=&#34;`8760h`&#34; pulumi-lang-go=&#34;`8760h`&#34; pulumi-lang-python=&#34;`8760h`&#34; pulumi-lang-yaml=&#34;`8760h`&#34; pulumi-lang-java=&#34;`8760h`&#34; pulumi-lang-hcl=&#34;`8760h`&#34;&gt;`8760h`&lt;/span&gt;. If unset, the backup is retained indefinitely field
         * 
         * @return builder
         * 
         */
        public Builder retentionPeriod(@Nullable Output<String> retentionPeriod) {
            $.retentionPeriod = retentionPeriod;
            return this;
        }

        /**
         * @param retentionPeriod Serverless Backup Schema Retention period of the backup, as a Go duration string between &lt;span pulumi-lang-nodejs=&#34;`24h`&#34; pulumi-lang-dotnet=&#34;`24h`&#34; pulumi-lang-go=&#34;`24h`&#34; pulumi-lang-python=&#34;`24h`&#34; pulumi-lang-yaml=&#34;`24h`&#34; pulumi-lang-java=&#34;`24h`&#34; pulumi-lang-hcl=&#34;`24h`&#34;&gt;`24h`&lt;/span&gt; and &lt;span pulumi-lang-nodejs=&#34;`8760h`&#34; pulumi-lang-dotnet=&#34;`8760h`&#34; pulumi-lang-go=&#34;`8760h`&#34; pulumi-lang-python=&#34;`8760h`&#34; pulumi-lang-yaml=&#34;`8760h`&#34; pulumi-lang-java=&#34;`8760h`&#34; pulumi-lang-hcl=&#34;`8760h`&#34;&gt;`8760h`&lt;/span&gt;. If unset, the backup is retained indefinitely field
         * 
         * @return builder
         * 
         */
        public Builder retentionPeriod(String retentionPeriod) {
            return retentionPeriod(Output.of(retentionPeriod));
        }

        /**
         * @param spaceId Serverless Backup Schema ID of the serverless space to back up field
         * 
         * @return builder
         * 
         */
        public Builder spaceId(@Nullable Output<String> spaceId) {
            $.spaceId = spaceId;
            return this;
        }

        /**
         * @param spaceId Serverless Backup Schema ID of the serverless space to back up field
         * 
         * @return builder
         * 
         */
        public Builder spaceId(String spaceId) {
            return spaceId(Output.of(spaceId));
        }

        /**
         * @param stats Serverless Backup Schema Statistics of the backup field
         * 
         * @return builder
         * 
         */
        public Builder stats(@Nullable Output<List<ServerlessBackupStatArgs>> stats) {
            $.stats = stats;
            return this;
        }

        /**
         * @param stats Serverless Backup Schema Statistics of the backup field
         * 
         * @return builder
         * 
         */
        public Builder stats(List<ServerlessBackupStatArgs> stats) {
            return stats(Output.of(stats));
        }

        /**
         * @param stats Serverless Backup Schema Statistics of the backup field
         * 
         * @return builder
         * 
         */
        public Builder stats(ServerlessBackupStatArgs... stats) {
            return stats(List.of(stats));
        }

        /**
         * @param status Serverless Backup Schema Current status of the backup field
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status Serverless Backup Schema Current status of the backup field
         * 
         * @return builder
         * 
         */
        public Builder status(String status) {
            return status(Output.of(status));
        }

        public Builder timeouts(@Nullable Output<ServerlessBackupTimeoutsArgs> timeouts) {
            $.timeouts = timeouts;
            return this;
        }

        public Builder timeouts(ServerlessBackupTimeoutsArgs timeouts) {
            return timeouts(Output.of(timeouts));
        }

        public ServerlessBackupState build() {
            return $;
        }
    }

}
