# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetAccountsRolesResult',
    'AwaitableGetAccountsRolesResult',
    'get_accounts_roles',
    'get_accounts_roles_output',
]

@pulumi.output_type
class GetAccountsRolesResult:
    """
    A collection of values returned by getAccountsRoles.
    """
    def __init__(__self__, account_id=None, id=None, roles=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if roles and not isinstance(roles, list):
            raise TypeError("Expected argument 'roles' to be a list")
        pulumi.set(__self__, "roles", roles)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> _builtins.str:
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def roles(self) -> Sequence['outputs.GetAccountsRolesRoleResult']:
        return pulumi.get(self, "roles")


class AwaitableGetAccountsRolesResult(GetAccountsRolesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAccountsRolesResult(
            account_id=self.account_id,
            id=self.id,
            roles=self.roles)


def get_accounts_roles(account_id: Optional[_builtins.str] = None,
                       id: Optional[_builtins.str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAccountsRolesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('qdrant-cloud:index/getAccountsRoles:getAccountsRoles', __args__, opts=opts, typ=GetAccountsRolesResult, package_ref=_utilities.get_package()).value

    return AwaitableGetAccountsRolesResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        id=pulumi.get(__ret__, 'id'),
        roles=pulumi.get(__ret__, 'roles'))
def get_accounts_roles_output(account_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                              id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAccountsRolesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('qdrant-cloud:index/getAccountsRoles:getAccountsRoles', __args__, opts=opts, typ=GetAccountsRolesResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetAccountsRolesResult(
        account_id=pulumi.get(__response__, 'account_id'),
        id=pulumi.get(__response__, 'id'),
        roles=pulumi.get(__response__, 'roles')))
