// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package qdrantcloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/qdrant-cloud/qdrant-cloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AccountsBackupSchedule struct {
	pulumi.CustomResourceState

	// Backup Schedule Schema Account ID field
	AccountId pulumi.StringOutput `pulumi:"accountId"`
	// Backup Schedule Schema Cluster ID field
	ClusterId pulumi.StringOutput `pulumi:"clusterId"`
	// Backup Schedule Schema Creation time field
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Backup Schedule Schema Cron expression for the schedule field
	CronExpression pulumi.StringOutput `pulumi:"cronExpression"`
	// Whether to delete backups when the schedule is destroyed.
	DeleteBackupsOnDestroy pulumi.BoolPtrOutput `pulumi:"deleteBackupsOnDestroy"`
	// Backup Schedule Schema Deletion time field
	DeletedAt pulumi.StringOutput `pulumi:"deletedAt"`
	// Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
	RetentionPeriod pulumi.StringPtrOutput `pulumi:"retentionPeriod"`
	// Backup Schedule Schema Status field
	Status pulumi.StringOutput `pulumi:"status"`
}

// NewAccountsBackupSchedule registers a new resource with the given unique name, arguments, and options.
func NewAccountsBackupSchedule(ctx *pulumi.Context,
	name string, args *AccountsBackupScheduleArgs, opts ...pulumi.ResourceOption) (*AccountsBackupSchedule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterId == nil {
		return nil, errors.New("invalid value for required argument 'ClusterId'")
	}
	if args.CronExpression == nil {
		return nil, errors.New("invalid value for required argument 'CronExpression'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource AccountsBackupSchedule
	err = ctx.RegisterPackageResource("qdrant-cloud:index/accountsBackupSchedule:AccountsBackupSchedule", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAccountsBackupSchedule gets an existing AccountsBackupSchedule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAccountsBackupSchedule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AccountsBackupScheduleState, opts ...pulumi.ResourceOption) (*AccountsBackupSchedule, error) {
	var resource AccountsBackupSchedule
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("qdrant-cloud:index/accountsBackupSchedule:AccountsBackupSchedule", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AccountsBackupSchedule resources.
type accountsBackupScheduleState struct {
	// Backup Schedule Schema Account ID field
	AccountId *string `pulumi:"accountId"`
	// Backup Schedule Schema Cluster ID field
	ClusterId *string `pulumi:"clusterId"`
	// Backup Schedule Schema Creation time field
	CreatedAt *string `pulumi:"createdAt"`
	// Backup Schedule Schema Cron expression for the schedule field
	CronExpression *string `pulumi:"cronExpression"`
	// Whether to delete backups when the schedule is destroyed.
	DeleteBackupsOnDestroy *bool `pulumi:"deleteBackupsOnDestroy"`
	// Backup Schedule Schema Deletion time field
	DeletedAt *string `pulumi:"deletedAt"`
	// Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
	RetentionPeriod *string `pulumi:"retentionPeriod"`
	// Backup Schedule Schema Status field
	Status *string `pulumi:"status"`
}

type AccountsBackupScheduleState struct {
	// Backup Schedule Schema Account ID field
	AccountId pulumi.StringPtrInput
	// Backup Schedule Schema Cluster ID field
	ClusterId pulumi.StringPtrInput
	// Backup Schedule Schema Creation time field
	CreatedAt pulumi.StringPtrInput
	// Backup Schedule Schema Cron expression for the schedule field
	CronExpression pulumi.StringPtrInput
	// Whether to delete backups when the schedule is destroyed.
	DeleteBackupsOnDestroy pulumi.BoolPtrInput
	// Backup Schedule Schema Deletion time field
	DeletedAt pulumi.StringPtrInput
	// Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
	RetentionPeriod pulumi.StringPtrInput
	// Backup Schedule Schema Status field
	Status pulumi.StringPtrInput
}

func (AccountsBackupScheduleState) ElementType() reflect.Type {
	return reflect.TypeOf((*accountsBackupScheduleState)(nil)).Elem()
}

type accountsBackupScheduleArgs struct {
	// Backup Schedule Schema Account ID field
	AccountId *string `pulumi:"accountId"`
	// Backup Schedule Schema Cluster ID field
	ClusterId string `pulumi:"clusterId"`
	// Backup Schedule Schema Cron expression for the schedule field
	CronExpression string `pulumi:"cronExpression"`
	// Whether to delete backups when the schedule is destroyed.
	DeleteBackupsOnDestroy *bool `pulumi:"deleteBackupsOnDestroy"`
	// Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
	RetentionPeriod *string `pulumi:"retentionPeriod"`
}

// The set of arguments for constructing a AccountsBackupSchedule resource.
type AccountsBackupScheduleArgs struct {
	// Backup Schedule Schema Account ID field
	AccountId pulumi.StringPtrInput
	// Backup Schedule Schema Cluster ID field
	ClusterId pulumi.StringInput
	// Backup Schedule Schema Cron expression for the schedule field
	CronExpression pulumi.StringInput
	// Whether to delete backups when the schedule is destroyed.
	DeleteBackupsOnDestroy pulumi.BoolPtrInput
	// Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
	RetentionPeriod pulumi.StringPtrInput
}

func (AccountsBackupScheduleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*accountsBackupScheduleArgs)(nil)).Elem()
}

type AccountsBackupScheduleInput interface {
	pulumi.Input

	ToAccountsBackupScheduleOutput() AccountsBackupScheduleOutput
	ToAccountsBackupScheduleOutputWithContext(ctx context.Context) AccountsBackupScheduleOutput
}

func (*AccountsBackupSchedule) ElementType() reflect.Type {
	return reflect.TypeOf((**AccountsBackupSchedule)(nil)).Elem()
}

func (i *AccountsBackupSchedule) ToAccountsBackupScheduleOutput() AccountsBackupScheduleOutput {
	return i.ToAccountsBackupScheduleOutputWithContext(context.Background())
}

func (i *AccountsBackupSchedule) ToAccountsBackupScheduleOutputWithContext(ctx context.Context) AccountsBackupScheduleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountsBackupScheduleOutput)
}

type AccountsBackupScheduleOutput struct{ *pulumi.OutputState }

func (AccountsBackupScheduleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AccountsBackupSchedule)(nil)).Elem()
}

func (o AccountsBackupScheduleOutput) ToAccountsBackupScheduleOutput() AccountsBackupScheduleOutput {
	return o
}

func (o AccountsBackupScheduleOutput) ToAccountsBackupScheduleOutputWithContext(ctx context.Context) AccountsBackupScheduleOutput {
	return o
}

// Backup Schedule Schema Account ID field
func (o AccountsBackupScheduleOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *AccountsBackupSchedule) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

// Backup Schedule Schema Cluster ID field
func (o AccountsBackupScheduleOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v *AccountsBackupSchedule) pulumi.StringOutput { return v.ClusterId }).(pulumi.StringOutput)
}

// Backup Schedule Schema Creation time field
func (o AccountsBackupScheduleOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *AccountsBackupSchedule) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Backup Schedule Schema Cron expression for the schedule field
func (o AccountsBackupScheduleOutput) CronExpression() pulumi.StringOutput {
	return o.ApplyT(func(v *AccountsBackupSchedule) pulumi.StringOutput { return v.CronExpression }).(pulumi.StringOutput)
}

// Whether to delete backups when the schedule is destroyed.
func (o AccountsBackupScheduleOutput) DeleteBackupsOnDestroy() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AccountsBackupSchedule) pulumi.BoolPtrOutput { return v.DeleteBackupsOnDestroy }).(pulumi.BoolPtrOutput)
}

// Backup Schedule Schema Deletion time field
func (o AccountsBackupScheduleOutput) DeletedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *AccountsBackupSchedule) pulumi.StringOutput { return v.DeletedAt }).(pulumi.StringOutput)
}

// Backup Schedule Schema Retention period as a Go duration string (e.g., "72h"). field
func (o AccountsBackupScheduleOutput) RetentionPeriod() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AccountsBackupSchedule) pulumi.StringPtrOutput { return v.RetentionPeriod }).(pulumi.StringPtrOutput)
}

// Backup Schedule Schema Status field
func (o AccountsBackupScheduleOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *AccountsBackupSchedule) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AccountsBackupScheduleInput)(nil)).Elem(), &AccountsBackupSchedule{})
	pulumi.RegisterOutputType(AccountsBackupScheduleOutput{})
}
