// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package qdrantcloud

import (
	"context"
	"reflect"

	"github.com/gvtlabs/pulumi-qdrant-cloud/sdks/go/qdrant-cloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetServerlessBackups(ctx *pulumi.Context, args *GetServerlessBackupsArgs, opts ...pulumi.InvokeOption) (*GetServerlessBackupsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetServerlessBackupsResult
	err = ctx.InvokePackage("qdrant-cloud:index/getServerlessBackups:getServerlessBackups", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServerlessBackups.
type GetServerlessBackupsArgs struct {
	AccountId        *string `pulumi:"accountId"`
	BackupScheduleId *string `pulumi:"backupScheduleId"`
	CollectionName   *string `pulumi:"collectionName"`
	Id               *string `pulumi:"id"`
	SpaceId          *string `pulumi:"spaceId"`
}

// A collection of values returned by getServerlessBackups.
type GetServerlessBackupsResult struct {
	AccountId        string                       `pulumi:"accountId"`
	BackupScheduleId *string                      `pulumi:"backupScheduleId"`
	Backups          []GetServerlessBackupsBackup `pulumi:"backups"`
	CollectionName   *string                      `pulumi:"collectionName"`
	Id               string                       `pulumi:"id"`
	SpaceId          *string                      `pulumi:"spaceId"`
}

func GetServerlessBackupsOutput(ctx *pulumi.Context, args GetServerlessBackupsOutputArgs, opts ...pulumi.InvokeOption) GetServerlessBackupsResultOutput {
	options := pulumi.InvokeOutputOptions{
		InvokeOptions: internal.PkgInvokeDefaultOpts(opts),
		PackageRefF:   internal.PkgGetPackageRef,
	}
	return ctx.InvokeOutput("qdrant-cloud:index/getServerlessBackups:getServerlessBackups", args, GetServerlessBackupsResultOutput{}, options).(GetServerlessBackupsResultOutput)
}

// A collection of arguments for invoking getServerlessBackups.
type GetServerlessBackupsOutputArgs struct {
	AccountId        pulumi.StringPtrInput `pulumi:"accountId"`
	BackupScheduleId pulumi.StringPtrInput `pulumi:"backupScheduleId"`
	CollectionName   pulumi.StringPtrInput `pulumi:"collectionName"`
	Id               pulumi.StringPtrInput `pulumi:"id"`
	SpaceId          pulumi.StringPtrInput `pulumi:"spaceId"`
}

func (GetServerlessBackupsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServerlessBackupsArgs)(nil)).Elem()
}

// A collection of values returned by getServerlessBackups.
type GetServerlessBackupsResultOutput struct{ *pulumi.OutputState }

func (GetServerlessBackupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServerlessBackupsResult)(nil)).Elem()
}

func (o GetServerlessBackupsResultOutput) ToGetServerlessBackupsResultOutput() GetServerlessBackupsResultOutput {
	return o
}

func (o GetServerlessBackupsResultOutput) ToGetServerlessBackupsResultOutputWithContext(ctx context.Context) GetServerlessBackupsResultOutput {
	return o
}

func (o GetServerlessBackupsResultOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerlessBackupsResult) string { return v.AccountId }).(pulumi.StringOutput)
}

func (o GetServerlessBackupsResultOutput) BackupScheduleId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetServerlessBackupsResult) *string { return v.BackupScheduleId }).(pulumi.StringPtrOutput)
}

func (o GetServerlessBackupsResultOutput) Backups() GetServerlessBackupsBackupArrayOutput {
	return o.ApplyT(func(v GetServerlessBackupsResult) []GetServerlessBackupsBackup { return v.Backups }).(GetServerlessBackupsBackupArrayOutput)
}

func (o GetServerlessBackupsResultOutput) CollectionName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetServerlessBackupsResult) *string { return v.CollectionName }).(pulumi.StringPtrOutput)
}

func (o GetServerlessBackupsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerlessBackupsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetServerlessBackupsResultOutput) SpaceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetServerlessBackupsResult) *string { return v.SpaceId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetServerlessBackupsResultOutput{})
}
