// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class AccountsClusterConfigurationDatabaseConfigurationTlsKey
    {
        /// <summary>
        /// The key within the secret.
        /// </summary>
        public readonly string SecretKey;
        /// <summary>
        /// The name of the secret.
        /// </summary>
        public readonly string SecretName;

        [OutputConstructor]
        private AccountsClusterConfigurationDatabaseConfigurationTlsKey(
            string secretKey,

            string secretName)
        {
            SecretKey = secretKey;
            SecretName = secretName;
        }
    }
}
