// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance
    {
        public readonly bool? AsyncScorer;
        public readonly double? OptimizerCpuBudget;

        [OutputConstructor]
        private AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance(
            bool? asyncScorer,

            double? optimizerCpuBudget)
        {
            AsyncScorer = asyncScorer;
            OptimizerCpuBudget = optimizerCpuBudget;
        }
    }
}
