// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class AccountsClusterStatusResource
    {
        public readonly ImmutableArray<Outputs.AccountsClusterStatusResourceCpus> Cpus;
        public readonly ImmutableArray<Outputs.AccountsClusterStatusResourceDisk> Disks;
        public readonly ImmutableArray<Outputs.AccountsClusterStatusResourceRam> Rams;

        [OutputConstructor]
        private AccountsClusterStatusResource(
            ImmutableArray<Outputs.AccountsClusterStatusResourceCpus> cpus,

            ImmutableArray<Outputs.AccountsClusterStatusResourceDisk> disks,

            ImmutableArray<Outputs.AccountsClusterStatusResourceRam> rams)
        {
            Cpus = cpus;
            Disks = disks;
            Rams = rams;
        }
    }
}
