// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class AccountsClusterConfigurationTopologySpreadConstraint
    {
        public readonly double MaxSkew;
        public readonly string TopologyKey;
        /// <summary>
        /// Action to take when the topology spread constraint cannot be satisfied. Must be one of: TOPOLOGY_SPREAD_CONSTRAINT_WHEN_UNSATISFIABLE_DO_NOT_SCHEDULE, TOPOLOGY_SPREAD_CONSTRAINT_WHEN_UNSATISFIABLE_SCHEDULE_ANYWAY.
        /// </summary>
        public readonly string WhenUnsatisfiable;

        [OutputConstructor]
        private AccountsClusterConfigurationTopologySpreadConstraint(
            double maxSkew,

            string topologyKey,

            string whenUnsatisfiable)
        {
            MaxSkew = maxSkew;
            TopologyKey = topologyKey;
            WhenUnsatisfiable = whenUnsatisfiable;
        }
    }
}
