// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class AccountsHybridCloudEnvironmentStatusStorageClass
    {
        public readonly bool? AllowVolumeExpansion;
        public readonly bool? Default;
        public readonly string? Name;
        public readonly ImmutableDictionary<string, string>? Parameters;
        public readonly string? Provisioner;
        public readonly string? ReclaimPolicy;

        [OutputConstructor]
        private AccountsHybridCloudEnvironmentStatusStorageClass(
            bool? allowVolumeExpansion,

            bool? @default,

            string? name,

            ImmutableDictionary<string, string>? parameters,

            string? provisioner,

            string? reclaimPolicy)
        {
            AllowVolumeExpansion = allowVolumeExpansion;
            Default = @default;
            Name = name;
            Parameters = parameters;
            Provisioner = provisioner;
            ReclaimPolicy = reclaimPolicy;
        }
    }
}
