// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStorage
    {
        public readonly ImmutableArray<Outputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance> Performances;

        [OutputConstructor]
        private AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStorage(ImmutableArray<Outputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance> performances)
        {
            Performances = performances;
        }
    }
}
