// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class GetAccountsClustersClusterResult
    {
        public readonly string? AccountId;
        public readonly string? CloudProvider;
        public readonly string? CloudRegion;
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationResult> Configurations;
        public readonly string? CreatedAt;
        public readonly bool? DeleteBackupsOnDestroy;
        public readonly string? Id;
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterLabelResult> Labels;
        public readonly string? MarkedForDeletionAt;
        public readonly string? Name;
        public readonly string? PrivateRegionId;
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterStatusResult> Statuses;
        public readonly string? Url;

        [OutputConstructor]
        private GetAccountsClustersClusterResult(
            string? accountId,

            string? cloudProvider,

            string? cloudRegion,

            ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationResult> configurations,

            string? createdAt,

            bool? deleteBackupsOnDestroy,

            string? id,

            ImmutableArray<Outputs.GetAccountsClustersClusterLabelResult> labels,

            string? markedForDeletionAt,

            string? name,

            string? privateRegionId,

            ImmutableArray<Outputs.GetAccountsClustersClusterStatusResult> statuses,

            string? url)
        {
            AccountId = accountId;
            CloudProvider = cloudProvider;
            CloudRegion = cloudRegion;
            Configurations = configurations;
            CreatedAt = createdAt;
            DeleteBackupsOnDestroy = deleteBackupsOnDestroy;
            Id = id;
            Labels = labels;
            MarkedForDeletionAt = markedForDeletionAt;
            Name = name;
            PrivateRegionId = privateRegionId;
            Statuses = statuses;
            Url = url;
        }
    }
}
