// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class GetAccountsClusterStatusResourceDiskResult
    {
        public readonly double? Additional;
        public readonly double? Available;
        public readonly double? Base;
        public readonly double? Complimentary;
        public readonly double? Reserved;

        [OutputConstructor]
        private GetAccountsClusterStatusResourceDiskResult(
            double? additional,

            double? available,

            double? @base,

            double? complimentary,

            double? reserved)
        {
            Additional = additional;
            Available = available;
            Base = @base;
            Complimentary = complimentary;
            Reserved = reserved;
        }
    }
}
