// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class GetAccountsClusterConfigurationNodeConfigurationResult
    {
        public readonly string? PackageId;
        public readonly ImmutableArray<Outputs.GetAccountsClusterConfigurationNodeConfigurationResourceConfigurationResult> ResourceConfigurations;

        [OutputConstructor]
        private GetAccountsClusterConfigurationNodeConfigurationResult(
            string? packageId,

            ImmutableArray<Outputs.GetAccountsClusterConfigurationNodeConfigurationResourceConfigurationResult> resourceConfigurations)
        {
            PackageId = packageId;
            ResourceConfigurations = resourceConfigurations;
        }
    }
}
