// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class GetAccountsClustersClusterConfigurationDatabaseConfigurationTlKeyResult
    {
        public readonly string? SecretKey;
        public readonly string? SecretName;

        [OutputConstructor]
        private GetAccountsClustersClusterConfigurationDatabaseConfigurationTlKeyResult(
            string? secretKey,

            string? secretName)
        {
            SecretKey = secretKey;
            SecretName = secretName;
        }
    }
}
