// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class GetAccountsClustersClusterConfigurationDatabaseConfigurationResult
    {
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationAuditLoggingResult> AuditLoggings;
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationCollectionResult> Collections;
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationInferenceResult> Inferences;
        public readonly string? LogLevel;
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationServiceResult> Services;
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationStorageResult> Storages;
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationTlResult> Tls;

        [OutputConstructor]
        private GetAccountsClustersClusterConfigurationDatabaseConfigurationResult(
            ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationAuditLoggingResult> auditLoggings,

            ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationCollectionResult> collections,

            ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationInferenceResult> inferences,

            string? logLevel,

            ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationServiceResult> services,

            ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationStorageResult> storages,

            ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationTlResult> tls)
        {
            AuditLoggings = auditLoggings;
            Collections = collections;
            Inferences = inferences;
            LogLevel = logLevel;
            Services = services;
            Storages = storages;
            Tls = tls;
        }
    }
}
