// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class GetAccountsClustersClusterConfigurationDatabaseConfigurationTlResult
    {
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationTlCertResult> Certs;
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationTlKeyResult> Keys;

        [OutputConstructor]
        private GetAccountsClustersClusterConfigurationDatabaseConfigurationTlResult(
            ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationTlCertResult> certs,

            ImmutableArray<Outputs.GetAccountsClustersClusterConfigurationDatabaseConfigurationTlKeyResult> keys)
        {
            Certs = certs;
            Keys = keys;
        }
    }
}
