// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class GetAccountsClusterStatusCapabilityBackupResult
    {
        public readonly string? Reason;
        public readonly string? Status;

        [OutputConstructor]
        private GetAccountsClusterStatusCapabilityBackupResult(
            string? reason,

            string? status)
        {
            Reason = reason;
            Status = status;
        }
    }
}
