// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud.Outputs
{

    [OutputType]
    public sealed class GetServerlessSpacesSpaceConfigurationResult
    {
        public readonly ImmutableArray<string> AllowedIpSourceRanges;
        public readonly ImmutableArray<string> AllowedOrigins;
        public readonly ImmutableArray<Outputs.GetServerlessSpacesSpaceConfigurationCollectionSettingResult> CollectionSettings;
        public readonly string? LastModifiedAt;
        public readonly double? MaxCollectionsPerSpace;
        public readonly ImmutableArray<Outputs.GetServerlessSpacesSpaceConfigurationSearcherSettingResult> SearcherSettings;

        [OutputConstructor]
        private GetServerlessSpacesSpaceConfigurationResult(
            ImmutableArray<string> allowedIpSourceRanges,

            ImmutableArray<string> allowedOrigins,

            ImmutableArray<Outputs.GetServerlessSpacesSpaceConfigurationCollectionSettingResult> collectionSettings,

            string? lastModifiedAt,

            double? maxCollectionsPerSpace,

            ImmutableArray<Outputs.GetServerlessSpacesSpaceConfigurationSearcherSettingResult> searcherSettings)
        {
            AllowedIpSourceRanges = allowedIpSourceRanges;
            AllowedOrigins = allowedOrigins;
            CollectionSettings = collectionSettings;
            LastModifiedAt = lastModifiedAt;
            MaxCollectionsPerSpace = maxCollectionsPerSpace;
            SearcherSettings = searcherSettings;
        }
    }
}
