// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud
{
    [QdrantCloudResourceType("qdrant-cloud:index/accountsAuthKey:AccountsAuthKey")]
    public partial class AccountsAuthKey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Auth Keys Keys Schema Cluster Identifiers for which this Auth Key is attached field
        /// </summary>
        [Output("clusterIds")]
        public Output<ImmutableArray<string>> ClusterIds { get; private set; } = null!;

        /// <summary>
        /// Auth Keys Keys Schema Timestamp when the Auth Key is created field
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Auth Keys Keys Schema Prefix of the Auth Key (the first few bytes from the token) field
        /// </summary>
        [Output("prefix")]
        public Output<string> Prefix { get; private set; } = null!;

        /// <summary>
        /// Auth Keys Keys Schema Secret token for this Auth Key (handle with care!) field
        /// </summary>
        [Output("token")]
        public Output<string> Token { get; private set; } = null!;


        /// <summary>
        /// Create a AccountsAuthKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AccountsAuthKey(string name, AccountsAuthKeyArgs args, CustomResourceOptions? options = null)
            : base("qdrant-cloud:index/accountsAuthKey:AccountsAuthKey", name, args ?? new AccountsAuthKeyArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private AccountsAuthKey(string name, Input<string> id, AccountsAuthKeyState? state = null, CustomResourceOptions? options = null)
            : base("qdrant-cloud:index/accountsAuthKey:AccountsAuthKey", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AccountsAuthKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AccountsAuthKey Get(string name, Input<string> id, AccountsAuthKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new AccountsAuthKey(name, id, state, options);
        }
    }

    public sealed class AccountsAuthKeyArgs : global::Pulumi.ResourceArgs
    {
        [Input("clusterIds", required: true)]
        private InputList<string>? _clusterIds;

        /// <summary>
        /// Auth Keys Keys Schema Cluster Identifiers for which this Auth Key is attached field
        /// </summary>
        public InputList<string> ClusterIds
        {
            get => _clusterIds ?? (_clusterIds = new InputList<string>());
            set => _clusterIds = value;
        }

        public AccountsAuthKeyArgs()
        {
        }
        public static new AccountsAuthKeyArgs Empty => new AccountsAuthKeyArgs();
    }

    public sealed class AccountsAuthKeyState : global::Pulumi.ResourceArgs
    {
        [Input("clusterIds")]
        private InputList<string>? _clusterIds;

        /// <summary>
        /// Auth Keys Keys Schema Cluster Identifiers for which this Auth Key is attached field
        /// </summary>
        public InputList<string> ClusterIds
        {
            get => _clusterIds ?? (_clusterIds = new InputList<string>());
            set => _clusterIds = value;
        }

        /// <summary>
        /// Auth Keys Keys Schema Timestamp when the Auth Key is created field
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Auth Keys Keys Schema Prefix of the Auth Key (the first few bytes from the token) field
        /// </summary>
        [Input("prefix")]
        public Input<string>? Prefix { get; set; }

        /// <summary>
        /// Auth Keys Keys Schema Secret token for this Auth Key (handle with care!) field
        /// </summary>
        [Input("token")]
        public Input<string>? Token { get; set; }

        public AccountsAuthKeyState()
        {
        }
        public static new AccountsAuthKeyState Empty => new AccountsAuthKeyState();
    }
}
