// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud
{
    [QdrantCloudResourceType("qdrant-cloud:index/accountsRole:AccountsRole")]
    public partial class AccountsRole : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Role Schema Account ID field
        /// </summary>
        [Output("accountId")]
        public Output<string> AccountId { get; private set; } = null!;

        /// <summary>
        /// Role Schema Creation timestamp field
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Role Schema Human-readable description (&lt;=256 chars) field
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Role Schema Last modification timestamp field
        /// </summary>
        [Output("lastModifiedAt")]
        public Output<string> LastModifiedAt { get; private set; } = null!;

        /// <summary>
        /// Role Schema Role name (printable, length 4-64) field
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Permissions assigned to this role (unordered).
        /// </summary>
        [Output("permissions")]
        public Output<ImmutableArray<Outputs.AccountsRolePermission>> Permissions { get; private set; } = null!;

        /// <summary>
        /// Role Schema Role type field
        /// </summary>
        [Output("roleType")]
        public Output<string> RoleType { get; private set; } = null!;

        /// <summary>
        /// Role Schema System role sub-type (if any) field
        /// </summary>
        [Output("subType")]
        public Output<string> SubType { get; private set; } = null!;


        /// <summary>
        /// Create a AccountsRole resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AccountsRole(string name, AccountsRoleArgs args, CustomResourceOptions? options = null)
            : base("qdrant-cloud:index/accountsRole:AccountsRole", name, args ?? new AccountsRoleArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private AccountsRole(string name, Input<string> id, AccountsRoleState? state = null, CustomResourceOptions? options = null)
            : base("qdrant-cloud:index/accountsRole:AccountsRole", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AccountsRole resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AccountsRole Get(string name, Input<string> id, AccountsRoleState? state = null, CustomResourceOptions? options = null)
        {
            return new AccountsRole(name, id, state, options);
        }
    }

    public sealed class AccountsRoleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Role Schema Account ID field
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// Role Schema Human-readable description (&lt;=256 chars) field
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Role Schema Role name (printable, length 4-64) field
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("permissions", required: true)]
        private InputList<Inputs.AccountsRolePermissionArgs>? _permissions;

        /// <summary>
        /// Permissions assigned to this role (unordered).
        /// </summary>
        public InputList<Inputs.AccountsRolePermissionArgs> Permissions
        {
            get => _permissions ?? (_permissions = new InputList<Inputs.AccountsRolePermissionArgs>());
            set => _permissions = value;
        }

        public AccountsRoleArgs()
        {
        }
        public static new AccountsRoleArgs Empty => new AccountsRoleArgs();
    }

    public sealed class AccountsRoleState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Role Schema Account ID field
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// Role Schema Creation timestamp field
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Role Schema Human-readable description (&lt;=256 chars) field
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Role Schema Last modification timestamp field
        /// </summary>
        [Input("lastModifiedAt")]
        public Input<string>? LastModifiedAt { get; set; }

        /// <summary>
        /// Role Schema Role name (printable, length 4-64) field
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("permissions")]
        private InputList<Inputs.AccountsRolePermissionGetArgs>? _permissions;

        /// <summary>
        /// Permissions assigned to this role (unordered).
        /// </summary>
        public InputList<Inputs.AccountsRolePermissionGetArgs> Permissions
        {
            get => _permissions ?? (_permissions = new InputList<Inputs.AccountsRolePermissionGetArgs>());
            set => _permissions = value;
        }

        /// <summary>
        /// Role Schema Role type field
        /// </summary>
        [Input("roleType")]
        public Input<string>? RoleType { get; set; }

        /// <summary>
        /// Role Schema System role sub-type (if any) field
        /// </summary>
        [Input("subType")]
        public Input<string>? SubType { get; set; }

        public AccountsRoleState()
        {
        }
        public static new AccountsRoleState Empty => new AccountsRoleState();
    }
}
