// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud
{
    public static class GetAccountsClusters
    {
        public static Task<GetAccountsClustersResult> InvokeAsync(GetAccountsClustersArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAccountsClustersResult>("qdrant-cloud:index/getAccountsClusters:getAccountsClusters", args ?? new GetAccountsClustersArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetAccountsClustersResult> Invoke(GetAccountsClustersInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountsClustersResult>("qdrant-cloud:index/getAccountsClusters:getAccountsClusters", args ?? new GetAccountsClustersInvokeArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetAccountsClustersResult> Invoke(GetAccountsClustersInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountsClustersResult>("qdrant-cloud:index/getAccountsClusters:getAccountsClusters", args ?? new GetAccountsClustersInvokeArgs(), options.WithDefaults(), Utilities.PackageParameterization());
    }


    public sealed class GetAccountsClustersArgs : global::Pulumi.InvokeArgs
    {
        [Input("accountId")]
        public string? AccountId { get; set; }

        [Input("id")]
        public string? Id { get; set; }

        public GetAccountsClustersArgs()
        {
        }
        public static new GetAccountsClustersArgs Empty => new GetAccountsClustersArgs();
    }

    public sealed class GetAccountsClustersInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        public GetAccountsClustersInvokeArgs()
        {
        }
        public static new GetAccountsClustersInvokeArgs Empty => new GetAccountsClustersInvokeArgs();
    }


    [OutputType]
    public sealed class GetAccountsClustersResult
    {
        public readonly string AccountId;
        public readonly ImmutableArray<Outputs.GetAccountsClustersClusterResult> Clusters;
        public readonly string Id;

        [OutputConstructor]
        private GetAccountsClustersResult(
            string accountId,

            ImmutableArray<Outputs.GetAccountsClustersClusterResult> clusters,

            string id)
        {
            AccountId = accountId;
            Clusters = clusters;
            Id = id;
        }
    }
}
