// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud
{
    public static class GetServerlessBackupSchedules
    {
        public static Task<GetServerlessBackupSchedulesResult> InvokeAsync(GetServerlessBackupSchedulesArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetServerlessBackupSchedulesResult>("qdrant-cloud:index/getServerlessBackupSchedules:getServerlessBackupSchedules", args ?? new GetServerlessBackupSchedulesArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetServerlessBackupSchedulesResult> Invoke(GetServerlessBackupSchedulesInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetServerlessBackupSchedulesResult>("qdrant-cloud:index/getServerlessBackupSchedules:getServerlessBackupSchedules", args ?? new GetServerlessBackupSchedulesInvokeArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetServerlessBackupSchedulesResult> Invoke(GetServerlessBackupSchedulesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetServerlessBackupSchedulesResult>("qdrant-cloud:index/getServerlessBackupSchedules:getServerlessBackupSchedules", args ?? new GetServerlessBackupSchedulesInvokeArgs(), options.WithDefaults(), Utilities.PackageParameterization());
    }


    public sealed class GetServerlessBackupSchedulesArgs : global::Pulumi.InvokeArgs
    {
        [Input("accountId")]
        public string? AccountId { get; set; }

        [Input("id")]
        public string? Id { get; set; }

        [Input("spaceId")]
        public string? SpaceId { get; set; }

        public GetServerlessBackupSchedulesArgs()
        {
        }
        public static new GetServerlessBackupSchedulesArgs Empty => new GetServerlessBackupSchedulesArgs();
    }

    public sealed class GetServerlessBackupSchedulesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("spaceId")]
        public Input<string>? SpaceId { get; set; }

        public GetServerlessBackupSchedulesInvokeArgs()
        {
        }
        public static new GetServerlessBackupSchedulesInvokeArgs Empty => new GetServerlessBackupSchedulesInvokeArgs();
    }


    [OutputType]
    public sealed class GetServerlessBackupSchedulesResult
    {
        public readonly string AccountId;
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetServerlessBackupSchedulesScheduleResult> Schedules;
        public readonly string? SpaceId;

        [OutputConstructor]
        private GetServerlessBackupSchedulesResult(
            string accountId,

            string id,

            ImmutableArray<Outputs.GetServerlessBackupSchedulesScheduleResult> schedules,

            string? spaceId)
        {
            AccountId = accountId;
            Id = id;
            Schedules = schedules;
            SpaceId = spaceId;
        }
    }
}
