// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud
{
    public static class GetServerlessSpaceApiKeys
    {
        public static Task<GetServerlessSpaceApiKeysResult> InvokeAsync(GetServerlessSpaceApiKeysArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetServerlessSpaceApiKeysResult>("qdrant-cloud:index/getServerlessSpaceApiKeys:getServerlessSpaceApiKeys", args ?? new GetServerlessSpaceApiKeysArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetServerlessSpaceApiKeysResult> Invoke(GetServerlessSpaceApiKeysInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetServerlessSpaceApiKeysResult>("qdrant-cloud:index/getServerlessSpaceApiKeys:getServerlessSpaceApiKeys", args ?? new GetServerlessSpaceApiKeysInvokeArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetServerlessSpaceApiKeysResult> Invoke(GetServerlessSpaceApiKeysInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetServerlessSpaceApiKeysResult>("qdrant-cloud:index/getServerlessSpaceApiKeys:getServerlessSpaceApiKeys", args ?? new GetServerlessSpaceApiKeysInvokeArgs(), options.WithDefaults(), Utilities.PackageParameterization());
    }


    public sealed class GetServerlessSpaceApiKeysArgs : global::Pulumi.InvokeArgs
    {
        [Input("accountId")]
        public string? AccountId { get; set; }

        [Input("id")]
        public string? Id { get; set; }

        [Input("spaceId", required: true)]
        public string SpaceId { get; set; } = null!;

        public GetServerlessSpaceApiKeysArgs()
        {
        }
        public static new GetServerlessSpaceApiKeysArgs Empty => new GetServerlessSpaceApiKeysArgs();
    }

    public sealed class GetServerlessSpaceApiKeysInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("spaceId", required: true)]
        public Input<string> SpaceId { get; set; } = null!;

        public GetServerlessSpaceApiKeysInvokeArgs()
        {
        }
        public static new GetServerlessSpaceApiKeysInvokeArgs Empty => new GetServerlessSpaceApiKeysInvokeArgs();
    }


    [OutputType]
    public sealed class GetServerlessSpaceApiKeysResult
    {
        public readonly string AccountId;
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetServerlessSpaceApiKeysKeyResult> Keys;
        public readonly string SpaceId;

        [OutputConstructor]
        private GetServerlessSpaceApiKeysResult(
            string accountId,

            string id,

            ImmutableArray<Outputs.GetServerlessSpaceApiKeysKeyResult> keys,

            string spaceId)
        {
            AccountId = accountId;
            Id = id;
            Keys = keys;
            SpaceId = spaceId;
        }
    }
}
