// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud
{
    public static class GetServerlessBackups
    {
        public static Task<GetServerlessBackupsResult> InvokeAsync(GetServerlessBackupsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetServerlessBackupsResult>("qdrant-cloud:index/getServerlessBackups:getServerlessBackups", args ?? new GetServerlessBackupsArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetServerlessBackupsResult> Invoke(GetServerlessBackupsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetServerlessBackupsResult>("qdrant-cloud:index/getServerlessBackups:getServerlessBackups", args ?? new GetServerlessBackupsInvokeArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetServerlessBackupsResult> Invoke(GetServerlessBackupsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetServerlessBackupsResult>("qdrant-cloud:index/getServerlessBackups:getServerlessBackups", args ?? new GetServerlessBackupsInvokeArgs(), options.WithDefaults(), Utilities.PackageParameterization());
    }


    public sealed class GetServerlessBackupsArgs : global::Pulumi.InvokeArgs
    {
        [Input("accountId")]
        public string? AccountId { get; set; }

        [Input("backupScheduleId")]
        public string? BackupScheduleId { get; set; }

        [Input("collectionName")]
        public string? CollectionName { get; set; }

        [Input("id")]
        public string? Id { get; set; }

        [Input("spaceId")]
        public string? SpaceId { get; set; }

        public GetServerlessBackupsArgs()
        {
        }
        public static new GetServerlessBackupsArgs Empty => new GetServerlessBackupsArgs();
    }

    public sealed class GetServerlessBackupsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        [Input("backupScheduleId")]
        public Input<string>? BackupScheduleId { get; set; }

        [Input("collectionName")]
        public Input<string>? CollectionName { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("spaceId")]
        public Input<string>? SpaceId { get; set; }

        public GetServerlessBackupsInvokeArgs()
        {
        }
        public static new GetServerlessBackupsInvokeArgs Empty => new GetServerlessBackupsInvokeArgs();
    }


    [OutputType]
    public sealed class GetServerlessBackupsResult
    {
        public readonly string AccountId;
        public readonly string? BackupScheduleId;
        public readonly ImmutableArray<Outputs.GetServerlessBackupsBackupResult> Backups;
        public readonly string? CollectionName;
        public readonly string Id;
        public readonly string? SpaceId;

        [OutputConstructor]
        private GetServerlessBackupsResult(
            string accountId,

            string? backupScheduleId,

            ImmutableArray<Outputs.GetServerlessBackupsBackupResult> backups,

            string? collectionName,

            string id,

            string? spaceId)
        {
            AccountId = accountId;
            BackupScheduleId = backupScheduleId;
            Backups = backups;
            CollectionName = collectionName;
            Id = id;
            SpaceId = spaceId;
        }
    }
}
