// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud
{
    [QdrantCloudResourceType("qdrant-cloud:index/serverlessBackup:ServerlessBackup")]
    public partial class ServerlessBackup : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Serverless Backup Schema Account ID (defaults to the provider account ID) field
        /// </summary>
        [Output("accountId")]
        public Output<string> AccountId { get; private set; } = null!;

        /// <summary>
        /// Serverless Backup Schema ID of the backup schedule that created the backup (empty for manual backups) field
        /// </summary>
        [Output("backupScheduleId")]
        public Output<string> BackupScheduleId { get; private set; } = null!;

        /// <summary>
        /// Serverless Backup Schema Name of the collection to back up. If unset, the entire space is backed up field
        /// </summary>
        [Output("collectionName")]
        public Output<string> CollectionName { get; private set; } = null!;

        /// <summary>
        /// Serverless Backup Schema Creation time field
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Serverless Backup Schema Name of the backup (generated) field
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Serverless Backup Schema Retention period of the backup, as a Go duration string between &lt;span pulumi-lang-nodejs="`24h`" pulumi-lang-dotnet="`24h`" pulumi-lang-go="`24h`" pulumi-lang-python="`24h`" pulumi-lang-yaml="`24h`" pulumi-lang-java="`24h`" pulumi-lang-hcl="`24h`"&gt;`24h`&lt;/span&gt; and &lt;span pulumi-lang-nodejs="`8760h`" pulumi-lang-dotnet="`8760h`" pulumi-lang-go="`8760h`" pulumi-lang-python="`8760h`" pulumi-lang-yaml="`8760h`" pulumi-lang-java="`8760h`" pulumi-lang-hcl="`8760h`"&gt;`8760h`&lt;/span&gt;. If unset, the backup is retained indefinitely field
        /// </summary>
        [Output("retentionPeriod")]
        public Output<string> RetentionPeriod { get; private set; } = null!;

        /// <summary>
        /// Serverless Backup Schema ID of the serverless space to back up field
        /// </summary>
        [Output("spaceId")]
        public Output<string> SpaceId { get; private set; } = null!;

        /// <summary>
        /// Serverless Backup Schema Statistics of the backup field
        /// </summary>
        [Output("stats")]
        public Output<ImmutableArray<Outputs.ServerlessBackupStat>> Stats { get; private set; } = null!;

        /// <summary>
        /// Serverless Backup Schema Current status of the backup field
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.ServerlessBackupTimeouts?> Timeouts { get; private set; } = null!;


        /// <summary>
        /// Create a ServerlessBackup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServerlessBackup(string name, ServerlessBackupArgs args, CustomResourceOptions? options = null)
            : base("qdrant-cloud:index/serverlessBackup:ServerlessBackup", name, args ?? new ServerlessBackupArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private ServerlessBackup(string name, Input<string> id, ServerlessBackupState? state = null, CustomResourceOptions? options = null)
            : base("qdrant-cloud:index/serverlessBackup:ServerlessBackup", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ServerlessBackup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ServerlessBackup Get(string name, Input<string> id, ServerlessBackupState? state = null, CustomResourceOptions? options = null)
        {
            return new ServerlessBackup(name, id, state, options);
        }
    }

    public sealed class ServerlessBackupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Serverless Backup Schema Account ID (defaults to the provider account ID) field
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// Serverless Backup Schema Name of the collection to back up. If unset, the entire space is backed up field
        /// </summary>
        [Input("collectionName")]
        public Input<string>? CollectionName { get; set; }

        /// <summary>
        /// Serverless Backup Schema Retention period of the backup, as a Go duration string between &lt;span pulumi-lang-nodejs="`24h`" pulumi-lang-dotnet="`24h`" pulumi-lang-go="`24h`" pulumi-lang-python="`24h`" pulumi-lang-yaml="`24h`" pulumi-lang-java="`24h`" pulumi-lang-hcl="`24h`"&gt;`24h`&lt;/span&gt; and &lt;span pulumi-lang-nodejs="`8760h`" pulumi-lang-dotnet="`8760h`" pulumi-lang-go="`8760h`" pulumi-lang-python="`8760h`" pulumi-lang-yaml="`8760h`" pulumi-lang-java="`8760h`" pulumi-lang-hcl="`8760h`"&gt;`8760h`&lt;/span&gt;. If unset, the backup is retained indefinitely field
        /// </summary>
        [Input("retentionPeriod")]
        public Input<string>? RetentionPeriod { get; set; }

        /// <summary>
        /// Serverless Backup Schema ID of the serverless space to back up field
        /// </summary>
        [Input("spaceId", required: true)]
        public Input<string> SpaceId { get; set; } = null!;

        [Input("timeouts")]
        public Input<Inputs.ServerlessBackupTimeoutsArgs>? Timeouts { get; set; }

        public ServerlessBackupArgs()
        {
        }
        public static new ServerlessBackupArgs Empty => new ServerlessBackupArgs();
    }

    public sealed class ServerlessBackupState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Serverless Backup Schema Account ID (defaults to the provider account ID) field
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// Serverless Backup Schema ID of the backup schedule that created the backup (empty for manual backups) field
        /// </summary>
        [Input("backupScheduleId")]
        public Input<string>? BackupScheduleId { get; set; }

        /// <summary>
        /// Serverless Backup Schema Name of the collection to back up. If unset, the entire space is backed up field
        /// </summary>
        [Input("collectionName")]
        public Input<string>? CollectionName { get; set; }

        /// <summary>
        /// Serverless Backup Schema Creation time field
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Serverless Backup Schema Name of the backup (generated) field
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Serverless Backup Schema Retention period of the backup, as a Go duration string between &lt;span pulumi-lang-nodejs="`24h`" pulumi-lang-dotnet="`24h`" pulumi-lang-go="`24h`" pulumi-lang-python="`24h`" pulumi-lang-yaml="`24h`" pulumi-lang-java="`24h`" pulumi-lang-hcl="`24h`"&gt;`24h`&lt;/span&gt; and &lt;span pulumi-lang-nodejs="`8760h`" pulumi-lang-dotnet="`8760h`" pulumi-lang-go="`8760h`" pulumi-lang-python="`8760h`" pulumi-lang-yaml="`8760h`" pulumi-lang-java="`8760h`" pulumi-lang-hcl="`8760h`"&gt;`8760h`&lt;/span&gt;. If unset, the backup is retained indefinitely field
        /// </summary>
        [Input("retentionPeriod")]
        public Input<string>? RetentionPeriod { get; set; }

        /// <summary>
        /// Serverless Backup Schema ID of the serverless space to back up field
        /// </summary>
        [Input("spaceId")]
        public Input<string>? SpaceId { get; set; }

        [Input("stats")]
        private InputList<Inputs.ServerlessBackupStatGetArgs>? _stats;

        /// <summary>
        /// Serverless Backup Schema Statistics of the backup field
        /// </summary>
        public InputList<Inputs.ServerlessBackupStatGetArgs> Stats
        {
            get => _stats ?? (_stats = new InputList<Inputs.ServerlessBackupStatGetArgs>());
            set => _stats = value;
        }

        /// <summary>
        /// Serverless Backup Schema Current status of the backup field
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("timeouts")]
        public Input<Inputs.ServerlessBackupTimeoutsGetArgs>? Timeouts { get; set; }

        public ServerlessBackupState()
        {
        }
        public static new ServerlessBackupState Empty => new ServerlessBackupState();
    }
}
