// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.QdrantCloud
{
    [QdrantCloudResourceType("qdrant-cloud:index/serverlessSpaceApiKey:ServerlessSpaceApiKey")]
    public partial class ServerlessSpaceApiKey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Serverless Space API Key Schema Account ID (defaults to the provider account ID) field
        /// </summary>
        [Output("accountId")]
        public Output<string> AccountId { get; private set; } = null!;

        /// <summary>
        /// A list of rules granting access to specific collections (max 20). Cannot be used with &lt;span pulumi-lang-nodejs="`globalAccessRule`" pulumi-lang-dotnet="`GlobalAccessRule`" pulumi-lang-go="`globalAccessRule`" pulumi-lang-python="`global_access_rule`" pulumi-lang-yaml="`globalAccessRule`" pulumi-lang-java="`globalAccessRule`" pulumi-lang-hcl="`global_access_rule`"&gt;`globalAccessRule`&lt;/span&gt;.
        /// </summary>
        [Output("collectionAccessRules")]
        public Output<ImmutableArray<Outputs.ServerlessSpaceApiKeyCollectionAccessRule>> CollectionAccessRules { get; private set; } = null!;

        /// <summary>
        /// Serverless Space API Key Schema Creation time field
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Serverless Space API Key Schema Expiration time (RFC3339) of the API key. If not set, the key does not expire field
        /// </summary>
        [Output("expiresAt")]
        public Output<string> ExpiresAt { get; private set; } = null!;

        /// <summary>
        /// A rule granting access to the entire space. Cannot be used with &lt;span pulumi-lang-nodejs="`collectionAccessRules`" pulumi-lang-dotnet="`CollectionAccessRules`" pulumi-lang-go="`collectionAccessRules`" pulumi-lang-python="`collection_access_rules`" pulumi-lang-yaml="`collectionAccessRules`" pulumi-lang-java="`collectionAccessRules`" pulumi-lang-hcl="`collection_access_rules`"&gt;`collectionAccessRules`&lt;/span&gt;. If no rules are provided, global `MANAGE` access is granted.
        /// </summary>
        [Output("globalAccessRule")]
        public Output<Outputs.ServerlessSpaceApiKeyGlobalAccessRule?> GlobalAccessRule { get; private set; } = null!;

        /// <summary>
        /// Serverless Space API Key Schema Secret key, only available after creation (empty after import) field
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// Serverless Space API Key Schema Name of the API key (4-128 characters: letters, numbers, spaces, `_` and `-`) field
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Serverless Space API Key Schema Last characters of the key, to identify it field
        /// </summary>
        [Output("postfix")]
        public Output<string> Postfix { get; private set; } = null!;

        /// <summary>
        /// Serverless Space API Key Schema ID of the serverless space this API key grants access to field
        /// </summary>
        [Output("spaceId")]
        public Output<string> SpaceId { get; private set; } = null!;

        /// <summary>
        /// Serverless Space API Key Schema Current state of the API key field
        /// </summary>
        [Output("states")]
        public Output<ImmutableArray<Outputs.ServerlessSpaceApiKeyState>> States { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.ServerlessSpaceApiKeyTimeouts?> Timeouts { get; private set; } = null!;


        /// <summary>
        /// Create a ServerlessSpaceApiKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServerlessSpaceApiKey(string name, ServerlessSpaceApiKeyArgs args, CustomResourceOptions? options = null)
            : base("qdrant-cloud:index/serverlessSpaceApiKey:ServerlessSpaceApiKey", name, args ?? new ServerlessSpaceApiKeyArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private ServerlessSpaceApiKey(string name, Input<string> id, ServerlessSpaceApiKeyState? state = null, CustomResourceOptions? options = null)
            : base("qdrant-cloud:index/serverlessSpaceApiKey:ServerlessSpaceApiKey", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "key",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ServerlessSpaceApiKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ServerlessSpaceApiKey Get(string name, Input<string> id, ServerlessSpaceApiKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new ServerlessSpaceApiKey(name, id, state, options);
        }
    }

    public sealed class ServerlessSpaceApiKeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Serverless Space API Key Schema Account ID (defaults to the provider account ID) field
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        [Input("collectionAccessRules")]
        private InputList<Inputs.ServerlessSpaceApiKeyCollectionAccessRuleArgs>? _collectionAccessRules;

        /// <summary>
        /// A list of rules granting access to specific collections (max 20). Cannot be used with &lt;span pulumi-lang-nodejs="`globalAccessRule`" pulumi-lang-dotnet="`GlobalAccessRule`" pulumi-lang-go="`globalAccessRule`" pulumi-lang-python="`global_access_rule`" pulumi-lang-yaml="`globalAccessRule`" pulumi-lang-java="`globalAccessRule`" pulumi-lang-hcl="`global_access_rule`"&gt;`globalAccessRule`&lt;/span&gt;.
        /// </summary>
        public InputList<Inputs.ServerlessSpaceApiKeyCollectionAccessRuleArgs> CollectionAccessRules
        {
            get => _collectionAccessRules ?? (_collectionAccessRules = new InputList<Inputs.ServerlessSpaceApiKeyCollectionAccessRuleArgs>());
            set => _collectionAccessRules = value;
        }

        /// <summary>
        /// Serverless Space API Key Schema Expiration time (RFC3339) of the API key. If not set, the key does not expire field
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        /// <summary>
        /// A rule granting access to the entire space. Cannot be used with &lt;span pulumi-lang-nodejs="`collectionAccessRules`" pulumi-lang-dotnet="`CollectionAccessRules`" pulumi-lang-go="`collectionAccessRules`" pulumi-lang-python="`collection_access_rules`" pulumi-lang-yaml="`collectionAccessRules`" pulumi-lang-java="`collectionAccessRules`" pulumi-lang-hcl="`collection_access_rules`"&gt;`collectionAccessRules`&lt;/span&gt;. If no rules are provided, global `MANAGE` access is granted.
        /// </summary>
        [Input("globalAccessRule")]
        public Input<Inputs.ServerlessSpaceApiKeyGlobalAccessRuleArgs>? GlobalAccessRule { get; set; }

        /// <summary>
        /// Serverless Space API Key Schema Name of the API key (4-128 characters: letters, numbers, spaces, `_` and `-`) field
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Serverless Space API Key Schema ID of the serverless space this API key grants access to field
        /// </summary>
        [Input("spaceId", required: true)]
        public Input<string> SpaceId { get; set; } = null!;

        [Input("timeouts")]
        public Input<Inputs.ServerlessSpaceApiKeyTimeoutsArgs>? Timeouts { get; set; }

        public ServerlessSpaceApiKeyArgs()
        {
        }
        public static new ServerlessSpaceApiKeyArgs Empty => new ServerlessSpaceApiKeyArgs();
    }

    public sealed class ServerlessSpaceApiKeyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Serverless Space API Key Schema Account ID (defaults to the provider account ID) field
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        [Input("collectionAccessRules")]
        private InputList<Inputs.ServerlessSpaceApiKeyCollectionAccessRuleGetArgs>? _collectionAccessRules;

        /// <summary>
        /// A list of rules granting access to specific collections (max 20). Cannot be used with &lt;span pulumi-lang-nodejs="`globalAccessRule`" pulumi-lang-dotnet="`GlobalAccessRule`" pulumi-lang-go="`globalAccessRule`" pulumi-lang-python="`global_access_rule`" pulumi-lang-yaml="`globalAccessRule`" pulumi-lang-java="`globalAccessRule`" pulumi-lang-hcl="`global_access_rule`"&gt;`globalAccessRule`&lt;/span&gt;.
        /// </summary>
        public InputList<Inputs.ServerlessSpaceApiKeyCollectionAccessRuleGetArgs> CollectionAccessRules
        {
            get => _collectionAccessRules ?? (_collectionAccessRules = new InputList<Inputs.ServerlessSpaceApiKeyCollectionAccessRuleGetArgs>());
            set => _collectionAccessRules = value;
        }

        /// <summary>
        /// Serverless Space API Key Schema Creation time field
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Serverless Space API Key Schema Expiration time (RFC3339) of the API key. If not set, the key does not expire field
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        /// <summary>
        /// A rule granting access to the entire space. Cannot be used with &lt;span pulumi-lang-nodejs="`collectionAccessRules`" pulumi-lang-dotnet="`CollectionAccessRules`" pulumi-lang-go="`collectionAccessRules`" pulumi-lang-python="`collection_access_rules`" pulumi-lang-yaml="`collectionAccessRules`" pulumi-lang-java="`collectionAccessRules`" pulumi-lang-hcl="`collection_access_rules`"&gt;`collectionAccessRules`&lt;/span&gt;. If no rules are provided, global `MANAGE` access is granted.
        /// </summary>
        [Input("globalAccessRule")]
        public Input<Inputs.ServerlessSpaceApiKeyGlobalAccessRuleGetArgs>? GlobalAccessRule { get; set; }

        [Input("key")]
        private Input<string>? _key;

        /// <summary>
        /// Serverless Space API Key Schema Secret key, only available after creation (empty after import) field
        /// </summary>
        public Input<string>? Key
        {
            get => _key;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _key = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Serverless Space API Key Schema Name of the API key (4-128 characters: letters, numbers, spaces, `_` and `-`) field
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Serverless Space API Key Schema Last characters of the key, to identify it field
        /// </summary>
        [Input("postfix")]
        public Input<string>? Postfix { get; set; }

        /// <summary>
        /// Serverless Space API Key Schema ID of the serverless space this API key grants access to field
        /// </summary>
        [Input("spaceId")]
        public Input<string>? SpaceId { get; set; }

        [Input("states")]
        private InputList<Inputs.ServerlessSpaceApiKeyStateGetArgs>? _states;

        /// <summary>
        /// Serverless Space API Key Schema Current state of the API key field
        /// </summary>
        public InputList<Inputs.ServerlessSpaceApiKeyStateGetArgs> States
        {
            get => _states ?? (_states = new InputList<Inputs.ServerlessSpaceApiKeyStateGetArgs>());
            set => _states = value;
        }

        [Input("timeouts")]
        public Input<Inputs.ServerlessSpaceApiKeyTimeoutsGetArgs>? Timeouts { get; set; }

        public ServerlessSpaceApiKeyState()
        {
        }
        public static new ServerlessSpaceApiKeyState Empty => new ServerlessSpaceApiKeyState();
    }
}
