// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAccountsRoles(args?: GetAccountsRolesArgs, opts?: pulumi.InvokeOptions): Promise<GetAccountsRolesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("qdrant-cloud:index/getAccountsRoles:getAccountsRoles", {
        "accountId": args.accountId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAccountsRoles.
 */
export interface GetAccountsRolesArgs {
    accountId?: string;
    id?: string;
}

/**
 * A collection of values returned by getAccountsRoles.
 */
export interface GetAccountsRolesResult {
    readonly accountId: string;
    readonly id: string;
    readonly roles: outputs.GetAccountsRolesRole[];
}
export function getAccountsRolesOutput(args?: GetAccountsRolesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAccountsRolesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("qdrant-cloud:index/getAccountsRoles:getAccountsRoles", {
        "accountId": args.accountId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAccountsRoles.
 */
export interface GetAccountsRolesOutputArgs {
    accountId?: pulumi.Input<string | undefined>;
    id?: pulumi.Input<string | undefined>;
}
