// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAccountsDatabaseApiKeysV2(args: GetAccountsDatabaseApiKeysV2Args, opts?: pulumi.InvokeOptions): Promise<GetAccountsDatabaseApiKeysV2Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("qdrant-cloud:index/getAccountsDatabaseApiKeysV2:getAccountsDatabaseApiKeysV2", {
        "accountId": args.accountId,
        "clusterId": args.clusterId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAccountsDatabaseApiKeysV2.
 */
export interface GetAccountsDatabaseApiKeysV2Args {
    accountId?: string;
    clusterId: string;
    id?: string;
}

/**
 * A collection of values returned by getAccountsDatabaseApiKeysV2.
 */
export interface GetAccountsDatabaseApiKeysV2Result {
    readonly accountId: string;
    readonly clusterId: string;
    readonly id: string;
    readonly keys: outputs.GetAccountsDatabaseApiKeysV2Key[];
}
export function getAccountsDatabaseApiKeysV2Output(args: GetAccountsDatabaseApiKeysV2OutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAccountsDatabaseApiKeysV2Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("qdrant-cloud:index/getAccountsDatabaseApiKeysV2:getAccountsDatabaseApiKeysV2", {
        "accountId": args.accountId,
        "clusterId": args.clusterId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAccountsDatabaseApiKeysV2.
 */
export interface GetAccountsDatabaseApiKeysV2OutputArgs {
    accountId?: pulumi.Input<string | undefined>;
    clusterId: pulumi.Input<string>;
    id?: pulumi.Input<string | undefined>;
}
