// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAccountsBackupSchedules(args: GetAccountsBackupSchedulesArgs, opts?: pulumi.InvokeOptions): Promise<GetAccountsBackupSchedulesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("qdrant-cloud:index/getAccountsBackupSchedules:getAccountsBackupSchedules", {
        "accountId": args.accountId,
        "clusterId": args.clusterId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAccountsBackupSchedules.
 */
export interface GetAccountsBackupSchedulesArgs {
    accountId?: string;
    clusterId: string;
    id?: string;
}

/**
 * A collection of values returned by getAccountsBackupSchedules.
 */
export interface GetAccountsBackupSchedulesResult {
    readonly accountId: string;
    readonly clusterId: string;
    readonly id: string;
    readonly schedules: outputs.GetAccountsBackupSchedulesSchedule[];
}
export function getAccountsBackupSchedulesOutput(args: GetAccountsBackupSchedulesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAccountsBackupSchedulesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("qdrant-cloud:index/getAccountsBackupSchedules:getAccountsBackupSchedules", {
        "accountId": args.accountId,
        "clusterId": args.clusterId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAccountsBackupSchedules.
 */
export interface GetAccountsBackupSchedulesOutputArgs {
    accountId?: pulumi.Input<string | undefined>;
    clusterId: pulumi.Input<string>;
    id?: pulumi.Input<string | undefined>;
}
