// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getServerlessSpaceApiKeys(args: GetServerlessSpaceApiKeysArgs, opts?: pulumi.InvokeOptions): Promise<GetServerlessSpaceApiKeysResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("qdrant-cloud:index/getServerlessSpaceApiKeys:getServerlessSpaceApiKeys", {
        "accountId": args.accountId,
        "id": args.id,
        "spaceId": args.spaceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServerlessSpaceApiKeys.
 */
export interface GetServerlessSpaceApiKeysArgs {
    accountId?: string;
    id?: string;
    spaceId: string;
}

/**
 * A collection of values returned by getServerlessSpaceApiKeys.
 */
export interface GetServerlessSpaceApiKeysResult {
    readonly accountId: string;
    readonly id: string;
    readonly keys: outputs.GetServerlessSpaceApiKeysKey[];
    readonly spaceId: string;
}
export function getServerlessSpaceApiKeysOutput(args: GetServerlessSpaceApiKeysOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetServerlessSpaceApiKeysResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("qdrant-cloud:index/getServerlessSpaceApiKeys:getServerlessSpaceApiKeys", {
        "accountId": args.accountId,
        "id": args.id,
        "spaceId": args.spaceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServerlessSpaceApiKeys.
 */
export interface GetServerlessSpaceApiKeysOutputArgs {
    accountId?: pulumi.Input<string | undefined>;
    id?: pulumi.Input<string | undefined>;
    spaceId: pulumi.Input<string>;
}
