// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getServerlessBackupSchedules(args?: GetServerlessBackupSchedulesArgs, opts?: pulumi.InvokeOptions): Promise<GetServerlessBackupSchedulesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("qdrant-cloud:index/getServerlessBackupSchedules:getServerlessBackupSchedules", {
        "accountId": args.accountId,
        "id": args.id,
        "spaceId": args.spaceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServerlessBackupSchedules.
 */
export interface GetServerlessBackupSchedulesArgs {
    accountId?: string;
    id?: string;
    spaceId?: string;
}

/**
 * A collection of values returned by getServerlessBackupSchedules.
 */
export interface GetServerlessBackupSchedulesResult {
    readonly accountId: string;
    readonly id: string;
    readonly schedules: outputs.GetServerlessBackupSchedulesSchedule[];
    readonly spaceId?: string;
}
export function getServerlessBackupSchedulesOutput(args?: GetServerlessBackupSchedulesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetServerlessBackupSchedulesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("qdrant-cloud:index/getServerlessBackupSchedules:getServerlessBackupSchedules", {
        "accountId": args.accountId,
        "id": args.id,
        "spaceId": args.spaceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServerlessBackupSchedules.
 */
export interface GetServerlessBackupSchedulesOutputArgs {
    accountId?: pulumi.Input<string | undefined>;
    id?: pulumi.Input<string | undefined>;
    spaceId?: pulumi.Input<string | undefined>;
}
