// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AccountsAuthKeyArgs, AccountsAuthKeyState } from "./accountsAuthKey";
export type AccountsAuthKey = import("./accountsAuthKey").AccountsAuthKey;
export const AccountsAuthKey: typeof import("./accountsAuthKey").AccountsAuthKey = null as any;
utilities.lazyLoad(exports, ["AccountsAuthKey"], () => require("./accountsAuthKey"));

export { AccountsBackupScheduleArgs, AccountsBackupScheduleState } from "./accountsBackupSchedule";
export type AccountsBackupSchedule = import("./accountsBackupSchedule").AccountsBackupSchedule;
export const AccountsBackupSchedule: typeof import("./accountsBackupSchedule").AccountsBackupSchedule = null as any;
utilities.lazyLoad(exports, ["AccountsBackupSchedule"], () => require("./accountsBackupSchedule"));

export { AccountsClusterArgs, AccountsClusterState } from "./accountsCluster";
export type AccountsCluster = import("./accountsCluster").AccountsCluster;
export const AccountsCluster: typeof import("./accountsCluster").AccountsCluster = null as any;
utilities.lazyLoad(exports, ["AccountsCluster"], () => require("./accountsCluster"));

export { AccountsDatabaseApiKeyV2Args, AccountsDatabaseApiKeyV2State } from "./accountsDatabaseApiKeyV2";
export type AccountsDatabaseApiKeyV2 = import("./accountsDatabaseApiKeyV2").AccountsDatabaseApiKeyV2;
export const AccountsDatabaseApiKeyV2: typeof import("./accountsDatabaseApiKeyV2").AccountsDatabaseApiKeyV2 = null as any;
utilities.lazyLoad(exports, ["AccountsDatabaseApiKeyV2"], () => require("./accountsDatabaseApiKeyV2"));

export { AccountsHybridCloudEnvironmentArgs, AccountsHybridCloudEnvironmentState } from "./accountsHybridCloudEnvironment";
export type AccountsHybridCloudEnvironment = import("./accountsHybridCloudEnvironment").AccountsHybridCloudEnvironment;
export const AccountsHybridCloudEnvironment: typeof import("./accountsHybridCloudEnvironment").AccountsHybridCloudEnvironment = null as any;
utilities.lazyLoad(exports, ["AccountsHybridCloudEnvironment"], () => require("./accountsHybridCloudEnvironment"));

export { AccountsManualBackupArgs, AccountsManualBackupState } from "./accountsManualBackup";
export type AccountsManualBackup = import("./accountsManualBackup").AccountsManualBackup;
export const AccountsManualBackup: typeof import("./accountsManualBackup").AccountsManualBackup = null as any;
utilities.lazyLoad(exports, ["AccountsManualBackup"], () => require("./accountsManualBackup"));

export { AccountsRoleArgs, AccountsRoleState } from "./accountsRole";
export type AccountsRole = import("./accountsRole").AccountsRole;
export const AccountsRole: typeof import("./accountsRole").AccountsRole = null as any;
utilities.lazyLoad(exports, ["AccountsRole"], () => require("./accountsRole"));

export { AccountsUserRolesArgs, AccountsUserRolesState } from "./accountsUserRoles";
export type AccountsUserRoles = import("./accountsUserRoles").AccountsUserRoles;
export const AccountsUserRoles: typeof import("./accountsUserRoles").AccountsUserRoles = null as any;
utilities.lazyLoad(exports, ["AccountsUserRoles"], () => require("./accountsUserRoles"));

export { GetAccountsAuthKeysArgs, GetAccountsAuthKeysResult, GetAccountsAuthKeysOutputArgs } from "./getAccountsAuthKeys";
export const getAccountsAuthKeys: typeof import("./getAccountsAuthKeys").getAccountsAuthKeys = null as any;
export const getAccountsAuthKeysOutput: typeof import("./getAccountsAuthKeys").getAccountsAuthKeysOutput = null as any;
utilities.lazyLoad(exports, ["getAccountsAuthKeys","getAccountsAuthKeysOutput"], () => require("./getAccountsAuthKeys"));

export { GetAccountsBackupScheduleArgs, GetAccountsBackupScheduleResult, GetAccountsBackupScheduleOutputArgs } from "./getAccountsBackupSchedule";
export const getAccountsBackupSchedule: typeof import("./getAccountsBackupSchedule").getAccountsBackupSchedule = null as any;
export const getAccountsBackupScheduleOutput: typeof import("./getAccountsBackupSchedule").getAccountsBackupScheduleOutput = null as any;
utilities.lazyLoad(exports, ["getAccountsBackupSchedule","getAccountsBackupScheduleOutput"], () => require("./getAccountsBackupSchedule"));

export { GetAccountsBackupSchedulesArgs, GetAccountsBackupSchedulesResult, GetAccountsBackupSchedulesOutputArgs } from "./getAccountsBackupSchedules";
export const getAccountsBackupSchedules: typeof import("./getAccountsBackupSchedules").getAccountsBackupSchedules = null as any;
export const getAccountsBackupSchedulesOutput: typeof import("./getAccountsBackupSchedules").getAccountsBackupSchedulesOutput = null as any;
utilities.lazyLoad(exports, ["getAccountsBackupSchedules","getAccountsBackupSchedulesOutput"], () => require("./getAccountsBackupSchedules"));

export { GetAccountsClusterArgs, GetAccountsClusterResult, GetAccountsClusterOutputArgs } from "./getAccountsCluster";
export const getAccountsCluster: typeof import("./getAccountsCluster").getAccountsCluster = null as any;
export const getAccountsClusterOutput: typeof import("./getAccountsCluster").getAccountsClusterOutput = null as any;
utilities.lazyLoad(exports, ["getAccountsCluster","getAccountsClusterOutput"], () => require("./getAccountsCluster"));

export { GetAccountsClustersArgs, GetAccountsClustersResult, GetAccountsClustersOutputArgs } from "./getAccountsClusters";
export const getAccountsClusters: typeof import("./getAccountsClusters").getAccountsClusters = null as any;
export const getAccountsClustersOutput: typeof import("./getAccountsClusters").getAccountsClustersOutput = null as any;
utilities.lazyLoad(exports, ["getAccountsClusters","getAccountsClustersOutput"], () => require("./getAccountsClusters"));

export { GetAccountsDatabaseApiKeysV2Args, GetAccountsDatabaseApiKeysV2Result, GetAccountsDatabaseApiKeysV2OutputArgs } from "./getAccountsDatabaseApiKeysV2";
export const getAccountsDatabaseApiKeysV2: typeof import("./getAccountsDatabaseApiKeysV2").getAccountsDatabaseApiKeysV2 = null as any;
export const getAccountsDatabaseApiKeysV2Output: typeof import("./getAccountsDatabaseApiKeysV2").getAccountsDatabaseApiKeysV2Output = null as any;
utilities.lazyLoad(exports, ["getAccountsDatabaseApiKeysV2","getAccountsDatabaseApiKeysV2Output"], () => require("./getAccountsDatabaseApiKeysV2"));

export { GetAccountsMembersArgs, GetAccountsMembersResult, GetAccountsMembersOutputArgs } from "./getAccountsMembers";
export const getAccountsMembers: typeof import("./getAccountsMembers").getAccountsMembers = null as any;
export const getAccountsMembersOutput: typeof import("./getAccountsMembers").getAccountsMembersOutput = null as any;
utilities.lazyLoad(exports, ["getAccountsMembers","getAccountsMembersOutput"], () => require("./getAccountsMembers"));

export { GetAccountsRolesArgs, GetAccountsRolesResult, GetAccountsRolesOutputArgs } from "./getAccountsRoles";
export const getAccountsRoles: typeof import("./getAccountsRoles").getAccountsRoles = null as any;
export const getAccountsRolesOutput: typeof import("./getAccountsRoles").getAccountsRolesOutput = null as any;
utilities.lazyLoad(exports, ["getAccountsRoles","getAccountsRolesOutput"], () => require("./getAccountsRoles"));

export { GetBookingPackagesArgs, GetBookingPackagesResult, GetBookingPackagesOutputArgs } from "./getBookingPackages";
export const getBookingPackages: typeof import("./getBookingPackages").getBookingPackages = null as any;
export const getBookingPackagesOutput: typeof import("./getBookingPackages").getBookingPackagesOutput = null as any;
utilities.lazyLoad(exports, ["getBookingPackages","getBookingPackagesOutput"], () => require("./getBookingPackages"));

export { GetServerlessBackupScheduleArgs, GetServerlessBackupScheduleResult, GetServerlessBackupScheduleOutputArgs } from "./getServerlessBackupSchedule";
export const getServerlessBackupSchedule: typeof import("./getServerlessBackupSchedule").getServerlessBackupSchedule = null as any;
export const getServerlessBackupScheduleOutput: typeof import("./getServerlessBackupSchedule").getServerlessBackupScheduleOutput = null as any;
utilities.lazyLoad(exports, ["getServerlessBackupSchedule","getServerlessBackupScheduleOutput"], () => require("./getServerlessBackupSchedule"));

export { GetServerlessBackupSchedulesArgs, GetServerlessBackupSchedulesResult, GetServerlessBackupSchedulesOutputArgs } from "./getServerlessBackupSchedules";
export const getServerlessBackupSchedules: typeof import("./getServerlessBackupSchedules").getServerlessBackupSchedules = null as any;
export const getServerlessBackupSchedulesOutput: typeof import("./getServerlessBackupSchedules").getServerlessBackupSchedulesOutput = null as any;
utilities.lazyLoad(exports, ["getServerlessBackupSchedules","getServerlessBackupSchedulesOutput"], () => require("./getServerlessBackupSchedules"));

export { GetServerlessBackupsArgs, GetServerlessBackupsResult, GetServerlessBackupsOutputArgs } from "./getServerlessBackups";
export const getServerlessBackups: typeof import("./getServerlessBackups").getServerlessBackups = null as any;
export const getServerlessBackupsOutput: typeof import("./getServerlessBackups").getServerlessBackupsOutput = null as any;
utilities.lazyLoad(exports, ["getServerlessBackups","getServerlessBackupsOutput"], () => require("./getServerlessBackups"));

export { GetServerlessCloudRegionsArgs, GetServerlessCloudRegionsResult, GetServerlessCloudRegionsOutputArgs } from "./getServerlessCloudRegions";
export const getServerlessCloudRegions: typeof import("./getServerlessCloudRegions").getServerlessCloudRegions = null as any;
export const getServerlessCloudRegionsOutput: typeof import("./getServerlessCloudRegions").getServerlessCloudRegionsOutput = null as any;
utilities.lazyLoad(exports, ["getServerlessCloudRegions","getServerlessCloudRegionsOutput"], () => require("./getServerlessCloudRegions"));

export { GetServerlessSpaceArgs, GetServerlessSpaceResult, GetServerlessSpaceOutputArgs } from "./getServerlessSpace";
export const getServerlessSpace: typeof import("./getServerlessSpace").getServerlessSpace = null as any;
export const getServerlessSpaceOutput: typeof import("./getServerlessSpace").getServerlessSpaceOutput = null as any;
utilities.lazyLoad(exports, ["getServerlessSpace","getServerlessSpaceOutput"], () => require("./getServerlessSpace"));

export { GetServerlessSpaceApiKeysArgs, GetServerlessSpaceApiKeysResult, GetServerlessSpaceApiKeysOutputArgs } from "./getServerlessSpaceApiKeys";
export const getServerlessSpaceApiKeys: typeof import("./getServerlessSpaceApiKeys").getServerlessSpaceApiKeys = null as any;
export const getServerlessSpaceApiKeysOutput: typeof import("./getServerlessSpaceApiKeys").getServerlessSpaceApiKeysOutput = null as any;
utilities.lazyLoad(exports, ["getServerlessSpaceApiKeys","getServerlessSpaceApiKeysOutput"], () => require("./getServerlessSpaceApiKeys"));

export { GetServerlessSpacesArgs, GetServerlessSpacesResult, GetServerlessSpacesOutputArgs } from "./getServerlessSpaces";
export const getServerlessSpaces: typeof import("./getServerlessSpaces").getServerlessSpaces = null as any;
export const getServerlessSpacesOutput: typeof import("./getServerlessSpaces").getServerlessSpacesOutput = null as any;
utilities.lazyLoad(exports, ["getServerlessSpaces","getServerlessSpacesOutput"], () => require("./getServerlessSpaces"));

export * from "./provider";
import { Provider } from "./provider";

export { ServerlessBackupArgs, ServerlessBackupState } from "./serverlessBackup";
export type ServerlessBackup = import("./serverlessBackup").ServerlessBackup;
export const ServerlessBackup: typeof import("./serverlessBackup").ServerlessBackup = null as any;
utilities.lazyLoad(exports, ["ServerlessBackup"], () => require("./serverlessBackup"));

export { ServerlessBackupScheduleArgs, ServerlessBackupScheduleState } from "./serverlessBackupSchedule";
export type ServerlessBackupSchedule = import("./serverlessBackupSchedule").ServerlessBackupSchedule;
export const ServerlessBackupSchedule: typeof import("./serverlessBackupSchedule").ServerlessBackupSchedule = null as any;
utilities.lazyLoad(exports, ["ServerlessBackupSchedule"], () => require("./serverlessBackupSchedule"));

export { ServerlessSpaceArgs, ServerlessSpaceState } from "./serverlessSpace";
export type ServerlessSpace = import("./serverlessSpace").ServerlessSpace;
export const ServerlessSpace: typeof import("./serverlessSpace").ServerlessSpace = null as any;
utilities.lazyLoad(exports, ["ServerlessSpace"], () => require("./serverlessSpace"));

export { ServerlessSpaceApiKeyArgs, ServerlessSpaceApiKeyState } from "./serverlessSpaceApiKey";
export type ServerlessSpaceApiKey = import("./serverlessSpaceApiKey").ServerlessSpaceApiKey;
export const ServerlessSpaceApiKey: typeof import("./serverlessSpaceApiKey").ServerlessSpaceApiKey = null as any;
utilities.lazyLoad(exports, ["ServerlessSpaceApiKey"], () => require("./serverlessSpaceApiKey"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "qdrant-cloud:index/accountsAuthKey:AccountsAuthKey":
                return new AccountsAuthKey(name, <any>undefined, { urn })
            case "qdrant-cloud:index/accountsBackupSchedule:AccountsBackupSchedule":
                return new AccountsBackupSchedule(name, <any>undefined, { urn })
            case "qdrant-cloud:index/accountsCluster:AccountsCluster":
                return new AccountsCluster(name, <any>undefined, { urn })
            case "qdrant-cloud:index/accountsDatabaseApiKeyV2:AccountsDatabaseApiKeyV2":
                return new AccountsDatabaseApiKeyV2(name, <any>undefined, { urn })
            case "qdrant-cloud:index/accountsHybridCloudEnvironment:AccountsHybridCloudEnvironment":
                return new AccountsHybridCloudEnvironment(name, <any>undefined, { urn })
            case "qdrant-cloud:index/accountsManualBackup:AccountsManualBackup":
                return new AccountsManualBackup(name, <any>undefined, { urn })
            case "qdrant-cloud:index/accountsRole:AccountsRole":
                return new AccountsRole(name, <any>undefined, { urn })
            case "qdrant-cloud:index/accountsUserRoles:AccountsUserRoles":
                return new AccountsUserRoles(name, <any>undefined, { urn })
            case "qdrant-cloud:index/serverlessBackup:ServerlessBackup":
                return new ServerlessBackup(name, <any>undefined, { urn })
            case "qdrant-cloud:index/serverlessBackupSchedule:ServerlessBackupSchedule":
                return new ServerlessBackupSchedule(name, <any>undefined, { urn })
            case "qdrant-cloud:index/serverlessSpace:ServerlessSpace":
                return new ServerlessSpace(name, <any>undefined, { urn })
            case "qdrant-cloud:index/serverlessSpaceApiKey:ServerlessSpaceApiKey":
                return new ServerlessSpaceApiKey(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/accountsAuthKey", _module)
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/accountsBackupSchedule", _module)
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/accountsCluster", _module)
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/accountsDatabaseApiKeyV2", _module)
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/accountsHybridCloudEnvironment", _module)
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/accountsManualBackup", _module)
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/accountsRole", _module)
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/accountsUserRoles", _module)
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/serverlessBackup", _module)
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/serverlessBackupSchedule", _module)
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/serverlessSpace", _module)
pulumi.runtime.registerResourceModule("qdrant-cloud", "index/serverlessSpaceApiKey", _module)
pulumi.runtime.registerResourcePackage("qdrant-cloud", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:qdrant-cloud") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
