// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AccountsClusterConfiguration {
    /**
     * List of allowed IP source ranges for this cluster. On Hybrid Cloud, this will configure the loadBalancerSourceRanges of a LoadBalancer Service.
     */
    allowedIpSourceRanges?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * List of annotations for this cluster in a hybrid cloud environment.
     */
    annotations?: pulumi.Input<pulumi.Input<inputs.AccountsClusterConfigurationAnnotation>[] | undefined>;
    /**
     * Configuration for cluster storage settings.
     */
    clusterStorageConfiguration?: pulumi.Input<inputs.AccountsClusterConfigurationClusterStorageConfiguration | undefined>;
    /**
     * Configuration for the Qdrant database engine, primarily for hybrid cloud setups.
     */
    databaseConfiguration?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfiguration | undefined>;
    /**
     * The GPU type that should be used for the database. Must be one of: CLUSTER_CONFIGURATION_GPU_TYPE_AMD, CLUSTER_CONFIGURATION_GPU_TYPE_NVIDIA.
     */
    gpuType?: pulumi.Input<string | undefined>;
    /**
     * Cluster Schema Timestamp when the cluster configuration was last updated field
     */
    lastModifiedAt?: pulumi.Input<string | undefined>;
    /**
     * Cluster Schema The node configuration options of a cluster field
     */
    nodeConfiguration: pulumi.Input<inputs.AccountsClusterConfigurationNodeConfiguration>;
    /**
     * The node selector for this cluster in a hybrid cloud environment.
     */
    nodeSelectors?: pulumi.Input<pulumi.Input<inputs.AccountsClusterConfigurationNodeSelector>[] | undefined>;
    /**
     * Cluster Schema The number of nodes in the cluster field
     */
    numberOfNodes: pulumi.Input<number>;
    /**
     * List of labels applied to the pods of this cluster in a hybrid cloud environment.
     */
    podLabels?: pulumi.Input<pulumi.Input<inputs.AccountsClusterConfigurationPodLabel>[] | undefined>;
    /**
     * The automatic shard rebalancing strategy for the database. Must be one of: CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_COUNT_AND_SIZE, CLUSTER_CONFIGURATION_REBALANCE_STRATEGY_BY_SIZE.
     */
    rebalanceStrategy?: pulumi.Input<string | undefined>;
    /**
     * The percentage of CPU resources reserved for system components.
     */
    reservedCpuPercentage?: pulumi.Input<number | undefined>;
    /**
     * The percentage of RAM resources reserved for system components.
     */
    reservedMemoryPercentage?: pulumi.Input<number | undefined>;
    /**
     * The restart policy for the database. Must be one of: CLUSTER_CONFIGURATION_RESTART_POLICY_AUTOMATIC, CLUSTER_CONFIGURATION_RESTART_POLICY_PARALLEL, CLUSTER_CONFIGURATION_RESTART_POLICY_ROLLING.
     */
    restartPolicy?: pulumi.Input<string | undefined>;
    /**
     * List of annotations applied to the service of this cluster in a hybrid cloud environment.
     */
    serviceAnnotations?: pulumi.Input<pulumi.Input<inputs.AccountsClusterConfigurationServiceAnnotation>[] | undefined>;
    /**
     * The type of service to use for this cluster in a hybrid cloud environment. Must be one of: CLUSTER_SERVICE_TYPE_CLUSTER_IP, CLUSTER_SERVICE_TYPE_LOAD_BALANCER, CLUSTER_SERVICE_TYPE_NODE_PORT.
     */
    serviceType?: pulumi.Input<string | undefined>;
    /**
     * List of tolerations for this cluster in a hybrid cloud environment.
     */
    tolerations?: pulumi.Input<pulumi.Input<inputs.AccountsClusterConfigurationToleration>[] | undefined>;
    /**
     * List of topology spread constraints for this cluster in a hybrid cloud environment.
     */
    topologySpreadConstraints?: pulumi.Input<pulumi.Input<inputs.AccountsClusterConfigurationTopologySpreadConstraint>[] | undefined>;
    /**
     * Cluster Schema Version of the Qdrant cluster field
     */
    version?: pulumi.Input<string | undefined>;
}

export interface AccountsClusterConfigurationAnnotation {
    key: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface AccountsClusterConfigurationClusterStorageConfiguration {
    /**
     * The storage class to use for the database storage, if different from the environment default. Hybrid cloud clusters only.
     */
    databaseStorageClass?: pulumi.Input<string | undefined>;
    /**
     * The storage class to use for the snapshot storage, if different from the environment default. Hybrid cloud clusters only.
     */
    snapshotStorageClass?: pulumi.Input<string | undefined>;
    /**
     * The storage performance tier for the cluster. Must be one of: STORAGE_TIER_TYPE_BALANCED, STORAGE_TIER_TYPE_COST_OPTIMISED, STORAGE_TIER_TYPE_PERFORMANCE.
     */
    storageTierType?: pulumi.Input<string | undefined>;
    /**
     * The volume snapshot class to use for the database storage, if different from the environment default. Hybrid cloud clusters only.
     */
    volumeSnapshotClass?: pulumi.Input<string | undefined>;
}

export interface AccountsClusterConfigurationDatabaseConfiguration {
    /**
     * Audit logging configuration for the Qdrant database.
     */
    auditLogging?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationAuditLogging | undefined>;
    /**
     * Default collection parameters.
     */
    collection?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationCollection | undefined>;
    /**
     * Inference service configuration.
     */
    inference?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationInference | undefined>;
    /**
     * Logging level for the database. Must be one of: DATABASE_CONFIGURATION_LOG_LEVEL_DEBUG, DATABASE_CONFIGURATION_LOG_LEVEL_ERROR, DATABASE_CONFIGURATION_LOG_LEVEL_INFO, DATABASE_CONFIGURATION_LOG_LEVEL_OFF, DATABASE_CONFIGURATION_LOG_LEVEL_TRACE, DATABASE_CONFIGURATION_LOG_LEVEL_WARN.
     */
    logLevel?: pulumi.Input<string | undefined>;
    /**
     * Service-related configuration.
     */
    service?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationService | undefined>;
    /**
     * Storage-related configuration.
     */
    storage?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationStorage | undefined>;
    /**
     * TLS configuration for the database.
     */
    tls?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationTls | undefined>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationAuditLogging {
    /**
     * If true, the cluster is configured to use audit logging.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Maximum number of rotated audit log files to keep. Default is 7.
     */
    maxLogFiles?: pulumi.Input<number | undefined>;
    /**
     * Rotation interval for audit logs. Must be one of: AUDIT_LOG_ROTATION_DAILY, AUDIT_LOG_ROTATION_HOURLY.
     */
    rotation?: pulumi.Input<string | undefined>;
    /**
     * Whether to use the X-Forwarded-For header to determine the client address in audit log entries. Relevant for hybrid cloud clusters only.
     */
    trustForwardedHeaders?: pulumi.Input<boolean | undefined>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationCollection {
    replicationFactor?: pulumi.Input<number | undefined>;
    vectors?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationCollectionVectors | undefined>;
    writeConsistencyFactor?: pulumi.Input<number | undefined>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationCollectionVectors {
    onDisk?: pulumi.Input<boolean | undefined>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationInference {
    enabled?: pulumi.Input<boolean | undefined>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationService {
    /**
     * Secret to use for the main API key.
     */
    apiKey?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationServiceApiKey | undefined>;
    enableTls?: pulumi.Input<boolean | undefined>;
    /**
     * @deprecated Deprecated
     */
    forceIncludeJwtRbac?: pulumi.Input<boolean | undefined>;
    jwtRbac?: pulumi.Input<boolean | undefined>;
    /**
     * Secret to use for the read-only API key.
     */
    readOnlyApiKey?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKey | undefined>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationServiceApiKey {
    /**
     * The key within the secret.
     */
    secretKey: pulumi.Input<string>;
    /**
     * The name of the secret.
     */
    secretName: pulumi.Input<string>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationServiceReadOnlyApiKey {
    /**
     * The key within the secret.
     */
    secretKey: pulumi.Input<string>;
    /**
     * The name of the secret.
     */
    secretName: pulumi.Input<string>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationStorage {
    performance?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationStoragePerformance | undefined>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationStoragePerformance {
    asyncScorer?: pulumi.Input<boolean | undefined>;
    optimizerCpuBudget?: pulumi.Input<number | undefined>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationTls {
    /**
     * Secret to use for the certificate.
     */
    cert?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationTlsCert | undefined>;
    /**
     * Secret to use for the private key.
     */
    key?: pulumi.Input<inputs.AccountsClusterConfigurationDatabaseConfigurationTlsKey | undefined>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationTlsCert {
    /**
     * The key within the secret.
     */
    secretKey: pulumi.Input<string>;
    /**
     * The name of the secret.
     */
    secretName: pulumi.Input<string>;
}

export interface AccountsClusterConfigurationDatabaseConfigurationTlsKey {
    /**
     * The key within the secret.
     */
    secretKey: pulumi.Input<string>;
    /**
     * The name of the secret.
     */
    secretName: pulumi.Input<string>;
}

export interface AccountsClusterConfigurationNodeConfiguration {
    /**
     * Cluster Schema The package identifier (specifying: CPU, Memory, and disk size) field
     */
    packageId: pulumi.Input<string>;
    /**
     * The resource configuration of the package
     */
    resourceConfigurations?: pulumi.Input<pulumi.Input<inputs.AccountsClusterConfigurationNodeConfigurationResourceConfiguration>[] | undefined>;
}

export interface AccountsClusterConfigurationNodeConfigurationResourceConfiguration {
    /**
     * The amount of the resource
     */
    amount: pulumi.Input<number>;
    /**
     * The type of the resource
     */
    resourceType: pulumi.Input<string>;
    /**
     * The unit of the resource
     */
    resourceUnit: pulumi.Input<string>;
}

export interface AccountsClusterConfigurationNodeSelector {
    key: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface AccountsClusterConfigurationPodLabel {
    key: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface AccountsClusterConfigurationServiceAnnotation {
    key: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface AccountsClusterConfigurationToleration {
    /**
     * The toleration effect. Must be one of: TOLERATION_EFFECT_NO_EXECUTE, TOLERATION_EFFECT_NO_SCHEDULE, TOLERATION_EFFECT_PREFER_NO_SCHEDULE.
     */
    effect?: pulumi.Input<string | undefined>;
    key?: pulumi.Input<string | undefined>;
    /**
     * The toleration operator. Must be one of: TOLERATION_OPERATOR_EQUAL, TOLERATION_OPERATOR_EXISTS.
     */
    operator?: pulumi.Input<string | undefined>;
    tolerationSeconds?: pulumi.Input<number | undefined>;
    value?: pulumi.Input<string | undefined>;
}

export interface AccountsClusterConfigurationTopologySpreadConstraint {
    maxSkew: pulumi.Input<number>;
    topologyKey: pulumi.Input<string>;
    /**
     * Action to take when the topology spread constraint cannot be satisfied. Must be one of: TOPOLOGY_SPREAD_CONSTRAINT_WHEN_UNSATISFIABLE_DO_NOT_SCHEDULE, TOPOLOGY_SPREAD_CONSTRAINT_WHEN_UNSATISFIABLE_SCHEDULE_ANYWAY.
     */
    whenUnsatisfiable: pulumi.Input<string>;
}

export interface AccountsClusterLabel {
    key: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface AccountsClusterStatus {
    capabilities?: pulumi.Input<pulumi.Input<inputs.AccountsClusterStatusCapability>[] | undefined>;
    nodesUp?: pulumi.Input<number | undefined>;
    phase?: pulumi.Input<string | undefined>;
    reason?: pulumi.Input<string | undefined>;
    resources?: pulumi.Input<pulumi.Input<inputs.AccountsClusterStatusResource>[] | undefined>;
    restartedAt?: pulumi.Input<string | undefined>;
    scalabilityInfos?: pulumi.Input<pulumi.Input<inputs.AccountsClusterStatusScalabilityInfo>[] | undefined>;
    version?: pulumi.Input<string | undefined>;
}

export interface AccountsClusterStatusCapability {
    backups?: pulumi.Input<pulumi.Input<inputs.AccountsClusterStatusCapabilityBackup>[] | undefined>;
    diskExpansions?: pulumi.Input<pulumi.Input<inputs.AccountsClusterStatusCapabilityDiskExpansion>[] | undefined>;
    scalabilityInfos?: pulumi.Input<pulumi.Input<inputs.AccountsClusterStatusCapabilityScalabilityInfo>[] | undefined>;
}

export interface AccountsClusterStatusCapabilityBackup {
    reason?: pulumi.Input<string | undefined>;
    status?: pulumi.Input<string | undefined>;
}

export interface AccountsClusterStatusCapabilityDiskExpansion {
    reason?: pulumi.Input<string | undefined>;
    status?: pulumi.Input<string | undefined>;
}

export interface AccountsClusterStatusCapabilityScalabilityInfo {
    reason?: pulumi.Input<string | undefined>;
    status?: pulumi.Input<string | undefined>;
}

export interface AccountsClusterStatusResource {
    cpus?: pulumi.Input<pulumi.Input<inputs.AccountsClusterStatusResourceCpus>[] | undefined>;
    disks?: pulumi.Input<pulumi.Input<inputs.AccountsClusterStatusResourceDisk>[] | undefined>;
    rams?: pulumi.Input<pulumi.Input<inputs.AccountsClusterStatusResourceRam>[] | undefined>;
}

export interface AccountsClusterStatusResourceCpus {
    additional?: pulumi.Input<number | undefined>;
    available?: pulumi.Input<number | undefined>;
    base?: pulumi.Input<number | undefined>;
    complimentary?: pulumi.Input<number | undefined>;
    reserved?: pulumi.Input<number | undefined>;
}

export interface AccountsClusterStatusResourceDisk {
    additional?: pulumi.Input<number | undefined>;
    available?: pulumi.Input<number | undefined>;
    base?: pulumi.Input<number | undefined>;
    complimentary?: pulumi.Input<number | undefined>;
    reserved?: pulumi.Input<number | undefined>;
}

export interface AccountsClusterStatusResourceRam {
    additional?: pulumi.Input<number | undefined>;
    available?: pulumi.Input<number | undefined>;
    base?: pulumi.Input<number | undefined>;
    complimentary?: pulumi.Input<number | undefined>;
    reserved?: pulumi.Input<number | undefined>;
}

export interface AccountsClusterStatusScalabilityInfo {
    reason?: pulumi.Input<string | undefined>;
    status?: pulumi.Input<string | undefined>;
}

export interface AccountsClusterTimeouts {
    create?: pulumi.Input<string | undefined>;
}

export interface AccountsDatabaseApiKeyV2CollectionAccessRule {
    /**
     * Access type for the collection. Must be one of: COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_ONLY, COLLECTION_ACCESS_RULE_ACCESS_TYPE_READ_WRITE.
     */
    accessType: pulumi.Input<string>;
    /**
     * Name of the collection.
     */
    collectionName: pulumi.Input<string>;
}

export interface AccountsDatabaseApiKeyV2GlobalAccessRule {
    /**
     * Access type for global access. Must be one of: GLOBAL_ACCESS_RULE_ACCESS_TYPE_MANAGE, GLOBAL_ACCESS_RULE_ACCESS_TYPE_READ_ONLY.
     */
    accessType: pulumi.Input<string>;
}

export interface AccountsHybridCloudEnvironmentConfiguration {
    /**
     * Advanced operator settings as a YAML string.
     */
    advancedOperatorSettings?: pulumi.Input<string | undefined>;
    /**
     * CA certificates for custom certificate authorities.
     */
    caCertificates?: pulumi.Input<string | undefined>;
    /**
     * Chart registry URL.
     */
    chartRepositoryUrl?: pulumi.Input<string | undefined>;
    /**
     * Container registry URL.
     */
    containerRegistryUrl?: pulumi.Input<string | undefined>;
    /**
     * Additional labels to apply to control plane components.
     */
    controlPlaneLabels?: pulumi.Input<pulumi.Input<inputs.AccountsHybridCloudEnvironmentConfigurationControlPlaneLabel>[] | undefined>;
    /**
     * Default database storage class.
     */
    databaseStorageClass?: pulumi.Input<string | undefined>;
    /**
     * Optional HTTP proxy URL.
     */
    httpProxyUrl?: pulumi.Input<string | undefined>;
    /**
     * Optional HTTPS proxy URL.
     */
    httpsProxyUrl?: pulumi.Input<string | undefined>;
    /**
     * Last modification timestamp of the configuration.
     */
    lastModifiedAt?: pulumi.Input<string | undefined>;
    /**
     * Log level for deployed components. Must be one of: HYBRID_CLOUD_ENVIRONMENT_CONFIGURATION_LOG_LEVEL_DEBUG, HYBRID_CLOUD_ENVIRONMENT_CONFIGURATION_LOG_LEVEL_ERROR, HYBRID_CLOUD_ENVIRONMENT_CONFIGURATION_LOG_LEVEL_INFO, HYBRID_CLOUD_ENVIRONMENT_CONFIGURATION_LOG_LEVEL_WARN.
     */
    logLevel?: pulumi.Input<string | undefined>;
    /**
     * The Kubernetes namespace where the Qdrant hybrid cloud components will be deployed.
     */
    namespace: pulumi.Input<string>;
    /**
     * List of hosts that should not be proxied.
     */
    noProxyConfigs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Node selector labels for scheduling control plane components.
     */
    nodeSelectors?: pulumi.Input<pulumi.Input<inputs.AccountsHybridCloudEnvironmentConfigurationNodeSelector>[] | undefined>;
    /**
     * Kubernetes secret name containing registry credentials.
     */
    registrySecretName?: pulumi.Input<string | undefined>;
    /**
     * Default snapshot storage class.
     */
    snapshotStorageClass?: pulumi.Input<string | undefined>;
    /**
     * Tolerations for scheduling control plane components.
     */
    tolerations?: pulumi.Input<pulumi.Input<inputs.AccountsHybridCloudEnvironmentConfigurationToleration>[] | undefined>;
    /**
     * Default volume snapshot storage class.
     */
    volumeSnapshotStorageClass?: pulumi.Input<string | undefined>;
}

export interface AccountsHybridCloudEnvironmentConfigurationControlPlaneLabel {
    key: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface AccountsHybridCloudEnvironmentConfigurationNodeSelector {
    key: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface AccountsHybridCloudEnvironmentConfigurationToleration {
    /**
     * The toleration effect. Must be one of: TOLERATION_EFFECT_NO_EXECUTE, TOLERATION_EFFECT_NO_SCHEDULE, TOLERATION_EFFECT_PREFER_NO_SCHEDULE.
     */
    effect?: pulumi.Input<string | undefined>;
    key?: pulumi.Input<string | undefined>;
    /**
     * The toleration operator. Must be one of: TOLERATION_OPERATOR_EQUAL, TOLERATION_OPERATOR_EXISTS.
     */
    operator?: pulumi.Input<string | undefined>;
    tolerationSeconds?: pulumi.Input<number | undefined>;
    value?: pulumi.Input<string | undefined>;
}

export interface AccountsHybridCloudEnvironmentStatus {
    capabilities?: pulumi.Input<pulumi.Input<inputs.AccountsHybridCloudEnvironmentStatusCapability>[] | undefined>;
    clusterCreationReadiness?: pulumi.Input<string | undefined>;
    componentStatuses?: pulumi.Input<pulumi.Input<inputs.AccountsHybridCloudEnvironmentStatusComponentStatus>[] | undefined>;
    kubernetesDistribution?: pulumi.Input<string | undefined>;
    kubernetesVersion?: pulumi.Input<string | undefined>;
    lastModifiedAt?: pulumi.Input<string | undefined>;
    message?: pulumi.Input<string | undefined>;
    numberOfNodes?: pulumi.Input<number | undefined>;
    phase?: pulumi.Input<string | undefined>;
    storageClasses?: pulumi.Input<pulumi.Input<inputs.AccountsHybridCloudEnvironmentStatusStorageClass>[] | undefined>;
    volumeSnapshotClasses?: pulumi.Input<pulumi.Input<inputs.AccountsHybridCloudEnvironmentStatusVolumeSnapshotClass>[] | undefined>;
}

export interface AccountsHybridCloudEnvironmentStatusCapability {
    volumeExpansion?: pulumi.Input<boolean | undefined>;
    volumeSnapshot?: pulumi.Input<boolean | undefined>;
}

export interface AccountsHybridCloudEnvironmentStatusComponentStatus {
    message?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    namespace?: pulumi.Input<string | undefined>;
    phase?: pulumi.Input<string | undefined>;
    version?: pulumi.Input<string | undefined>;
}

export interface AccountsHybridCloudEnvironmentStatusStorageClass {
    allowVolumeExpansion?: pulumi.Input<boolean | undefined>;
    default?: pulumi.Input<boolean | undefined>;
    name?: pulumi.Input<string | undefined>;
    parameters?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    provisioner?: pulumi.Input<string | undefined>;
    reclaimPolicy?: pulumi.Input<string | undefined>;
}

export interface AccountsHybridCloudEnvironmentStatusVolumeSnapshotClass {
    driver?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfo {
    cloudProviderId?: pulumi.Input<string | undefined>;
    cloudProviderRegionId?: pulumi.Input<string | undefined>;
    configurations?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfiguration>[] | undefined>;
    name?: pulumi.Input<string | undefined>;
    resourcesSummaries?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoResourcesSummary>[] | undefined>;
    restorePackageId?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfiguration {
    allowedIpSourceRanges?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    annotations?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationAnnotation>[] | undefined>;
    clusterStorageConfigurations?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationClusterStorageConfiguration>[] | undefined>;
    databaseConfigurations?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfiguration>[] | undefined>;
    gpuType?: pulumi.Input<string | undefined>;
    lastModifiedAt?: pulumi.Input<string | undefined>;
    nodeConfigurations?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationNodeConfiguration>[] | undefined>;
    nodeSelectors?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationNodeSelector>[] | undefined>;
    numberOfNodes?: pulumi.Input<number | undefined>;
    podLabels?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationPodLabel>[] | undefined>;
    rebalanceStrategy?: pulumi.Input<string | undefined>;
    reservedCpuPercentage?: pulumi.Input<number | undefined>;
    reservedMemoryPercentage?: pulumi.Input<number | undefined>;
    restartPolicy?: pulumi.Input<string | undefined>;
    serviceAnnotations?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationServiceAnnotation>[] | undefined>;
    serviceType?: pulumi.Input<string | undefined>;
    tolerations?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationToleration>[] | undefined>;
    topologySpreadConstraints?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationTopologySpreadConstraint>[] | undefined>;
    version?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationAnnotation {
    key?: pulumi.Input<string | undefined>;
    value?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationClusterStorageConfiguration {
    databaseStorageClass?: pulumi.Input<string | undefined>;
    snapshotStorageClass?: pulumi.Input<string | undefined>;
    storageTierType?: pulumi.Input<string | undefined>;
    volumeSnapshotClass?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfiguration {
    auditLoggings?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationAuditLogging>[] | undefined>;
    collections?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationCollection>[] | undefined>;
    inferences?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationInference>[] | undefined>;
    logLevel?: pulumi.Input<string | undefined>;
    services?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationService>[] | undefined>;
    storages?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStorage>[] | undefined>;
    tls?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationTl>[] | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationAuditLogging {
    enabled?: pulumi.Input<boolean | undefined>;
    maxLogFiles?: pulumi.Input<number | undefined>;
    rotation?: pulumi.Input<string | undefined>;
    trustForwardedHeaders?: pulumi.Input<boolean | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationCollection {
    replicationFactor?: pulumi.Input<number | undefined>;
    vectors?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationCollectionVector>[] | undefined>;
    writeConsistencyFactor?: pulumi.Input<number | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationCollectionVector {
    onDisk?: pulumi.Input<boolean | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationInference {
    enabled?: pulumi.Input<boolean | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationService {
    apiKeys?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKey>[] | undefined>;
    enableTls?: pulumi.Input<boolean | undefined>;
    forceIncludeJwtRbac?: pulumi.Input<boolean | undefined>;
    jwtRbac?: pulumi.Input<boolean | undefined>;
    readOnlyApiKeys?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKey>[] | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceApiKey {
    secretKey?: pulumi.Input<string | undefined>;
    secretName?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationServiceReadOnlyApiKey {
    secretKey?: pulumi.Input<string | undefined>;
    secretName?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStorage {
    performances?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance>[] | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationStoragePerformance {
    asyncScorer?: pulumi.Input<boolean | undefined>;
    optimizerCpuBudget?: pulumi.Input<number | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationTl {
    certs?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationTlCert>[] | undefined>;
    keys?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationTlKey>[] | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationTlCert {
    secretKey?: pulumi.Input<string | undefined>;
    secretName?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationDatabaseConfigurationTlKey {
    secretKey?: pulumi.Input<string | undefined>;
    secretName?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationNodeConfiguration {
    packageId?: pulumi.Input<string | undefined>;
    resourceConfigurations?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoConfigurationNodeConfigurationResourceConfiguration>[] | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationNodeConfigurationResourceConfiguration {
    amount?: pulumi.Input<number | undefined>;
    resourceType?: pulumi.Input<string | undefined>;
    resourceUnit?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationNodeSelector {
    key?: pulumi.Input<string | undefined>;
    value?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationPodLabel {
    key?: pulumi.Input<string | undefined>;
    value?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationServiceAnnotation {
    key?: pulumi.Input<string | undefined>;
    value?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationToleration {
    effect?: pulumi.Input<string | undefined>;
    key?: pulumi.Input<string | undefined>;
    operator?: pulumi.Input<string | undefined>;
    tolerationSeconds?: pulumi.Input<number | undefined>;
    value?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoConfigurationTopologySpreadConstraint {
    maxSkew?: pulumi.Input<number | undefined>;
    topologyKey?: pulumi.Input<string | undefined>;
    whenUnsatisfiable?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoResourcesSummary {
    cpus?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoResourcesSummaryCpus>[] | undefined>;
    disks?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoResourcesSummaryDisk>[] | undefined>;
    rams?: pulumi.Input<pulumi.Input<inputs.AccountsManualBackupClusterInfoResourcesSummaryRam>[] | undefined>;
}

export interface AccountsManualBackupClusterInfoResourcesSummaryCpus {
    amount?: pulumi.Input<number | undefined>;
    unit?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoResourcesSummaryDisk {
    amount?: pulumi.Input<number | undefined>;
    unit?: pulumi.Input<string | undefined>;
}

export interface AccountsManualBackupClusterInfoResourcesSummaryRam {
    amount?: pulumi.Input<number | undefined>;
    unit?: pulumi.Input<string | undefined>;
}

export interface AccountsRolePermission {
    /**
     * Permission category (e.g., "Cluster", "Account").
     */
    category?: pulumi.Input<string | undefined>;
    /**
     * Permission value (e.g., "read:backups").
     */
    value: pulumi.Input<string>;
}

